/**
 * run.mjs — RangerFlow vs React Flow, side by side.
 *
 *   node gallery/rangerflow/bench/compare/run.mjs [N]
 *   npm run rangerflow:bench:compare -- 500
 *
 * Runs:
 *   1. RangerFlow `--bench N --json` (paths, force, layered, scene, drag)
 *   2. React Flow stack in Node (@xyflow/system paths + d3-force)
 *
 * Writes gallery/rangerflow/out/bench-compare.md and bench-compare.json.
 * Copy into docs/BENCH.md when the numbers are worth keeping.
 */
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "../../../..");
const OUT_DIR = path.join(REPO, "gallery/rangerflow/out");
const HARNESS = path.join(REPO, "gallery/rangerflow/harness");

const sizes = [];
for (const a of process.argv.slice(2)) {
  if (/^\d+$/.test(a)) sizes.push(parseInt(a, 10));
}
if (sizes.length === 0) sizes.push(100, 500, 1000);

function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, {
    cwd: REPO,
    encoding: "utf8",
    maxBuffer: 20 * 1024 * 1024,
    ...opts,
  });
  if (r.status !== 0) {
    console.error(r.stdout || "");
    console.error(r.stderr || "");
    throw new Error(`${cmd} ${args.join(" ")} exited ${r.status}`);
  }
  return r.stdout || "";
}

function ensureHarness() {
  if (!fs.existsSync(path.join(HARNESS, "node_modules", "@xyflow", "system"))) {
    console.log("installing harness deps (@xyflow/system, d3-force)…");
    run("npm", ["install", "--silent", "--no-audit", "--no-fund"], {
      cwd: HARNESS,
    });
  }
}

function buildRanger() {
  console.log("building RangerFlow demo…");
  run("npm", ["run", "--silent", "rangerflow:build"]);
}

function runRanger(n) {
  console.log(`\n-- RangerFlow n=${n} --`);
  const out = run("node", [
    "./gallery/rangerflow/bin/rangerflow_demo.js",
    "--bench",
    String(n),
    "--json",
  ]);
  process.stdout.write(out);
  const p = path.join(OUT_DIR, "bench-rangerflow.json");
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

function runReactDirect(n) {
  console.log(`\n-- React Flow stack n=${n} --`);
  const out = spawnSync(
    "node",
    [path.join(HARNESS, "oracles", "reactflow_perf.mjs"), String(n)],
    {
      cwd: REPO,
      encoding: "utf8",
      maxBuffer: 10 * 1024 * 1024,
    }
  );
  process.stdout.write(out.stdout || "");
  if (out.status !== 0) {
    console.error(out.stderr || "");
    throw new Error("reactflow_perf failed");
  }
  return JSON.parse(fs.readFileSync(path.join(OUT_DIR, "bench-reactflow.json"), "utf8"));
}

function fmt(ms) {
  if (ms == null || Number.isNaN(ms)) return "—";
  if (ms < 10) return ms.toFixed(2) + " ms";
  return Math.round(ms) + " ms";
}

function ratio(a, b) {
  if (a == null || b == null || b === 0) return "—";
  const r = a / b;
  if (r < 1) return (1 / r).toFixed(2) + "× faster";
  if (r > 1) return r.toFixed(2) + "× slower";
  return "even";
}

function tableRow(label, rf, xy, note) {
  return `| ${label} | ${fmt(rf)} | ${fmt(xy)} | ${ratio(rf, xy)} | ${note || ""} |`;
}

ensureHarness();
buildRanger();

const rows = [];
for (const n of sizes) {
  const ranger = runRanger(n);
  const react = runReactDirect(n);
  rows.push({ n, ranger, react });
}

const lines = [];
lines.push("# RangerFlow vs React Flow — performance");
lines.push("");
lines.push(`**Generated by \`npm run rangerflow:bench:compare\`.** Node ${process.version}, this machine.`);
lines.push("");
lines.push("What is compared in Node is the shared *math*: edge-path generation");
lines.push("(`@xyflow/system` vs `EdgeRouter`) and force layout (`d3-force` vs");
lines.push("`FlowSimulation`) on the **same** graph shape. Scene build and drag");
lines.push("are RangerFlow-only in Node — React Flow paints through the DOM.");
lines.push("");

for (const { n, ranger, react } of rows) {
  lines.push(`## ${n} nodes / ${ranger.edges} edges`);
  lines.push("");
  lines.push("| Step | RangerFlow | React Flow stack | Ranger vs RF | Note |");
  lines.push("| --- | ---: | ---: | --- | --- |");
  lines.push(
    tableRow(
      `edge paths (${ranger.path_cases})`,
      ranger.path_ms,
      react.path_ms,
      "EdgeRouter vs getBezier/Straight/SmoothStep"
    )
  );
  lines.push(
    tableRow(
      "force layout, 300 ticks",
      ranger.force_ms,
      react.force_ms,
      "FlowSimulation vs d3-force, same graph"
    )
  );
  lines.push(
    tableRow(
      "layered layout",
      ranger.layered_ms,
      null,
      "Ranger only — React Flow has no built-in Sugiyama"
    )
  );
  lines.push(
    tableRow(
      "scene build (fit)",
      ranger.scene_fit_ms,
      null,
      `${ranger.drawn_fit} drawn / ${ranger.culled_fit} culled`
    )
  );
  lines.push(
    tableRow(
      "scene build (1:1 zoom)",
      ranger.scene_zoom_ms,
      null,
      `${ranger.drawn_zoom} drawn / ${ranger.culled_zoom} culled`
    )
  );
  lines.push(
    tableRow(
      "drag, ms/frame",
      ranger.drag_ms_per_frame,
      null,
      "EVG display-list rebuild (RF is DOM)"
    )
  );
  lines.push("");
}

lines.push("## How to read this");
lines.push("");
lines.push("- **Path and force rows are the fair fight.** Same cases, same graph,");
lines.push("  same machine, Node only.");
lines.push("- **Scene / drag in Node** measure RangerFlow's EVG display-list path.");
lines.push("  React Flow's equivalent is React reconciliation + SVG/HTML nodes.");
lines.push("- Behavioural parity (does the line go the same place?) is scored by");
lines.push("  `npm run rangerflow:parity`, not here. Last checked overall **~98.6%**.");
lines.push("");

fs.mkdirSync(OUT_DIR, { recursive: true });
const mdPath = path.join(OUT_DIR, "bench-compare.md");
const jsonPath = path.join(OUT_DIR, "bench-compare.json");
fs.writeFileSync(mdPath, lines.join("\n"));
fs.writeFileSync(
  jsonPath,
  JSON.stringify(
    {
      at: new Date().toISOString(),
      node: process.version,
      sizes,
      rows,
    },
    null,
    2
  )
);

console.log("\n" + lines.join("\n"));
console.log(`\nwrote ${mdPath}`);
console.log(`wrote ${jsonPath}`);
