/**
 * examples.mjs — compile landing/examples/Cart.rgr to the targets the front
 * page shows, and write them as landing/assets/targets.js.
 *
 *   node landing/tools/examples.mjs
 *
 * The point of the section it feeds is that the code beside "Swift" is the
 * code this compiler writes, so it is generated here rather than pasted. The
 * site build runs this first; the result is committed as well, so the page
 * can be opened from a checkout without a compile.
 */
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const SRC = "landing/examples/Cart.rgr";
const TMP = path.join(ROOT, ".landing_tmp/examples");
const OUT = path.join(ROOT, "landing/assets/targets.js");

/** label — what the page calls it; flag — what the CLI calls it. */
const TARGETS = [
  { id: "swift",  label: "Swift",      flag: "-l=swift6", ext: "swift", hl: "swift",  note: "swift6" },
  { id: "kotlin", label: "Kotlin",     flag: "-l=kotlin", ext: "kt",    hl: "kotlin", note: "kotlin" },
  { id: "js",     label: "JavaScript", flag: "-es6",      ext: "js",    hl: "js",     note: "es6" },
  { id: "ts",     label: "TypeScript", flag: "-es6 -typescript", ext: "ts", hl: "ts", note: "es6 -typescript" },
  { id: "csharp", label: "C#",         flag: "-l=csharp", ext: "cs",    hl: "csharp", note: "csharp" },
  // C++ and Rust open with the small runtime the target needs — the optional
  // union, the pointer alias, the string helpers. It is the same header for
  // every program, so the tab starts at the code that is this program's.
  { id: "cpp",    label: "C++",        flag: "-l=cpp",    ext: "cpp",   hl: "cpp",    note: "cpp",
    from: /^(#[a-z]+ .*\n)*class CartLine \{/m },
  { id: "php",    label: "PHP",        flag: "-l=php",    ext: "php",   hl: "php",    note: "php" },
  { id: "rust",   label: "Rust",       flag: "-l=rust",   ext: "rs",    hl: "rust",   note: "rust",
    from: /^#\[derive\(Clone\)\]\nstruct CartLine \{/m },
];

const env = { ...process.env, RANGER_LIB: "./compiler/Lang.rgr:./lib/stdops.rgr" };
fs.mkdirSync(TMP, { recursive: true });

const out = {};
for (const t of TARGETS) {
  const file = `Cart_${t.id}.${t.ext}`;
  const log = execFileSync("node",
    ["dist/rgrc.js", ...t.flag.split(" "), SRC, `-d=${path.relative(ROOT, TMP)}`, `-o=${file}`],
    { cwd: ROOT, env, encoding: "utf8", stdio: ["ignore", "pipe", "inherit"] });
  // The compiler exits 0 even when it failed, so the log is the status.
  if (log.includes("[FAIL]") || log.includes("Compilation FAILED")) {
    console.error(log);
    throw new Error(`${SRC} did not compile for ${t.label}`);
  }
  const written = path.join(TMP, file);
  if (!fs.existsSync(written)) throw new Error(`no output for ${t.label} (expected ${written})`);
  let code = fs.readFileSync(written, "utf8").replace(/\r\n/g, "\n").trim();
  // Cart is a library, not a CLI. Drop a Node shebang if one was written, and
  // the C++ argc/argv globals every program on that target carries.
  code = code.replace(/^#!\/usr\/bin\/env node\n/, "");
  code = code.replace(/\nint __g_argc;\nchar \*\*__g_argv;\n/, "\n");
  let skipped = 0;
  if (t.from) {
    const at = code.search(t.from);
    if (at < 0) throw new Error(`${t.label}: could not find where the program starts`);
    skipped = code.slice(0, at).split("\n").length - 1;
    code = code.slice(at).trim();
  }
  out[t.id] = {
    label: t.label,
    hl: t.hl,
    skipped,
    cmd: `rgrc -${t.note.startsWith("es6") ? t.note.replace("es6", "l=es6") : `l=${t.note}`} Cart.rgr`,
    code,
  };
  console.log(`  ${t.label.padEnd(11)} ${String(out[t.id].code.split("\n").length).padStart(3)} lines` +
    (skipped ? `   (after ${skipped} lines of target runtime)` : ""));
}

const source = fs.readFileSync(path.join(ROOT, SRC), "utf8")
  .replace(/\r\n/g, "\n")
  // Drop the file's own header comment: the page says where the file is.
  .replace(/^(?:;[^\n]*\n|\n)+/, "")
  .trim();

const banner = `// Generated by landing/tools/examples.mjs from ${SRC} — do not edit.
// Every string below is what this commit's compiler wrote for that target.
`;
fs.writeFileSync(OUT,
  `${banner}window.RANGER_TARGETS = ${JSON.stringify({ source, targets: out }, null, 1)};\n`);
console.log(`wrote ${path.relative(ROOT, OUT)} (${(fs.statSync(OUT).size / 1024).toFixed(1)} KB)`);
