#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Rafi's page, assembled — the Fig editor with its chrome drawn by Ranger.
//
//   npm run rafi:web                      # beside the sources
//   node gallery/figma/web/rafi/build.mjs --out DIR    # for the site
//
// No bundler, the same way gallery/mfiles' console is built: the compiled
// Ranger app is one CommonJS file wrapped as an ES module, the EVG stylesheet
// becomes a string in generated.js, and EVG's browser helpers are copied
// beside the page, followed transitively from what main.js imports.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MODULE = path.join(HERE, "..", "..");          // gallery/figma
const GALLERY = path.join(MODULE, "..");             // gallery

const argv = process.argv.slice(2);
const outFlag = argv.indexOf("--out");
const OUT = outFlag >= 0 ? path.resolve(argv[outFlag + 1]) : null;

const COMPILED = path.join(MODULE, "bin", "RafiApp.cjs");
if (!fs.existsSync(COMPILED)) {
  console.error("the app is not built — run `npm run rafi:build` first");
  process.exit(3);
}

// --- the app, as an ES module ---------------------------------------------------
const cjs = fs.readFileSync(COMPILED, "utf8");
const names = [...cjs.matchAll(/^module\.exports\.(\w+)\s*=/gm)].map((m) => m[1]);
if (!names.includes("RafiApp")) {
  console.error("the compiled module does not export RafiApp");
  process.exit(4);
}
const wrapped = `// Generated by gallery/figma/web/rafi/build.mjs — do not edit.
// SPDX-License-Identifier: AGPL-3.0-or-later
const module = { exports: {} };
{
${cjs}
}
const RafiModule = module.exports;
export default RafiModule;
export const { ${names.join(", ")} } = RafiModule;
`;
fs.writeFileSync(path.join(HERE, "generated-host.js"), wrapped);

// --- the stylesheet, as a string ---------------------------------------------------
fs.writeFileSync(
  path.join(HERE, "generated.js"),
  "// Generated by gallery/figma/web/rafi/build.mjs — do not edit.\n" +
    `export const CSS = ${JSON.stringify(fs.readFileSync(path.join(HERE, "rafi.css"), "utf8"))};\n`
);

// --- EVG's browser helpers ----------------------------------------------------------
const ENTRY_IMPORTS = ["evg/gl/evg-webgl.js", "evg/gl/evg-a11y.js", "evg/gl/evg-measure.js"];

function relativeImports(text) {
  const out = [];
  for (const m of text.matchAll(/(?:^|\s)(?:import|export)[^;]*?from\s*["'](\.[^"']+)["']/g)) out.push(m[1]);
  for (const m of text.matchAll(/import\s*\(\s*["'](\.[^"']+)["']\s*\)/g)) out.push(m[1]);
  return out;
}

function helperClosure() {
  const seen = new Set();
  const queue = [...ENTRY_IMPORTS];
  while (queue.length) {
    const rel = queue.shift();
    if (seen.has(rel)) continue;
    const from = path.join(GALLERY, rel);
    if (!fs.existsSync(from)) {
      console.error(`the page imports ${rel}, which is not in gallery/`);
      process.exit(4);
    }
    seen.add(rel);
    for (const next of relativeImports(fs.readFileSync(from, "utf8"))) {
      queue.push(path.posix.normalize(path.posix.join(path.posix.dirname(rel), next)));
    }
  }
  return [...seen];
}

const HELPERS = helperClosure();
function copyHelpers(root) {
  for (const rel of HELPERS) {
    const to = path.join(root, rel);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(path.join(GALLERY, rel), to);
  }
}
copyHelpers(HERE);

// The document the page opens on, which is the same one the DOM editor starts
// with: a real file rather than a screenshot of one.
function copyFixtures(root) {
  const dir = path.join(root, "fixtures");
  fs.mkdirSync(dir, { recursive: true });
  for (const f of fs.readdirSync(path.join(MODULE, "fixtures")).filter((f) => f.endsWith(".fig"))) {
    fs.copyFileSync(path.join(MODULE, "fixtures", f), path.join(dir, f));
  }
}
copyFixtures(HERE);

function assertResolvable(root) {
  for (const name of ["main.js", "generated-host.js", "generated.js"]) {
    const file = path.join(root, name);
    for (const rel of relativeImports(fs.readFileSync(file, "utf8"))) {
      if (!fs.existsSync(path.join(path.dirname(file), rel))) {
        console.error(`${name} imports ${rel}, which is not beside it in ${path.relative(process.cwd(), root)}`);
        process.exit(4);
      }
    }
  }
  if (!fs.existsSync(path.join(root, "fixtures", "health.fig"))) {
    console.error(`the page opens on fixtures/health.fig, which is not in ${path.relative(process.cwd(), root)}`);
    process.exit(4);
  }
}
assertResolvable(HERE);

if (OUT) {
  fs.mkdirSync(OUT, { recursive: true });
  for (const name of ["index.html", "main.js", "generated-host.js", "generated.js"]) {
    fs.copyFileSync(path.join(HERE, name), path.join(OUT, name));
  }
  copyHelpers(OUT);
  copyFixtures(OUT);
  assertResolvable(OUT);
  process.stdout.write(`  ${path.relative(process.cwd(), OUT)}  index.html + ${HELPERS.length + 3} modules\n`);
} else {
  const kb = (wrapped.length / 1024).toFixed(0);
  process.stdout.write(`  gallery/figma/web/rafi  generated-host.js ${kb} kB, EVG helpers and fixtures copied\n`);
}
