#!/usr/bin/env python3
# Generates gallery/math/src/MathFontData.rgr from the KaTeX package:
# glyph outlines (fontTools) and metrics (src/fontMetricsData.js) of the
# fonts the typesetter uses, and the symbol table (src/symbols.ts).
#
#   npm pack katex && tar xzf katex-*.tgz      # -> ./package
#   pip install fonttools
#   python3 gallery/math/tools/gen_math_font.py ./package > gallery/math/src/MathFontData.rgr
#
# The fonts are SIL OFL 1.1 (see gallery/math/FONTS-LICENSE.txt); only the
# outlines and metrics are carried, as data, not the font files.
import json, re, sys
from fontTools.ttLib import TTFont
from fontTools.pens.basePen import BasePen

pkg = sys.argv[1]

class Pen(BasePen):
    def __init__(s, gs):
        super().__init__(gs); s.o = []
    def _moveTo(s, p): s.o.append(('M', [p]))
    def _lineTo(s, p): s.o.append(('L', [p]))
    def _qCurveToOne(s, a, b): s.o.append(('Q', [a, b]))
    def _curveToOne(s, a, b, c): s.o.append(('C', [a, b, c]))
    def _closePath(s): s.o.append(('Z', []))
    def _endPath(s): s.o.append(('Z', []))

src = open(f'{pkg}/src/fontMetricsData.js').read()
src = src[src.index('{'):].rstrip().rstrip(';')
src = re.sub(r',\s*}', '}', src)
metrics = json.loads(src)

# symbols.ts: defineSymbol(math, main|ams, group, "replace", "name")
syms = []
seen = set()
for m in re.finditer(r'defineSymbol\(math,\s*(main|ams),\s*(\w+),\s*("(?:[^"\\]|\\.)*"|null),\s*("(?:[^"\\]|\\.)*")(,\s*true)?', open(f'{pkg}/src/symbols.ts').read()):
    font, group, rep, name = m.group(1), m.group(2), m.group(3), m.group(4)
    if rep == 'null': continue
    rep = json.loads(rep); name = json.loads(name)
    if len(rep) != 1 or group == 'spacing': continue
    if name in seen: continue
    seen.add(name)
    syms.append((name, font, group, ord(rep)))
    if m.group(5):
        key = '#%d' % ord(rep) if ord(rep) > 127 else rep
        if key not in seen:
            seen.add(key)
            syms.append((key, font, group, ord(rep)))

letters = [ord(c) for c in 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789']
amsNames = r'\therefore \because \nexists \varnothing \square \blacksquare \leqslant \geqslant \lesssim \gtrsim \subsetneq \supsetneq \checkmark \complement \nleq \ngeq \nmid \nparallel \nsubseteq \nsupseteq \lozenge \blacktriangle \triangleq \circledast \boxplus \boxtimes \ltimes \rtimes \twoheadrightarrow \leftleftarrows \rightrightarrows \measuredangle \eqsim \approxeq \backsim \smallsetminus \nless \ngtr \ncong \nsim \leftrightarrows \rightleftarrows \Rrightarrow \Lleftarrow \upharpoonright \restriction \digamma \varkappa \hbar \hslash \ulcorner \urcorner \llcorner \lrcorner \vDash \Vdash \nvdash \nvDash \intercal \dotplus \veebar \barwedge \doublebarwedge \centerdot \circleddash \circledcirc \divideontimes \varpropto \blacktriangleright \blacktriangleleft \vartriangle \triangledown \bigstar \diagup \diagdown'.split()
ams = set(letters[:26])
for name, font, group, cp in syms:
    if font == 'ams' and name in amsNames: ams.add(cp)

FONTS = [
    ('Main-Regular', None),
    ('Math-Italic', None),
    ('Main-Bold', set(letters) | set(range(0x391, 0x3aa)) | {ord(c) for c in '()[]{}+-=,.;:!?/|*<>\'"'} | {0x2212, 0xd7, 0xb7}),
    ('AMS-Regular', ams),
    ('Caligraphic-Regular', None),
    ('Size1-Regular', None),
    ('Size2-Regular', None),
    ('Size3-Regular', None),
    ('Size4-Regular', None),
]

def enc(ops):
    out = []; px = py = 0
    for op, pts in ops:
        s = op
        nums = []
        for x, y in pts:
            x = round(x); y = round(y)
            nums += [x - px, y - py]; px, py = x, y
        s += ' '.join(str(n) for n in nums)
        out.append(s)
    return ''.join(out)

def lit(s, ind='        '):
    # str_append in chunks: one Ranger line each
    lines = []
    for i in range(0, len(s), 160):
        lines.append(f'{ind}str_append s "{s[i:i+160]}"')
    return '\n'.join(lines)

print('''; SPDX-License-Identifier: AGPL-3.0-or-later
; ==============================================================================
; MathFontData.rgr — GENERATED by gallery/math/tools/gen_math_font.py. Do not edit.
; ==============================================================================
;
; Glyph outlines and metrics of the KaTeX fonts (SIL OFL 1.1, derived from the
; Computer Modern and AMS fonts; see gallery/math/FONTS-LICENSE.txt), and the
; symbol table of KaTeX's src/symbols.ts (MIT).
;
; One string per font: glyphs separated by `|`, each
;
;     cp,width,height,depth,italic,skew,PATH
;
; metrics in 1/1000 em, PATH in font units (1000/em, y up) as M/L/Q/Z with
; every coordinate relative to the one before it.
; ==============================================================================

class MathFontData {''')
print('    sfn fontCount:int () {\n        return %d\n    }\n' % len(FONTS))
print('    sfn fontName:string (i:int) {')
for i, (f, _) in enumerate(FONTS):
    print(f'        if (i == {i}) {{ return "{f}" }}')
print('        return ""\n    }\n')
print('    sfn glyphs:string (i:int) {')
for i in range(len(FONTS)):
    print(f'        if (i == {i}) {{ return (MathFontData.font{i}()) }}')
print('        return ""\n    }\n')
total = 0
for i, (f, only) in enumerate(FONTS):
    t = TTFont(f'{pkg}/dist/fonts/KaTeX_{f}.ttf')
    cm = t.getBestCmap(); gs = t.getGlyphSet()
    parts = []
    for cps, mt in metrics[f].items():
        cp = int(cps)
        if only is not None and cp not in only: continue
        d, h, ic, sk, w = mt
        path = ''
        if cp in cm:
            p = Pen(gs); gs[cm[cp]].draw(p); path = enc(p.o)
        parts.append(f'{cp},{round(w*1000)},{round(h*1000)},{round(d*1000)},{round(ic*1000)},{round(sk*1000)},{path}')
    s = '|'.join(parts); total += len(s)
    print(f'    ; {f}: {len(parts)} glyphs')
    print(f'    sfn font{i}:string () {{\n        def s:string ""')
    print(lit(s))
    print('        return s\n    }\n')
fi = {'main': 0, 'ams': 3}
ss = ';'.join(f'{n},{fi[f]},{g},{cp}' for n, f, g, cp in syms if ';' not in n and ',' not in n and '"' not in n and '\\\\' not in n[1:] and all(ord(c) < 128 for c in n))
# names are stored without escapes: a backslash is written as `!`
ss = ss.replace('\\', '!')
print('    ; name,font,group,codepoint;… — names spelled with `!` for the backslash')
print('    sfn symbols:string () {\n        def s:string ""')
print(lit(ss))
print('        return s\n    }\n}')
print(f'generated {total} chars of glyph data, {len(syms)} symbols', file=sys.stderr)
