#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Regenerate uix/uix-api.js from the official type declarations.
//
//   npm pack @m-filescorporation/uix-extensions && tar xzf m-filescorporation-uix-extensions-*.tgz
//   node gallery/mfiles/tools/gen-uix-api.mjs ./package
//
// The emulator's API surface must be M-Files' own, not a transcription of it:
// every enum a UIX v2 application can import, with the numbers it will carry,
// and the exact list of IVault operations. Both come out of index.d.ts and
// vault.d.ts here, so a new package version is a re-run, not a hunt through a
// diff for renamed members.
//
// The output holds facts (names and numbers), not code from the package.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const pkg = process.argv[2];
if (!pkg) {
  console.error("usage: gen-uix-api.mjs <path to the unpacked @m-filescorporation/uix-extensions package>");
  process.exit(2);
}
const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, "..", "uix", "uix-api.js");

const meta = JSON.parse(fs.readFileSync(path.join(pkg, "package.json"), "utf8"));
const index = fs.readFileSync(path.join(pkg, "index.d.ts"), "utf8");
const vault = fs.readFileSync(path.join(pkg, "vault.d.ts"), "utf8");

function stripComments(text) {
  return text.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/[^\n]*/g, "");
}

function enumsOf(text) {
  const out = {};
  const re = /export\s+(?:declare\s+)?enum\s+(\w+)\s*\{([\s\S]*?)\n\}/g;
  for (const m of stripComments(text).matchAll(re)) {
    const members = {};
    let next = 0;
    for (const raw of m[2].split(",")) {
      const line = raw.trim();
      if (!line) continue;
      const eq = line.match(/^(\w+)\s*=\s*(.+)$/);
      if (eq) {
        const v = eq[2].trim();
        if (/^-?\d+$/.test(v)) {
          members[eq[1]] = Number(v);
          next = Number(v) + 1;
        } else {
          members[eq[1]] = JSON.parse(v.replace(/'/g, '"'));
        }
      } else if (/^\w+$/.test(line)) {
        members[line] = next;
        next += 1;
      }
    }
    out[m[1]] = members;
  }
  return out;
}

function vaultApiOf(text) {
  const clean = stripComments(text);
  const start = clean.indexOf("export interface IVault {");
  if (start < 0) throw new Error("vault.d.ts has no IVault interface");
  const api = {};
  let group = null;
  let depth = 0;
  for (const line of clean.slice(start).split("\n").slice(1)) {
    const g = line.match(/^\s*(\w+)\s*:\s*\{\s*$/);
    if (g && depth === 0) {
      group = g[1];
      api[group] = [];
      depth = 1;
      continue;
    }
    if (depth === 1) {
      const m = line.match(/^\s*(\w+)\s*\(/);
      if (m) api[group].push(m[1]);
      if (/^\s*\};?\s*$/.test(line)) {
        depth = 0;
        group = null;
      }
      continue;
    }
    if (/^\}/.test(line)) break;
  }
  return api;
}

const enums = { ...enumsOf(vault), ...enumsOf(index) };
// TypeScript's runtime enum objects map numbers back to names, and code does
// read them that way (`Event[id]` in a log line).
const runtime = {};
for (const [name, members] of Object.entries(enums)) {
  const obj = {};
  for (const [k, v] of Object.entries(members)) {
    obj[k] = v;
  }
  for (const [k, v] of Object.entries(members)) {
    if (typeof v === "number" && !(String(v) in obj)) obj[v] = k;
  }
  runtime[name] = obj;
}
const api = vaultApiOf(vault);
const methodCount = Object.values(api).reduce((n, list) => n + list.length, 0);

const text = `// Generated by gallery/mfiles/tools/gen-uix-api.mjs — do not edit.
// Source: ${meta.name}@${meta.version} type declarations (MIT, M-Files Corporation).
// ${Object.keys(runtime).length} enums, ${Object.keys(api).length} vault operation groups, ${methodCount} vault methods.
var __MF_PACKAGE = ${JSON.stringify(`${meta.name}@${meta.version}`)};
var __MF_ENUMS = ${JSON.stringify(runtime)};
var __MF_VAULT_API = ${JSON.stringify(api, null, 1)};
`;
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, text);
console.log(`wrote ${path.relative(process.cwd(), OUT)}: ${Object.keys(runtime).length} enums, ${methodCount} vault methods`);
