#!/usr/bin/env node
class Test3  {
  constructor() {
  }
}
/* static JavaSript main routine at the end of the JS file */
function __js_main() {
  let names = [];
  names.push("hello");
  names.push("world");
  console.log(names[0]);
  console.log(names[1]);
  console.log("Done");
}
__js_main();
