#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The emulator page, assembled.
//
//   npm run mfiles:web:page                       # beside the sources
//   node gallery/mfiles/web/build.mjs --out DIR   # for the site
//
// No bundler, the same way gallery/firesim's console is built: the compiled
// Ranger app is one CommonJS file wrapped as an ES module; the stylesheet, the
// UIX preludes and the sample extensions become strings in generated.js; and
// EVG's browser helpers are copied beside the page, followed transitively from
// what main.js imports.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MODULE = path.join(HERE, "..");
const GALLERY = path.join(MODULE, "..");

const argv = process.argv.slice(2);
const outFlag = argv.indexOf("--out");
const OUT = outFlag >= 0 ? path.resolve(argv[outFlag + 1]) : null;

const COMPILED = path.join(MODULE, "bin", "MfilesApp.cjs");
if (!fs.existsSync(COMPILED)) {
  console.error("the app is not built — run `npm run mfiles:web:build` first");
  process.exit(3);
}

// --- the app, as an ES module ---------------------------------------------------
const cjs = fs.readFileSync(COMPILED, "utf8");
const names = [...cjs.matchAll(/^module\.exports\.(\w+)\s*=/gm)].map((m) => m[1]);
if (!names.includes("MfilesApp")) {
  console.error("the compiled module does not export MfilesApp");
  process.exit(4);
}
const wrapped = `// Generated by gallery/mfiles/web/build.mjs — do not edit.
// SPDX-License-Identifier: AGPL-3.0-or-later
const module = { exports: {} };
{
${cjs}
}
const MfilesModule = module.exports;
export default MfilesModule;
export const { ${names.join(", ")} } = MfilesModule;
`;
fs.writeFileSync(path.join(HERE, "generated-host.js"), wrapped);

// --- strings: the stylesheet, the preludes, the sample extensions --------------
const read = (rel) => fs.readFileSync(path.join(MODULE, rel), "utf8");
const scripts = {
  api: read("uix/uix-api.js"),
  core: read("uix/uix-core.js"),
  v1: read("uix/uix1-prelude.js"),
  v2: read("uix/uix2-prelude.js"),
  grpc: read("uix/mfgrpc.js"),
};
const extensions = fs
  .readdirSync(path.join(MODULE, "extensions"))
  .filter((f) => f.endsWith(".js"))
  .sort()
  .map((file) => {
    const source = read(path.join("extensions", file));
    const tag = (name) => (source.match(new RegExp("@" + name + "\\s+(.+)")) || [])[1]?.trim() ?? "";
    return { file, name: tag("name") || file, guid: tag("guid") || `{${file}}`, version: Number(tag("uix") || "2"), source };
  });
fs.writeFileSync(
  path.join(HERE, "generated.js"),
  "// Generated by gallery/mfiles/web/build.mjs — do not edit.\n" +
    `export const CSS = ${JSON.stringify(fs.readFileSync(path.join(HERE, "mfiles.css"), "utf8"))};\n` +
    `export const SCRIPTS = ${JSON.stringify(scripts)};\n` +
    `export const EXTENSIONS = ${JSON.stringify(extensions)};\n`
);

// --- EVG's browser helpers --------------------------------------------------------
const ENTRY_IMPORTS = ["evg/gl/evg-webgl.js", "evg/gl/evg-a11y.js", "evg/gl/evg-measure.js", "evg/gl/evg-textinput.js"];

function relativeImports(text) {
  const out = [];
  for (const m of text.matchAll(/(?:^|\s)(?:import|export)[^;]*?from\s*["'](\.[^"']+)["']/g)) out.push(m[1]);
  for (const m of text.matchAll(/import\s*\(\s*["'](\.[^"']+)["']\s*\)/g)) out.push(m[1]);
  return out;
}

function helperClosure() {
  const seen = new Set();
  const queue = [...ENTRY_IMPORTS];
  while (queue.length) {
    const rel = queue.shift();
    if (seen.has(rel)) continue;
    const from = path.join(GALLERY, rel);
    if (!fs.existsSync(from)) {
      console.error(`the page imports ${rel}, which is not in gallery/`);
      process.exit(4);
    }
    seen.add(rel);
    for (const next of relativeImports(fs.readFileSync(from, "utf8"))) {
      queue.push(path.posix.normalize(path.posix.join(path.posix.dirname(rel), next)));
    }
  }
  return [...seen];
}

const HELPERS = helperClosure();
function copyHelpers(root) {
  for (const rel of HELPERS) {
    const to = path.join(root, rel);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(path.join(GALLERY, rel), to);
  }
}
copyHelpers(HERE);

function assertResolvable(root) {
  for (const name of ["main.js", "generated-host.js", "generated.js"]) {
    const file = path.join(root, name);
    for (const rel of relativeImports(fs.readFileSync(file, "utf8"))) {
      if (!fs.existsSync(path.join(path.dirname(file), rel))) {
        console.error(`${name} imports ${rel}, which is not beside it in ${path.relative(process.cwd(), root)}`);
        process.exit(4);
      }
    }
  }
}
assertResolvable(HERE);

if (OUT) {
  fs.mkdirSync(OUT, { recursive: true });
  for (const name of ["index.html", "main.js", "generated-host.js", "generated.js"]) {
    fs.copyFileSync(path.join(HERE, name), path.join(OUT, name));
  }
  copyHelpers(OUT);
  assertResolvable(OUT);
  process.stdout.write(`  ${path.relative(process.cwd(), OUT)}  index.html + ${HELPERS.length + 3} modules\n`);
} else {
  const kb = (wrapped.length / 1024).toFixed(0);
  process.stdout.write(`  gallery/mfiles/web  generated-host.js ${kb} kB, ${extensions.length} sample extensions, EVG helpers copied\n`);
}
