#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The emulator page, assembled.
//
//   npm run mfiles:web:page                       # beside the sources
//   node gallery/mfiles/web/build.mjs --out DIR   # for the site
//
// No bundler, the same way gallery/firesim's console is built: the compiled
// Ranger app is one CommonJS file wrapped as an ES module; the stylesheet, the
// UIX preludes and the sample extensions become strings in generated.js; and
// EVG's browser helpers are copied beside the page, followed transitively from
// what main.js imports.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MODULE = path.join(HERE, "..");
const GALLERY = path.join(MODULE, "..");
// EVG's browser helpers live in lib/evg (MIT) since the engine left gallery/;
// the page keeps importing them as `evg/gl/…`, so resolve that prefix there.
const helperPath = (rel) => rel.startsWith("evg/") ? path.join(GALLERY, "..", "lib", rel) : path.join(GALLERY, rel);

const argv = process.argv.slice(2);
const outFlag = argv.indexOf("--out");
const OUT = outFlag >= 0 ? path.resolve(argv[outFlag + 1]) : null;
const REPO = path.join(GALLERY, "..");

const COMPILED = path.join(MODULE, "bin", "MfilesApp.cjs");
if (!fs.existsSync(COMPILED)) {
  console.error("the app is not built — run `npm run mfiles:web:build` first");
  process.exit(3);
}

// --- the app, as an ES module ---------------------------------------------------
const cjs = fs.readFileSync(COMPILED, "utf8");
const names = [...cjs.matchAll(/^module\.exports\.(\w+)\s*=/gm)].map((m) => m[1]);
if (!names.includes("MfilesApp")) {
  console.error("the compiled module does not export MfilesApp");
  process.exit(4);
}
const wrapped = `// Generated by gallery/mfiles/web/build.mjs — do not edit.
// SPDX-License-Identifier: AGPL-3.0-or-later
const module = { exports: {} };
{
${cjs}
}
const MfilesModule = module.exports;
export default MfilesModule;
export const { ${names.join(", ")} } = MfilesModule;
`;
fs.writeFileSync(path.join(HERE, "generated-host.js"), wrapped);

// --- strings: the stylesheet, the preludes, the sample extensions --------------
const read = (rel) => fs.readFileSync(path.join(MODULE, rel), "utf8");
const scripts = {
  api: read("uix/uix-api.js"),
  core: read("uix/uix-core.js"),
  v1: read("uix/uix1-prelude.js"),
  v2: read("uix/uix2-prelude.js"),
  grpc: read("uix/mfgrpc.js"),
};
const extensions = fs
  .readdirSync(path.join(MODULE, "extensions"))
  .filter((f) => f.endsWith(".js"))
  .sort()
  .map((file) => {
    const source = read(path.join("extensions", file));
    const tag = (name) => (source.match(new RegExp("@" + name + "\\s+(.+)")) || [])[1]?.trim() ?? "";
    return { file, name: tag("name") || file, guid: tag("guid") || `{${file}}`, version: Number(tag("uix") || "2"), source };
  });
fs.writeFileSync(
  path.join(HERE, "generated.js"),
  "// Generated by gallery/mfiles/web/build.mjs — do not edit.\n" +
    `export const CSS = ${JSON.stringify(fs.readFileSync(path.join(HERE, "mfiles.css"), "utf8"))};\n` +
    `export const SCRIPTS = ${JSON.stringify(scripts)};\n` +
    `export const EXTENSIONS = ${JSON.stringify(extensions)};\n`
);

// --- the Preview tab's viewers, fonts and sample files ------------------------------
// The Word viewer, the spreadsheet and the code editor are the gallery's own apps, compiled as
// they are for their own pages (classic scripts, loaded only when a preview is
// opened). They take half a minute to compile, so an existing build is kept;
// `--viewers` compiles them again.
const VIEWERS = [
  ["gallery/docx_viewer/web/docx_web.rgr", "docx_web.js"],
  ["gallery/datagrid/web/datagrid_web.rgr", "datagrid_web.js"],
  ["gallery/datagrid/web/code_editor_web.rgr", "code_editor_web.js"],
];
const VIEWER_DIR = path.join(HERE, "viewers");
// `-d` is joined onto cwd inside the compiler, so an absolute path becomes
// `<cwd>/<absolute>` (e.g. `/workspace/workspace/…`) and the file lands
// somewhere build.mjs never looks. Always pass a path relative to REPO.
const VIEWER_DIR_REL = path.relative(REPO, VIEWER_DIR) || ".";
fs.mkdirSync(VIEWER_DIR, { recursive: true });
for (const [source, out] of VIEWERS) {
  if (fs.existsSync(path.join(VIEWER_DIR, out)) && !argv.includes("--viewers")) continue;
  process.stdout.write(`  compiling ${source} …\n`);
  const log = execFileSync(process.execPath, ["dist/rgrc.js", "-es6", source, `-d=${VIEWER_DIR_REL}`, `-o=${out}`], {
    cwd: REPO,
    env: { ...process.env, RANGER_LIB: "./compiler/Lang.rgr:./lib/stdops.rgr" },
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });
  if (log.includes("[FAIL]") || !fs.existsSync(path.join(VIEWER_DIR, out))) {
    console.error(log.split("\n").filter((l) => l.includes("[FAIL]") || l.includes("rror")).slice(0, 20).join("\n"));
    console.error(`could not compile ${source}`);
    process.exit(5);
  }
}

const FONT_DIR = path.join(GALLERY, "pdf_writer", "assets", "fonts");
const FONT_FILES = {
  "OpenSans-Regular.ttf": "Open_Sans",
  "OpenSans-Bold.ttf": "Open_Sans",
  "OpenSans-Italic.ttf": "Open_Sans",
  "OpenSans-BoldItalic.ttf": "Open_Sans",
  "NotoSans-Regular.ttf": "Noto_Sans",
  "NotoSans-Bold.ttf": "Noto_Sans",
  "NotoEmoji-Regular.ttf": "Noto_Emoji",
};
// Every `samples/…` path the sample vault names, and the fixture it is.
const SAMPLES = {
  "hello.docx": "docx_viewer/fixtures/hello.docx",
  "20-business-report.docx": "docx_viewer/fixtures/20-business-report.docx",
  "styles_demo.docx": "docx_viewer/fixtures/styles_demo.docx",
  "lists_demo.docx": "docx_viewer/fixtures/lists_demo.docx",
  "05-table-basic.docx": "docx_viewer/fixtures/05-table-basic.docx",
  "12-header-footer.docx": "docx_viewer/fixtures/12-header-footer.docx",
  "sales.xlsx": "datagrid/fixtures/sales.xlsx",
};
const vaultSource = fs.readFileSync(path.join(MODULE, "src", "vault", "MfSampleVault.rgr"), "utf8");
for (const m of vaultSource.matchAll(/"samples\/([^"]+)"/g)) {
  if (!SAMPLES[m[1]]) {
    console.error(`the sample vault names samples/${m[1]}, which build.mjs does not know`);
    process.exit(4);
  }
}
function copyAssets(root) {
  for (const dir of ["fonts", "samples", "viewers"]) fs.mkdirSync(path.join(root, dir), { recursive: true });
  for (const [name, dir] of Object.entries(FONT_FILES)) fs.copyFileSync(path.join(FONT_DIR, dir, name), path.join(root, "fonts", name));
  for (const [name, rel] of Object.entries(SAMPLES)) fs.copyFileSync(path.join(GALLERY, rel), path.join(root, "samples", name));
  if (root !== HERE) for (const [, out] of VIEWERS) fs.copyFileSync(path.join(VIEWER_DIR, out), path.join(root, "viewers", out));
}
copyAssets(HERE);

// --- EVG's browser helpers --------------------------------------------------------
const ENTRY_IMPORTS = ["evg/gl/evg-webgl.js", "evg/gl/evg-a11y.js", "evg/gl/evg-measure.js", "evg/gl/evg-textinput.js"];

function relativeImports(text) {
  const out = [];
  for (const m of text.matchAll(/(?:^|\s)(?:import|export)[^;]*?from\s*["'](\.[^"']+)["']/g)) out.push(m[1]);
  for (const m of text.matchAll(/import\s*\(\s*["'](\.[^"']+)["']\s*\)/g)) out.push(m[1]);
  return out;
}

function helperClosure() {
  const seen = new Set();
  const queue = [...ENTRY_IMPORTS];
  while (queue.length) {
    const rel = queue.shift();
    if (seen.has(rel)) continue;
    const from = helperPath(rel);
    if (!fs.existsSync(from)) {
      console.error(`the page imports ${rel}, which is not in gallery/ or lib/`);
      process.exit(4);
    }
    seen.add(rel);
    for (const next of relativeImports(fs.readFileSync(from, "utf8"))) {
      queue.push(path.posix.normalize(path.posix.join(path.posix.dirname(rel), next)));
    }
  }
  return [...seen];
}

const HELPERS = helperClosure();
function copyHelpers(root) {
  for (const rel of HELPERS) {
    const to = path.join(root, rel);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(helperPath(rel), to);
  }
}
copyHelpers(HERE);

function assertResolvable(root) {
  for (const name of ["main.js", "preview.js", "code-editor.js", "generated-host.js", "generated.js"]) {
    const file = path.join(root, name);
    for (const rel of relativeImports(fs.readFileSync(file, "utf8"))) {
      if (!fs.existsSync(path.join(path.dirname(file), rel))) {
        console.error(`${name} imports ${rel}, which is not beside it in ${path.relative(process.cwd(), root)}`);
        process.exit(4);
      }
    }
  }
}
assertResolvable(HERE);

if (OUT) {
  fs.mkdirSync(OUT, { recursive: true });
  for (const name of ["index.html", "main.js", "preview.js", "code-editor.js", "generated-host.js", "generated.js"]) {
    fs.copyFileSync(path.join(HERE, name), path.join(OUT, name));
  }
  copyHelpers(OUT);
  copyAssets(OUT);
  assertResolvable(OUT);
  process.stdout.write(`  ${path.relative(process.cwd(), OUT)}  index.html + ${HELPERS.length + 3} modules\n`);
} else {
  const kb = (wrapped.length / 1024).toFixed(0);
  process.stdout.write(`  gallery/mfiles/web  generated-host.js ${kb} kB, ${extensions.length} sample extensions, EVG helpers copied\n`);
}
