// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Bundle the demo page.
//
//   node gallery/realtrainer/web/build.mjs
//
// The stylesheet is generated into a module rather than fetched, so the page
// and the headless check style the tree from exactly the same text and cannot
// drift. esbuild comes from the conformance reference host, so there is one
// install for gallery/ui's playground, its gates and this.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { assertDomInstalled, MissingDomDeps } from "../../ui/conformance/dom-adapter.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DOM_DIR = path.join(HERE, "..", "..", "ui", "conformance", "dom");
const domRequire = createRequire(path.join(DOM_DIR, "package.json"));

if (!fs.existsSync(path.join(HERE, "..", "bin", "RealTrainerDemo.cjs"))) {
  console.error("compiled app missing — run `npm run rt:build` first");
  process.exit(3);
}

let esbuild;
try {
  assertDomInstalled();
  esbuild = domRequire("esbuild");
} catch (e) {
  console.error(e instanceof MissingDomDeps ? e.message : String(e));
  process.exit(3);
}

// A one-line re-export, so the page imports a path that is the same in the
// bundle and in the editor rather than reaching into ../bin.
fs.writeFileSync(
  path.join(HERE, "generated-host.js"),
  "// Generated by web/build.mjs — do not edit.\n" +
    'export { RealTrainerDemo } from "../bin/RealTrainerDemo.cjs";\n',
);
fs.writeFileSync(
  path.join(HERE, "generated.js"),
  "// Generated by web/build.mjs — do not edit.\n" +
    "export const REALTRAINER_CSS = " +
    JSON.stringify(fs.readFileSync(path.join(HERE, "realtrainer.css"), "utf8")) +
    ";\n",
);

// A browser has no filesystem, and the only thing in this bundle that asks for
// one is the text engine's search for font FILES. The honest answer there is
// NO — there is no file — and the renderer falls back to the same estimating
// measurer the Node check uses, which is what keeps the two pictures the same.
const noFilesystem = {
  name: "no-filesystem",
  setup(build) {
    build.onResolve({ filter: /^fs$/ }, () => ({ path: "fs", namespace: "stub-fs" }));
    build.onLoad({ filter: /.*/, namespace: "stub-fs" }, () => ({
      contents:
        "export const existsSync = () => false;\n" +
        "export const readFileSync = () => { throw new Error('no filesystem in the browser'); };\n" +
        "export const readdirSync = () => [];\n" +
        "export default { existsSync, readFileSync, readdirSync };\n",
      loader: "js",
    }));
  },
};

await esbuild.build({
  entryPoints: [path.join(HERE, "main.js")],
  bundle: true,
  format: "esm",
  outfile: path.join(HERE, "bundle.js"),
  plugins: [noFilesystem],
  logLevel: "info",
});
