// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Bundle the demo page.
//
//   node gallery/realtrainer/web/build.mjs
//
// The stylesheet is generated into a module rather than fetched, so the page
// and the headless check style the tree from exactly the same text and cannot
// drift. esbuild comes from the conformance reference host, so there is one
// install for gallery/ui's playground, its gates and this.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { spawnSync } from "node:child_process";
import { assertDomInstalled, MissingDomDeps } from "../../ui/conformance/dom-adapter.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
// `--out DIR` writes the page for the site: index.html and the bundle beside
// it, and nothing else — the page loads one script. Without it the bundle
// lands here, where `rt:web` serves it.
const argv = process.argv.slice(2);
const outFlag = argv.indexOf("--out");
const OUT = outFlag >= 0 ? path.resolve(argv[outFlag + 1]) : null;
const DOM_DIR = path.join(HERE, "..", "..", "ui", "conformance", "dom");
const domRequire = createRequire(path.join(DOM_DIR, "package.json"));

if (!fs.existsSync(path.join(HERE, "..", "bin", "RealTrainerDemo.cjs"))) {
  console.error("compiled app missing — run `npm run rt:build` first");
  process.exit(3);
}

// THE FIRST PICTURE MUST BE CURRENT. `index.html` carries a picture of the
// app's chrome computed by `snapshot.mjs`, and a page that paints a stale one
// replaces a flash with a subtler flash. So the build refuses rather than
// shipping a picture of an app that no longer looks like that.
const stale = spawnSync(process.execPath, [path.join(HERE, "snapshot.mjs"), "--check"], {
  stdio: ["ignore", "pipe", "pipe"],
});
if (stale.status !== 0) {
  process.stderr.write(stale.stderr.toString() || "");
  console.error("the baked first picture is stale — run `npm run rt:shot:sync`");
  process.exit(3);
}

let esbuild;
try {
  assertDomInstalled();
  esbuild = domRequire("esbuild");
} catch (e) {
  console.error(e instanceof MissingDomDeps ? e.message : String(e));
  process.exit(3);
}

// A one-line re-export, so the page imports a path that is the same in the
// bundle and in the editor rather than reaching into ../bin.
fs.writeFileSync(
  path.join(HERE, "generated-host.js"),
  "// Generated by web/build.mjs — do not edit.\n" +
    'export { RealTrainerDemo } from "../bin/RealTrainerDemo.cjs";\n' +
    // The whole module too: the browser's text measurer is installed into
    // it (`gallery/evg/gl/evg-measure.js`).
    'export * as RealTrainerModule from "../bin/RealTrainerDemo.cjs";\n',
);
// The stylesheet AND the session's COMPACT source. Neither is fetched: the
// page and the headless check have to style and parse exactly the same text,
// and a browser has no filesystem to read the fixture from anyway.
fs.writeFileSync(
  path.join(HERE, "generated.js"),
  "// Generated by web/build.mjs — do not edit.\n" +
    "export const REALTRAINER_CSS = " +
    JSON.stringify(fs.readFileSync(path.join(HERE, "realtrainer.css"), "utf8")) +
    ";\n" +
    "export const REALTRAINER_COMPACT = " +
    JSON.stringify(
      fs.readFileSync(path.join(HERE, "..", "fixtures", "session.compact"), "utf8"),
    ) +
    ";\n" +
    // …and the plan-week machine, from the same file XState is measured on.
    "export const REALTRAINER_PLAN_MACHINE = " +
    JSON.stringify(
      fs.readFileSync(path.join(HERE, "..", "fixtures", "machines", "planDialog.machine.json"), "utf8"),
    ) +
    ";\n" +
    "export const REALTRAINER_CHAT_MACHINE = " +
    JSON.stringify(
      fs.readFileSync(path.join(HERE, "..", "fixtures", "machines", "chat.machine.json"), "utf8"),
    ) +
    ";\n" +
    "export const REALTRAINER_SEED = " +
    JSON.stringify(
      fs.readFileSync(path.join(HERE, "..", "fixtures", "reference", "seed.json"), "utf8"),
    ) +
    ";\n",
);

// A browser has no filesystem, and the only thing in this bundle that asks for
// one is the text engine's search for font FILES. The honest answer there is
// NO — there is no file — and the renderer falls back to the same estimating
// measurer the Node check uses, which is what keeps the two pictures the same.
const noFilesystem = {
  name: "no-filesystem",
  setup(build) {
    build.onResolve({ filter: /^fs$/ }, () => ({ path: "fs", namespace: "stub-fs" }));
    build.onLoad({ filter: /.*/, namespace: "stub-fs" }, () => ({
      contents:
        "export const existsSync = () => false;\n" +
        "export const readFileSync = () => { throw new Error('no filesystem in the browser'); };\n" +
        "export const readdirSync = () => [];\n" +
        "export default { existsSync, readFileSync, readdirSync };\n",
      loader: "js",
    }));
  },
};

// MINIFIED. The generated app is machine-written and reads like it — long
// identifiers, one statement per line, every temporary named — and none of
// that survives to the browser usefully. What the page ships is the behaviour,
// and the source it is compiled from is a `.rgr` file in the repository, not
// this bundle. Property names are left alone by esbuild, which is what the
// Ranger objects and every check that reaches into them depend on.
const MINIFY = process.env.RT_NO_MINIFY !== "1";

await esbuild.build({
  entryPoints: [path.join(HERE, "main.js")],
  bundle: true,
  format: "esm",
  minify: MINIFY,
  outfile: path.join(HERE, "bundle.js"),
  plugins: [noFilesystem],
  logLevel: "info",
});
// The same page with the engine in a Worker (`?engine=worker`): the host that
// paints, and the worker that holds the app. Two bundles, because a Worker is
// its own script; the generated module is in the worker's and not the host's.
await esbuild.build({
  entryPoints: [path.join(HERE, "main-worker.js")],
  bundle: true,
  format: "esm",
  minify: MINIFY,
  outfile: path.join(HERE, "bundle-worker.js"),
  plugins: [noFilesystem],
  logLevel: "info",
});
await esbuild.build({
  entryPoints: [path.join(HERE, "engine-worker.js")],
  bundle: true,
  format: "esm",
  minify: MINIFY,
  outfile: path.join(HERE, "worker-bundle.js"),
  plugins: [noFilesystem],
  logLevel: "info",
});

if (OUT) {
  fs.mkdirSync(OUT, { recursive: true });
  fs.copyFileSync(path.join(HERE, "bundle.js"), path.join(OUT, "bundle.js"));
  fs.copyFileSync(path.join(HERE, "bundle-worker.js"), path.join(OUT, "bundle-worker.js"));
  fs.copyFileSync(path.join(HERE, "worker-bundle.js"), path.join(OUT, "worker-bundle.js"));
  fs.copyFileSync(path.join(HERE, "index.html"), path.join(OUT, "index.html"));
  console.log(`  wrote ${path.relative(process.cwd(), OUT)}/index.html and bundle.js`);
}
