/**
 * LLVM / WAT backend tests — excluded from default `npm test` (see tests/vitest.config.ts).
 * Run explicitly: npm run test:llvm
 */
import { describe, it, expect, beforeAll } from "vitest";
import { execSync } from "child_process";
import * as path from "path";
import * as fs from "fs";
import { fileURLToPath } from "url";
import { compileRangerWithFlags } from "./helpers/compiler";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, "..");
const FIXTURES = "tests/fixtures";
const OUTPUT_DIR = path.join(__dirname, ".output-llvm");
const GOLDEN_DIR = path.join(__dirname, "golden", "llvm");

function normalizeLl(text: string): string {
  return text
    .replace(/\r\n/g, "\n")
    .replace(/; Generated.*\n/, "; Generated by Ranger LLVM backend\n")
    .trim();
}

function compileToLl(fixture: string, extraFlags: string[] = []): string {
  const base = path.basename(fixture, ".rgr");
  const outFile = `${base}.ll`;
  const outPath = path.join(OUTPUT_DIR, outFile);

  const result = compileRangerWithFlags(fixture, "llvm", OUTPUT_DIR, extraFlags);
  expect(result.success, result.error || result.output).toBe(true);
  expect(fs.existsSync(outPath), `Expected ${outPath}`).toBe(true);
  return fs.readFileSync(outPath, "utf-8");
}

function isLlvmAvailable(): boolean {
  try {
    execSync("which clang", { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

function nativeTarget(): string {
  return process.platform === "darwin"
    ? process.arch === "arm64"
      ? "arm64-apple-macos"
      : "x86_64-apple-macos"
    : "native-linux-gnu";
}

const RANGER_MEM_C = path.join(ROOT, "runtime", "ranger_mem.c");

function compileNativeWithMem(
  fixture: string,
  binName: string,
  outDir: string
): string {
  fs.mkdirSync(outDir, { recursive: true });
  const base = path.basename(fixture, ".rgr");
  const result = compileRangerWithFlags(fixture, "llvm", outDir, [
    `-target=${nativeTarget()}`,
  ]);
  expect(result.success, result.error || result.output).toBe(true);
  const llPath = path.join(outDir, `${base}.ll`);
  const binPath = path.join(outDir, binName);
  execSync(`clang "${llPath}" "${RANGER_MEM_C}" -o "${binPath}"`, {
    stdio: "pipe",
  });
  return binPath;
}

describe("Ranger Compiler - LLVM / Low IR backend", () => {
  beforeAll(() => {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    fs.mkdirSync(GOLDEN_DIR, { recursive: true });
  });

  it("compiles add example to LLVM IR", () => {
    const ll = normalizeLl(compileToLl(`${FIXTURES}/llvm_add.rgr`));
    expect(ll).toContain("define dso_local i32 @AddLib_add");
    expect(ll).toContain("ret i32");
  });

  it("compiles fibonacci example to LLVM IR with branches", () => {
    const ll = normalizeLl(compileToLl(`${FIXTURES}/llvm_fibonacci.rgr`));
    expect(ll).toContain("@Fib_fib");
    expect(ll).toContain("icmp slt");
    expect(ll).toContain("call i32 @Fib_fib");
  });

  it("compiles factorial example with recursion", () => {
    const ll = normalizeLl(compileToLl(`${FIXTURES}/llvm_factorial.rgr`));
    expect(ll).toContain("@Fact_factorial");
    expect(ll).toContain("call i32 @Fact_factorial");
    expect(ll).toContain(" mul i32 ");
  });

  it("compiles @main entry point to LLVM IR", () => {
    const ll = normalizeLl(compileToLl(`${FIXTURES}/llvm_main.rgr`));
    expect(ll).toContain("define dso_local i32 @main(");
    expect(ll).toContain("@AddLib_add");
    expect(ll).toContain("call i32 @AddLib_add");
  });

  it("compiles while-loop factorial with mutable locals", () => {
    const ll = normalizeLl(compileToLl(`${FIXTURES}/llvm_factorial_while.rgr`));
    expect(ll).toContain("@Fact_factorial");
    expect(ll).toContain("while_cond");
    expect(ll).toContain("alloca i32");
    expect(ll).toContain("store i32");
    expect(ll).toContain("load i32");
  });

  it("compiles class with instance methods and mutable field", () => {
    const ll = normalizeLl(
      compileToLl(`${FIXTURES}/llvm_counter.rgr`, ["-freestanding"])
    );
    expect(ll).toContain("@Counter_Constructor");
    expect(ll).toContain("@Counter_increment");
    expect(ll).toContain("@Counter_get");
    expect(ll).toContain("getelementptr");
    expect(ll).toContain("@CounterDemo_run");
    expect(ll).toContain("call void @Counter_increment");
    expect(ll).toContain("call i32 @Counter_get");
  });

  it("compiles Lang array/map operators to LLVM IR with runtime helpers", () => {
    const ll = normalizeLl(
      compileToLl(`${FIXTURES}/llvm_array_map_lang.rgr`, ["-freestanding"])
    );
    expect(ll).toContain("@LangCollectionsDemo_run");
    expect(ll).toContain("@RtMap_new");
    expect(ll).toContain("@RtArray_set");
    expect(ll).toContain("@heap_ptr");
  });

  it("compiles IntList and IntMap with heap intrinsics", () => {
    const ll = normalizeLl(
      compileToLl(`${FIXTURES}/llvm_collections.rgr`, ["-freestanding"])
    );
    expect(ll).toContain("@heap_ptr");
    expect(ll).toContain("@IntList_Constructor");
    expect(ll).toContain("@IntList_get");
    expect(ll).toContain("@IntMap_put");
    expect(ll).toContain("@IntMap_get");
    expect(ll).toContain("@CollectionsDemo_run");
    expect(ll).toContain("inttoptr");
  });

  it("compiles dynamic array/map demo with push growth and itemAt", () => {
    const ll = normalizeLl(
      compileToLl(`${FIXTURES}/llvm_dyn_collections.rgr`, ["-freestanding"])
    );
    expect(ll).toContain("@main");
    expect(ll).toContain("@RtPtrArray_push");
    expect(ll).toContain("@RtPtrArray_get");
    expect(ll).toContain("@RtPtrArray_len");
    expect(ll).toContain("@RtArray_set");
    expect(ll).toContain("@RtMap_put");
    expect(ll).toContain("@RtMap_get");
    expect(ll).toContain("realloc");
  });

  it("native dynamic collections binary returns 50 after push loop", () => {
    if (!isLlvmAvailable()) {
      return;
    }
    const outDir = path.join(__dirname, ".output-dyn-collections");
    fs.mkdirSync(outDir, { recursive: true });
    const target =
      process.platform === "darwin"
        ? process.arch === "arm64"
          ? "arm64-apple-macos"
          : "x86_64-apple-macos"
        : "native-linux-gnu";
    const result = compileRangerWithFlags(
      `${FIXTURES}/llvm_dyn_collections.rgr`,
      "llvm",
      outDir,
      [`-target=${target}`]
    );
    expect(result.success, result.error || result.output).toBe(true);
    const llPath = path.join(outDir, "llvm_dyn_collections.ll");
    const binPath = path.join(outDir, "dyn_collections");
    execSync(`clang "${llPath}" "${RANGER_MEM_C}" -o "${binPath}"`, {
      stdio: "pipe",
    });
    const exitCode = execSync(`"${binPath}"; echo $?`, {
      shell: "/bin/bash",
      encoding: "utf-8",
    }).trim();
    expect(exitCode).toBe("50");
  });

  it("does not double zext boolean literals stored to class fields", () => {
    // Regression: `field = true` (bare field name) used to emit an invalid
    // `zext i1 <already-i32> to i32`. The IR must widen the i1 exactly once.
    const ll = compileToLl(`${FIXTURES}/llvm_bool_field.rgr`);
    // A zext-of-a-zext temp (%z<n> feeding another zext i1) is the bug.
    expect(ll).not.toMatch(/zext i1 %z\d+ to i32/);
  });

  it("native boolean field binary returns 42", () => {
    if (!isLlvmAvailable()) {
      return;
    }
    const outDir = path.join(__dirname, ".output-bool-field");
    fs.mkdirSync(outDir, { recursive: true });
    const target =
      process.platform === "darwin"
        ? process.arch === "arm64"
          ? "arm64-apple-macos"
          : "x86_64-apple-macos"
        : "native-linux-gnu";
    const result = compileRangerWithFlags(
      `${FIXTURES}/llvm_bool_field.rgr`,
      "llvm",
      outDir,
      [`-target=${target}`]
    );
    expect(result.success, result.error || result.output).toBe(true);
    const llPath = path.join(outDir, "llvm_bool_field.ll");
    const binPath = path.join(outDir, "bool_field");
    execSync(`clang "${llPath}" -o "${binPath}" -Wno-override-module`, {
      stdio: "pipe",
    });
    const exitCode = execSync(`"${binPath}"; echo $?`, {
      shell: "/bin/bash",
      encoding: "utf-8",
    }).trim();
    expect(exitCode).toBe("42");
  });

  it("matches golden LLVM IR for add", () => {
    const ll = normalizeLl(compileToLl(`${FIXTURES}/llvm_add.rgr`));
    const goldenPath = path.join(GOLDEN_DIR, "add.ll");
    if (!fs.existsSync(goldenPath)) {
      fs.writeFileSync(goldenPath, ll + "\n");
    }
    const golden = normalizeLl(fs.readFileSync(goldenPath, "utf-8"));
    expect(ll).toBe(golden);
  });

  it("matches golden LLVM IR for fibonacci", () => {
    const ll = normalizeLl(compileToLl(`${FIXTURES}/llvm_fibonacci.rgr`));
    const goldenPath = path.join(GOLDEN_DIR, "fibonacci.ll");
    if (!fs.existsSync(goldenPath)) {
      fs.writeFileSync(goldenPath, ll + "\n");
    }
    const golden = normalizeLl(fs.readFileSync(goldenPath, "utf-8"));
    expect(ll).toBe(golden);
  });

  it("matches golden LLVM IR for factorial", () => {
    const ll = normalizeLl(compileToLl(`${FIXTURES}/llvm_factorial.rgr`));
    const goldenPath = path.join(GOLDEN_DIR, "factorial.ll");
    if (!fs.existsSync(goldenPath)) {
      fs.writeFileSync(goldenPath, ll + "\n");
    }
    const golden = normalizeLl(fs.readFileSync(goldenPath, "utf-8"));
    expect(ll).toBe(golden);
  });

  it("compiles hello world with libc printf for native target", () => {
    const target =
      process.platform === "darwin"
        ? process.arch === "arm64"
          ? "arm64-apple-macos"
          : "x86_64-apple-macos"
        : "native-linux-gnu";
    const ll = normalizeLl(
      compileToLl(`${FIXTURES}/llvm_hello.rgr`, [`-target=${target}`])
    );
    if (process.platform === "darwin") {
      if (process.arch === "arm64") {
        expect(ll).toContain('target triple = "arm64-apple-macosx"');
      } else {
        expect(ll).toContain('target triple = "x86_64-apple-macosx"');
      }
    } else {
      expect(ll).toContain('target triple = "x86_64-unknown-linux-gnu"');
    }
    expect(ll).toContain("@.str.0");
    expect(ll).toContain("declare i32 @printf(i8*, ...)");
    expect(ll).toContain("call i32 (i8*, ...) @printf");
    expect(ll).toContain("define dso_local i32 @main(");
  });

  it("compiles libc operators (write, strlen) for native target", () => {
    const target =
      process.platform === "darwin"
        ? process.arch === "arm64"
          ? "arm64-apple-macos"
          : "x86_64-apple-macos"
        : "native-linux-gnu";
    const ll = normalizeLl(
      compileToLl(`${FIXTURES}/llvm_libc_ops.rgr`, [`-target=${target}`])
    );
    expect(ll).toContain("declare i32 @printf(i8*, ...)");
    expect(ll).toContain("@.str.0");
    expect(ll).toContain("\\00\"");
    expect(ll).toContain("@.str.1");
    expect(ll).toContain("\\0A\\00\"");
    expect(ll).toContain("add i32 0, 5");
    expect(ll).toContain("define dso_local i32 @main(");
  });

  it("native libc_ops binary writes Hi and returns 5", () => {
    if (!isLlvmAvailable()) {
      return;
    }
    const outDir = path.join(__dirname, ".output-libc-ops");
    fs.mkdirSync(outDir, { recursive: true });
    const target =
      process.platform === "darwin"
        ? process.arch === "arm64"
          ? "arm64-apple-macos"
          : "x86_64-apple-macos"
        : "native-linux-gnu";
    const result = compileRangerWithFlags(
      `${FIXTURES}/llvm_libc_ops.rgr`,
      "llvm",
      outDir,
      [`-target=${target}`]
    );
    expect(result.success, result.error || result.output).toBe(true);
    const llPath = path.join(outDir, "llvm_libc_ops.ll");
    const binPath = path.join(outDir, "libc_ops");
    execSync(`clang "${llPath}" -o "${binPath}"`, { stdio: "pipe" });
    const stdout = execSync(`"${binPath}"; echo $?`, {
      shell: "/bin/bash",
      encoding: "utf-8",
    });
    const lines = stdout.trim().split("\n");
    expect(lines[0]).toBe("Hi!");
    expect(lines[lines.length - 1]).toBe("5");
  });

  it("native hello binary prints Hello, world!", () => {
    if (!isLlvmAvailable()) {
      return;
    }
    const outDir = path.join(__dirname, ".output-hello-native");
    fs.mkdirSync(outDir, { recursive: true });
    const target =
      process.platform === "darwin"
        ? process.arch === "arm64"
          ? "arm64-apple-macos"
          : "x86_64-apple-macos"
        : "native-linux-gnu";
    const result = compileRangerWithFlags(
      `${FIXTURES}/llvm_hello.rgr`,
      "llvm",
      outDir,
      [`-target=${target}`]
    );
    expect(result.success, result.error || result.output).toBe(true);
    const llPath = path.join(outDir, "llvm_hello.ll");
    const binPath = path.join(outDir, "hello");
    execSync(`clang "${llPath}" -o "${binPath}"`, { stdio: "pipe" });
    const stdout = execSync(`"${binPath}"`, { encoding: "utf-8" });
    expect(stdout.trim()).toBe("Hello, world!");
  });

  it("native binary from @main fixture exits 42", () => {
    if (!isLlvmAvailable()) {
      return;
    }
    const outDir = path.join(__dirname, ".output-llvm-native");
    fs.mkdirSync(outDir, { recursive: true });
    const llPath = path.join(outDir, "llvm_main.ll");
    const binPath = path.join(outDir, "main_demo");
    const result = compileRangerWithFlags(
      `${FIXTURES}/llvm_main.rgr`,
      "llvm",
      outDir
    );
    expect(result.success, result.error || result.output).toBe(true);
    expect(fs.existsSync(llPath)).toBe(true);
    execSync(`clang "${llPath}" -o "${binPath}"`, { stdio: "pipe" });
    const exitCode = execSync(`"${binPath}"; echo $?`, {
      shell: "/bin/bash",
      encoding: "utf-8",
    }).trim();
    expect(exitCode).toBe("42");
  });

  it("emits ranger_obj_new and ranger_obj_release for trivial object", () => {
    const ll = normalizeLl(
      compileToLl(`${FIXTURES}/llvm_mem_trivial.rgr`, [
        `-target=${nativeTarget()}`,
      ])
    );
    expect(ll).toContain("declare i64 @ranger_obj_new");
    expect(ll).toContain("@ranger_obj_release");
    expect(ll).toContain("call void @ranger_obj_release");
    expect(ll).toContain("call i64 (i32, ptr) @ranger_obj_new");
  });

  it("native trivial object alloc reports zero live objects", () => {
    if (!isLlvmAvailable()) {
      return;
    }
    const outDir = path.join(__dirname, ".output-mem-trivial");
    const binPath = compileNativeWithMem(
      `${FIXTURES}/llvm_mem_trivial.rgr`,
      "mem_trivial",
      outDir
    );
    const exitCode = execSync(`"${binPath}"; echo $?`, {
      shell: "/bin/bash",
      encoding: "utf-8",
    }).trim();
    expect(exitCode).toBe("0");
  });

  it("native loop of 1000 object allocs reports zero live objects", () => {
    if (!isLlvmAvailable()) {
      return;
    }
    const outDir = path.join(__dirname, ".output-mem-loop");
    const binPath = compileNativeWithMem(
      `${FIXTURES}/llvm_mem_loop.rgr`,
      "mem_loop",
      outDir
    );
    const exitCode = execSync(`"${binPath}"; echo $?`, {
      shell: "/bin/bash",
      encoding: "utf-8",
    }).trim();
    expect(exitCode).toBe("0");
  });

  it("emits type descriptor for string field class", () => {
    const ll = normalizeLl(
      compileToLl(`${FIXTURES}/llvm_mem_string.rgr`, [
        `-target=${nativeTarget()}`,
      ])
    );
    expect(ll).toContain("@NamedBox_typeDesc");
    expect(ll).toContain("@NamedBox_typeFields");
    expect(ll).toContain("%struct.RangerTypeDesc");
  });

  it("native field assign releases old strings", () => {
    if (!isLlvmAvailable()) {
      return;
    }
    const outDir = path.join(__dirname, ".output-mem-field-assign");
    const binPath = compileNativeWithMem(
      `${FIXTURES}/llvm_mem_field_assign.rgr`,
      "mem_field_assign",
      outDir
    );
    const exitCode = execSync(`"${binPath}"; echo $?`, {
      shell: "/bin/bash",
      encoding: "utf-8",
    }).trim();
    expect(exitCode).toBe("0");
  });

  it("native ptr-array push releases all elements", () => {
    if (!isLlvmAvailable()) {
      return;
    }
    const outDir = path.join(__dirname, ".output-mem-ptrarray");
    const binPath = compileNativeWithMem(
      `${FIXTURES}/llvm_mem_ptrarray.rgr`,
      "mem_ptrarray",
      outDir
    );
    const exitCode = execSync(`"${binPath}"; echo $?`, {
      shell: "/bin/bash",
      encoding: "utf-8",
    }).trim();
    expect(exitCode).toBe("0");
  });

  it("native string-field object alloc reports zero live objects", () => {
    if (!isLlvmAvailable()) {
      return;
    }
    const outDir = path.join(__dirname, ".output-mem-string");
    const binPath = compileNativeWithMem(
      `${FIXTURES}/llvm_mem_string.rgr`,
      "mem_string",
      outDir
    );
    const exitCode = execSync(`"${binPath}"; echo $?`, {
      shell: "/bin/bash",
      encoding: "utf-8",
    }).trim();
    expect(exitCode).toBe("0");
  });

  it("emits ownership summary on manual target with -strict-ownership", () => {
    const outDir = path.join(OUTPUT_DIR, "strict-own");
    const result = compileRangerWithFlags(
      `${FIXTURES}/llvm_mem_ptrarray.rgr`,
      "llvm",
      outDir,
      [`-target=${nativeTarget()}`, "-strict-ownership"]
    );
    expect(result.success, result.error || result.output).toBe(true);
    const ll = fs.readFileSync(
      path.join(outDir, "llvm_mem_ptrarray.ll"),
      "utf-8"
    );
    expect(ll).toContain("; ownership[manual]: scope-exit disposition");
    expect(ll).toContain("owned object 'b' -> escaped");
    expect(ll).toContain("owned array 'items' -> released");
  });

  it("omits ownership summary without -strict-ownership", () => {
    const outDir = path.join(OUTPUT_DIR, "no-strict-own");
    const result = compileRangerWithFlags(
      `${FIXTURES}/llvm_mem_ptrarray.rgr`,
      "llvm",
      outDir,
      [`-target=${nativeTarget()}`]
    );
    expect(result.success, result.error || result.output).toBe(true);
    const ll = fs.readFileSync(
      path.join(outDir, "llvm_mem_ptrarray.ll"),
      "utf-8"
    );
    expect(ll).not.toContain("ownership[manual]");
  });

  it("native parser-sim workload stays flat at scale (1000 objects)", () => {
    if (!isLlvmAvailable()) {
      return;
    }
    const outDir = path.join(__dirname, ".output-mem-parser-sim");
    const binPath = compileNativeWithMem(
      `${FIXTURES}/llvm_mem_parser_sim.rgr`,
      "mem_parser_sim",
      outDir
    );
    const exitCode = execSync(`"${binPath}"; echo $?`, {
      shell: "/bin/bash",
      encoding: "utf-8",
    }).trim();
    expect(exitCode).toBe("0");
  });
});

describe("Ranger Compiler - WAT backend", () => {
  beforeAll(() => {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  });

  it("emits valid WASM for math demo exports", () => {
    const outDir = path.join(__dirname, ".output-wasm");
    fs.mkdirSync(outDir, { recursive: true });
    const result = compileRangerWithFlags(
      `${FIXTURES}/llvm_wasm_demo.rgr`,
      "llvm",
      outDir,
      ["-wat", "-freestanding"]
    );
    expect(result.success, result.error || result.output).toBe(true);
    const watPath = path.join(outDir, "llvm_wasm_demo.ll");
    const wat = fs.readFileSync(watPath, "utf-8");
    expect(wat).toContain('(export "MathLib_add")');
    expect(wat).toContain('(export "MathLib_hypot")');
    expect(wat).toContain('(export "Fib_fib")');
    expect(wat).toContain('(export "Fact_factorial")');
    expect(wat).toContain("if");
    expect(wat).toContain("(loop ");
    expect(wat).toContain("call $MathLib_mul");

    const wat2wasm = path.join(ROOT, "node_modules", ".bin", "wat2wasm");
    if (!fs.existsSync(wat2wasm)) {
      return;
    }
    const wasmPath = path.join(outDir, "demo.wasm");
    execSync(`"${wat2wasm}" "${watPath}" -o "${wasmPath}"`, { stdio: "pipe" });
    const buf = fs.readFileSync(wasmPath);
    const mod = new WebAssembly.Module(buf);
    const inst = new WebAssembly.Instance(mod);
    const e = inst.exports as Record<string, (...args: number[]) => number>;
    expect(e.MathLib_add(40, 2)).toBe(42);
    expect(e.Fib_fib(10)).toBe(55);
    expect(e.Fact_factorial(5)).toBe(120);
    expect(e.Fact_factorial(6)).toBe(720);
  });

  it("emits valid WASM for mathlib (fib, factorial)", () => {
    const outDir = path.join(__dirname, ".output-wasm");
    fs.mkdirSync(outDir, { recursive: true });
    const result = compileRangerWithFlags(
      `${FIXTURES}/llvm_mathlib.rgr`,
      "llvm",
      outDir,
      ["-wat", "-freestanding"]
    );
    expect(result.success, result.error || result.output).toBe(true);
    const watPath = path.join(outDir, "llvm_mathlib.ll");
    const wat = fs.readFileSync(watPath, "utf-8");
    expect(wat).toContain('(export "Fib_fib")');
    expect(wat).toContain("if");

    const wat2wasm = path.join(ROOT, "node_modules", ".bin", "wat2wasm");
    if (!fs.existsSync(wat2wasm)) {
      return;
    }
    const wasmPath = path.join(outDir, "mathlib.wasm");
    execSync(`"${wat2wasm}" "${watPath}" -o "${wasmPath}"`, { stdio: "pipe" });
    const buf = fs.readFileSync(wasmPath);
    const mod = new WebAssembly.Module(buf);
    const inst = new WebAssembly.Instance(mod);
    const e = inst.exports as Record<string, (n: number) => number>;
    expect(e.Fib_fib(10)).toBe(55);
    expect(e.Fact_factorial(5)).toBe(120);
  });

  it("emits valid WASM for while-loop factorial", () => {
    const outDir = path.join(__dirname, ".output-wasm");
    const result = compileRangerWithFlags(
      `${FIXTURES}/llvm_factorial_while.rgr`,
      "llvm",
      outDir,
      ["-wat", "-freestanding"]
    );
    expect(result.success, result.error || result.output).toBe(true);
    const watPath = path.join(outDir, "llvm_factorial_while.ll");
    const wat = fs.readFileSync(watPath, "utf-8");
    expect(wat).toContain("(loop ");

    const wat2wasm = path.join(ROOT, "node_modules", ".bin", "wat2wasm");
    if (!fs.existsSync(wat2wasm)) {
      return;
    }
    const wasmPath = path.join(outDir, "factorial_while.wasm");
    execSync(`"${wat2wasm}" "${watPath}" -o "${wasmPath}"`, { stdio: "pipe" });
    const inst = new WebAssembly.Instance(new WebAssembly.Module(fs.readFileSync(wasmPath)));
    const fact = (inst.exports as Record<string, (n: number) => number>).Fact_factorial;
    expect(fact(5)).toBe(120);
    expect(fact(6)).toBe(720);
  });

  it("emits valid WASM for class instance methods updating a field", () => {
    const outDir = path.join(__dirname, ".output-wasm");
    const result = compileRangerWithFlags(
      `${FIXTURES}/llvm_counter.rgr`,
      "llvm",
      outDir,
      ["-wat", "-freestanding"]
    );
    expect(result.success, result.error || result.output).toBe(true);
    const watPath = path.join(outDir, "llvm_counter.ll");
    const wat = fs.readFileSync(watPath, "utf-8");
    expect(wat).toContain('(export "CounterDemo_run")');
    expect(wat).toContain("$Counter_increment");
    expect(wat).toContain("i32.store");

    const wat2wasm = path.join(ROOT, "node_modules", ".bin", "wat2wasm");
    if (!fs.existsSync(wat2wasm)) {
      return;
    }
    const wasmPath = path.join(outDir, "counter.wasm");
    execSync(`"${wat2wasm}" "${watPath}" -o "${wasmPath}"`, { stdio: "pipe" });
    const inst = new WebAssembly.Instance(new WebAssembly.Module(fs.readFileSync(wasmPath)));
    const run = (inst.exports as Record<string, () => number>).CounterDemo_run;
    expect(run()).toBe(11);
  });

  it("emits valid WASM for IntList and IntMap collections demo", () => {
    const outDir = path.join(__dirname, ".output-wasm");
    const result = compileRangerWithFlags(
      `${FIXTURES}/llvm_collections.rgr`,
      "llvm",
      outDir,
      ["-wat", "-freestanding"]
    );
    expect(result.success, result.error || result.output).toBe(true);
    const watPath = path.join(outDir, "llvm_collections.ll");
    const wat = fs.readFileSync(watPath, "utf-8");
    expect(wat).toContain('(export "CollectionsDemo_run")');
    expect(wat).toContain("$IntMap_get");
    expect(wat).toContain("i32.rem_s");

    const wat2wasm = path.join(ROOT, "node_modules", ".bin", "wat2wasm");
    if (!fs.existsSync(wat2wasm)) {
      return;
    }
    const wasmPath = path.join(outDir, "collections.wasm");
    execSync(`"${wat2wasm}" "${watPath}" -o "${wasmPath}"`, { stdio: "pipe" });
    const inst = new WebAssembly.Instance(new WebAssembly.Module(fs.readFileSync(wasmPath)));
    const run = (inst.exports as Record<string, () => number>).CollectionsDemo_run;
    expect(run()).toBe(410);
  });

  it("emits valid WASM for Lang array/map operators", () => {
    const outDir = path.join(__dirname, ".output-wasm");
    const result = compileRangerWithFlags(
      `${FIXTURES}/llvm_array_map_lang.rgr`,
      "llvm",
      outDir,
      ["-wat", "-freestanding"]
    );
    expect(result.success, result.error || result.output).toBe(true);
    const watPath = path.join(outDir, "llvm_array_map_lang.ll");
    const wat = fs.readFileSync(watPath, "utf-8");
    expect(wat).toContain('(export "LangCollectionsDemo_run")');
    expect(wat).toContain("$RtArray_set");
    expect(wat).toContain("$RtMap_put");

    const wat2wasm = path.join(ROOT, "node_modules", ".bin", "wat2wasm");
    if (!fs.existsSync(wat2wasm)) {
      return;
    }
    const wasmPath = path.join(outDir, "lang_ops.wasm");
    execSync(`"${wat2wasm}" "${watPath}" -o "${wasmPath}"`, { stdio: "pipe" });
    const inst = new WebAssembly.Instance(new WebAssembly.Module(fs.readFileSync(wasmPath)));
    const run = (inst.exports as Record<string, () => number>).LangCollectionsDemo_run;
    expect(run()).toBe(410);
  });

  it("emits valid WASM for IntList push and indexed get", () => {
    const outDir = path.join(__dirname, ".output-wasm");
    const result = compileRangerWithFlags(
      `${FIXTURES}/llvm_list_smoke.rgr`,
      "llvm",
      outDir,
      ["-wat", "-freestanding"]
    );
    expect(result.success, result.error || result.output).toBe(true);
    const watPath = path.join(outDir, "llvm_list_smoke.ll");
    const wat = fs.readFileSync(watPath, "utf-8");
    expect(wat).toContain('(export "ListSmoke_run")');
    expect(wat).toContain("$IntList_push");

    const wat2wasm = path.join(ROOT, "node_modules", ".bin", "wat2wasm");
    if (!fs.existsSync(wat2wasm)) {
      return;
    }
    const wasmPath = path.join(outDir, "list_smoke.wasm");
    execSync(`"${wat2wasm}" "${watPath}" -o "${wasmPath}"`, { stdio: "pipe" });
    const inst = new WebAssembly.Instance(new WebAssembly.Module(fs.readFileSync(wasmPath)));
    const run = (inst.exports as Record<string, () => number>).ListSmoke_run;
    expect(run()).toBe(10);
  });
});
