/**
 * The Ranger syntax app, compiled to every target.
 *
 * tests/syntax_app/ holds one Ranger program that uses as much of
 * compiler/Lang.rgr and of the language as can be written portably: 203 of the
 * 207 core operator names, classes, inheritance, traits, records, enums,
 * extensions, lambdas, optionals, buffers, custom operators and the collection
 * methods of lib/stdlib.rgr. tests/syntax_app/README.md explains the layout.
 *
 * This test does three things.
 *
 *   1. It holds the reference target to the letter. ES6 has to compile, run
 *      and print exactly tests/syntax_app/expected_output.txt. That assertion
 *      has no baseline to fall back on: a change there is a regression.
 *
 *   2. It measures every other target and compares the measurement with
 *      tests/syntax_app/target_matrix.json. The comparison is two directional,
 *      so a target that gets worse and a target that gets better both fail,
 *      and the message says which. Re-record with:
 *
 *        UPDATE_SYNTAX_APP_BASELINE=1 npx vitest run --config tests/vitest.config.ts syntax-app.test.ts
 *
 *   3. It pins the constructs of tests/syntax_app/gaps/, each of which is a
 *      short program that does not work today. If one starts to work, the test
 *      says so and asks for the record to be updated -- the point is that a
 *      fix is noticed rather than quietly lost.
 *
 * The matrix is written to tests/.output-syntax-app/report.md on every run.
 */
import { describe, it, expect, beforeAll } from "vitest";
import * as fs from "fs";
import * as path from "path";
import {
  APP_DIR,
  GAPS_DIR,
  OUT_DIR,
  ROOT_DIR,
  Status,
  TARGETS,
  UNITS,
  compile,
  normalise,
  firstDifference,
  renderMatrix,
  runGenerated,
  statusOf,
  toolAvailable,
} from "./helpers/syntax-app";

const BASELINE_FILE = path.join(APP_DIR, "target_matrix.json");
const REPORT_FILE = path.join(APP_DIR, "TARGET_REPORT.md");
const GAPS_FILE = path.join(APP_DIR, "gaps", "gaps.json");
const UPDATE = process.env.UPDATE_SYNTAX_APP_BASELINE === "1";

interface Measurement {
  status: Status;
  detail?: string;
  unmatched: string[];
}

type Matrix = Record<string, Record<string, Measurement>>;

let matrix: Matrix = {};

/**
 * The measurement shells out a few hundred times. Each compilation and each
 * run is synchronous, so the loop yields between targets: without it the
 * worker never answers the reporter and Vitest reports
 * `Timeout calling "onTaskUpdate"` next to a passing suite.
 */
const yieldToLoop = () => new Promise((resolve) => setImmediate(resolve));

beforeAll(async () => {
  fs.rmSync(OUT_DIR, { recursive: true, force: true });
  fs.mkdirSync(OUT_DIR, { recursive: true });

  for (const unit of UNITS) {
    matrix[unit.id] = {};
    for (const target of TARGETS) {
      const compiled = compile(unit, target);
      const { status, detail } = statusOf(unit, target, compiled);
      matrix[unit.id][target.id] = {
        status,
        detail,
        unmatched: compiled.unmatched,
      };
      await yieldToLoop();
    }
  }

  const plain: Record<string, Record<string, Status>> = {};
  for (const unit of Object.keys(matrix)) {
    plain[unit] = {};
    for (const target of TARGETS) {
      plain[unit][target.id] = matrix[unit][target.id].status;
    }
  }
  fs.writeFileSync(
    path.join(OUT_DIR, "report.md"),
    renderReport(matrix, plain),
    "utf8"
  );
}, 1800000);

function renderReport(
  full: Matrix,
  plain: Record<string, Record<string, Status>>
): string {
  const lines: string[] = [];
  lines.push("# Ranger syntax app: target report");
  lines.push("");
  lines.push(
    "Generated by `tests/syntax-app.test.ts`. `ok` = compiled, ran and printed"
  );
  lines.push(
    "the expected output; `c` = compiled (not run here); `diff` = ran and"
  );
  lines.push(
    "printed something else; `run` = the target toolchain or the program"
  );
  lines.push("failed; `-` = the Ranger compiler rejected it.");
  lines.push("");
  lines.push(renderMatrix(plain, TARGETS));
  lines.push("");
  lines.push("## Operators with no template for a target");
  lines.push("");
  lines.push(
    "One row per unit that a target rejected. The names are the operators the"
  );
  lines.push(
    "compiler could not match; a missing template is the usual reason, and the"
  );
  lines.push(
    "first one often drags unrelated names in with it, because an expression of"
  );
  lines.push("unknown type does not match anything either.");
  lines.push("");
  const rows2: string[] = [];
  for (const target of TARGETS) {
    for (const unit of Object.keys(full)) {
      const cell = full[unit][target.id];
      if (cell.unmatched.length) {
        rows2.push(`| ${target.id} | ${unit} | ${cell.unmatched.join(" ")} |`);
      }
    }
  }
  if (rows2.length === 0) {
    lines.push("None.");
  } else {
    lines.push("| target | unit | operators |");
    lines.push("| --- | --- | --- |");
    lines.push(...rows2);
  }
  lines.push("");
  lines.push("## What went wrong, per cell");
  lines.push("");
  lines.push(
    "Only the cells that are not `ok` and not a plain `compiled` appear here."
  );
  lines.push("");
  const notes: string[] = [];
  for (const unit of Object.keys(full)) {
    for (const target of TARGETS) {
      const cell = full[unit][target.id];
      if (cell.status === "ok" || !cell.detail) {
        continue;
      }
      const detail = cell.detail.replace(/\s+/g, " ").trim().slice(0, 400);
      notes.push(`- **${unit} / ${target.id}** (${cell.status}): ${detail}`);
    }
  }
  lines.push(notes.length ? notes.join("\n") : "Nothing to report.");
  lines.push("");
  lines.push("## Toolchains present on this machine");
  lines.push("");
  for (const target of TARGETS) {
    const tool = target.runner?.tool;
    const state = !tool
      ? "no runner defined"
      : toolAvailable(tool)
        ? `${tool} present`
        : `${tool} missing, compile only`;
    lines.push(`- ${target.id}: ${state}`);
  }
  lines.push("");
  return lines.join("\n");
}

describe("Ranger syntax app", () => {
  it("compiles, runs and prints the expected output on the ES6 reference target", () => {
    const cell = matrix["app"]["es6"];
    expect(
      cell.status,
      `ES6 is the reference target and has no allowance: ${cell.detail ?? ""}`
    ).toBe("ok");
  });

  it("compiles every section on the ES6 reference target", () => {
    const broken = Object.keys(matrix)
      .filter((unit) => matrix[unit]["es6"].status === "compile-error")
      .map((unit) => `${unit}: ${matrix[unit]["es6"].detail ?? ""}`);
    expect(broken.join("\n"), "sections rejected on ES6").toBe("");
  });

  it("matches the recorded target matrix", () => {
    const measured: Record<string, Record<string, Status>> = {};
    for (const unit of Object.keys(matrix)) {
      measured[unit] = {};
      for (const target of TARGETS) {
        measured[unit][target.id] = matrix[unit][target.id].status;
      }
    }

    if (UPDATE) {
      fs.writeFileSync(
        BASELINE_FILE,
        `${JSON.stringify(measured, null, 2)}\n`,
        "utf8"
      );
      fs.writeFileSync(
        REPORT_FILE,
        fs.readFileSync(path.join(OUT_DIR, "report.md"), "utf8"),
        "utf8"
      );
    }

    const baseline: Record<string, Record<string, Status>> = JSON.parse(
      fs.readFileSync(BASELINE_FILE, "utf8")
    );

    const rank: Record<Status, number> = {
      "compile-error": 0,
      "run-error": 1,
      "output-differs": 2,
      compiled: 3,
      ok: 4,
    };

    const regressions: string[] = [];
    const improvements: string[] = [];
    for (const unit of Object.keys(measured)) {
      for (const target of TARGETS) {
        const now = measured[unit][target.id];
        const before = baseline[unit]?.[target.id];
        if (before === undefined) {
          improvements.push(`${unit} / ${target.id}: new, now ${now}`);
          continue;
        }
        if (now === before) {
          continue;
        }
        // The baseline was recorded on a machine that had the toolchain of
        // this target. Where this one does not, only the Ranger side of the
        // cell can be compared: everything that compiled reads as `compiled`.
        const tool = target.runner?.tool;
        if (tool && !toolAvailable(tool)) {
          const compiledNow = now !== "compile-error";
          const compiledBefore = before !== "compile-error";
          if (compiledNow === compiledBefore) {
            continue;
          }
        }
        const line = `${unit} / ${target.id}: ${before} -> ${now}${
          matrix[unit][target.id].detail
            ? ` (${matrix[unit][target.id].detail})`
            : ""
        }`;
        if (rank[now] < rank[before]) {
          regressions.push(line);
        } else {
          improvements.push(line);
        }
      }
    }

    expect(
      [
        ...regressions.map((r) => `WORSE  ${r}`),
        ...improvements.map((i) => `BETTER ${i}`),
      ].join("\n"),
      "the target matrix moved. A WORSE line is a regression. A BETTER line is " +
        "good news that still needs recording: re-run with " +
        "UPDATE_SYNTAX_APP_BASELINE=1 to update " +
        "tests/syntax_app/target_matrix.json and TARGET_REPORT.md."
    ).toBe("");
  });

  it("keeps the ES6 output of the sections that are run", () => {
    const failures: string[] = [];
    for (const unit of UNITS) {
      if (!unit.expected) {
        continue;
      }
      const cell = matrix[unit.id]["es6"];
      if (cell.status !== "ok") {
        failures.push(`${unit.id}: ${cell.status} ${cell.detail ?? ""}`);
      }
    }
    expect(failures.join("\n"), "units with expected output on ES6").toBe("");
  });

  it("uses the share of compiler/Lang.rgr the README of the app claims", () => {
    // The operator names come from compiler/Lang.rgr itself rather than from
    // docs/site/src/data/operators.json, which is generated and not in the
    // tree. A definition sits at eight spaces of indent and reads
    //   <name>[@(...)] <implementation>[@(...)]:<type> ( arguments ) {
    // The pattern gives the same 207 names as `npm run docs:extract` does for
    // the `core` source.
    const definition =
      /^ {8}([^\s(){}"';]+?)(?:@\(.*?\))?\s+[A-Za-z_]\w*(?:@\(.*?\))?\s*:\s*[^\s(]+\s*\(/;
    const coreNames = [
      ...new Set(
        fs
          .readFileSync(path.join(ROOT_DIR, "compiler/Lang.rgr"), "utf8")
          .split(/\r?\n/)
          .map((line) => definition.exec(line))
          .filter((m): m is RegExpExecArray => m !== null)
          .map((m) => m[1])
      ),
    ];
    expect(
      coreNames.length,
      "the operator pattern stopped matching compiler/Lang.rgr"
    ).toBeGreaterThan(150);

    const source = fs
      .readdirSync(APP_DIR)
      .filter((f) => f.endsWith(".rgr"))
      .map((f) => fs.readFileSync(path.join(APP_DIR, f), "utf8"))
      .join("\n")
      .split("\n")
      .filter((line) => !/^\s*;/.test(line))
      .join("\n");

    const used = coreNames.filter((name) => {
      const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      return new RegExp(`(^|[\\s(])${escaped}([\\s)]|$)`, "m").test(source);
    });

    // The app is expected to grow, not shrink. The floor sits a little under
    // the number the README of the app states; raise both together.
    expect(
      used.length,
      `the app uses ${used.length} of the ${coreNames.length} core operator ` +
        `names. Missing: ${coreNames
          .filter((n) => !used.includes(n))
          .sort()
          .join(" ")}`
    ).toBeGreaterThanOrEqual(195);
  });

  it("keeps the known gaps in the state the record describes", async () => {
    const record: Record<
      string,
      {
        outcome: string;
        note: string;
        target?: string;
        /** The wrong answer the probe prints today, for the wrong-output ones. */
        prints?: string;
      }
    > = JSON.parse(fs.readFileSync(GAPS_FILE, "utf8"));

    const probes = fs
      .readdirSync(GAPS_DIR)
      .filter((f) => f.endsWith(".rgr"))
      .sort();

    const unrecorded = probes
      .map((f) => path.basename(f, ".rgr"))
      .filter((name) => !record[name]);
    expect(unrecorded.join(" "), "gap probes with no entry in gaps.json").toBe(
      ""
    );

    const moved: string[] = [];
    for (const file of probes) {
      const name = path.basename(file, ".rgr");
      // Most gaps show on the reference target. A few -- the Go for loop over
      // an array of objects, for one -- compile and run correctly on ES6 and
      // fail only elsewhere, so the entry names the target to measure on.
      const wanted = record[name].target ?? "es6";
      const target = TARGETS.find((t) => t.id === wanted);
      expect(target, `gaps.json names an unknown target: ${wanted}`).toBeDefined();
      if (!target) {
        continue;
      }
      if (target.runner && !toolAvailable(target.runner.tool)) {
        continue;
      }

      const unit = { id: `gap:${name}`, source: `tests/syntax_app/gaps/${file}` };
      const compiled = compile(unit, target);

      let outcome: string;
      let printed = "";
      if (!compiled.ok) {
        outcome = "compile-error";
      } else {
        const run = runGenerated(target, compiled.outputFile as string);
        printed = normalise(run.output);
        outcome = run.ok ? "wrong-output" : "run-error";
      }

      await yieldToLoop();

      if (outcome !== record[name].outcome) {
        moved.push(
          `${name} (${wanted}): recorded ${record[name].outcome}, measured ${outcome}` +
            (outcome === "compile-error" ? "" : " -- the gap may be fixed")
        );
        continue;
      }

      // A wrong-output gap states the wrong answer, so that a fix is seen and
      // a different wrong answer is not mistaken for the same defect.
      const expectedPrint = record[name].prints;
      if (outcome === "wrong-output" && expectedPrint !== undefined) {
        if (printed !== normalise(expectedPrint)) {
          moved.push(
            `${name} (${wanted}): recorded output ${JSON.stringify(
              expectedPrint
            )}, measured ${JSON.stringify(printed)}`
          );
        }
      }
    }

    expect(
      moved.join("\n"),
      "a known gap changed state. If it is fixed, move the case back into the " +
        "app and delete its probe and its entry in tests/syntax_app/gaps/gaps.json."
    ).toBe("");
  }, 300000);
});
