; Generated by Ranger LLVM backend
target triple = "unknown-unknown-unknown"
@heap_ptr = global i32 0
declare i32 @ranger_obj_new(i32, ptr)
declare void @ranger_obj_release(i32)
declare void @ranger_str_release(i8*)
declare i32 @ranger_mem_live_objects()
declare void @ranger_mem_reset_stats()
declare void @ranger_obj_retain(i32)
declare void @ranger_ptrarray_push_owned(i32, i32)
declare void @ranger_ptrarray_release(i32)
%struct.JSONArrayUnion = type {  }
%struct.JSONObjectUnion = type {  }
%struct.AddLib = type {  }
%struct.RangerFieldDesc = type { i32, i8, i8, i8, i8 }
%struct.RangerTypeDesc = type { i32, i16, i16, ptr }
@JSONArrayUnion_typeDesc = private constant %struct.RangerTypeDesc { i32 0, i16 0, i16 0, ptr null }
@JSONObjectUnion_typeDesc = private constant %struct.RangerTypeDesc { i32 0, i16 0, i16 0, ptr null }
@AddLib_typeDesc = private constant %struct.RangerTypeDesc { i32 0, i16 0, i16 0, ptr null }
define dso_local i32 @AddLib_add(i32 %a, i32 %b) {
entry:
  %a_addr = alloca i32
  store i32 %a, i32* %a_addr
  %b_addr = alloca i32
  store i32 %b, i32* %b_addr
  %.v0 = load i32, i32* %a_addr
  %.v1 = load i32, i32* %b_addr
  %.t2 = add i32 %.v0, %.v1
  ret i32 %.t2
}
