; Generated by Ranger LLVM backend
target triple = "unknown-unknown-unknown"
define dso_local i32 @AddLib_add(i32 %a, i32 %b) {
entry:
  %a_addr = alloca i32
  store i32 %a, i32* %a_addr
  %b_addr = alloca i32
  store i32 %b, i32* %b_addr
  %v0 = load i32, i32* %a_addr
  %v1 = load i32, i32* %b_addr
  %t2 = add i32 %v0, %v1
  ret i32 %t2
}
