; Generated by Ranger LLVM backend
target triple = "unknown-unknown-unknown"
define dso_local i32 @Fact_factorial(i32 %n) {
entry:
  %n_addr = alloca i32
  store i32 %n, i32* %n_addr
  %v0 = load i32, i32* %n_addr
  %c1 = add i32 0, 1
  %p2 = icmp sle i32 %v0, %c1
  br i1 %p2, label %then0, label %merge2
then0:
  %c3 = add i32 0, 1
  ret i32 %c3
merge2:
  %v4 = load i32, i32* %n_addr
  %v5 = load i32, i32* %n_addr
  %c6 = add i32 0, 1
  %t7 = sub i32 %v5, %c6
  %c8 = call i32 @Fact_factorial(i32 %t7)
  %t9 = mul i32 %v4, %c8
  ret i32 %t9
}
