; Generated by Ranger LLVM backend
target triple = "unknown-unknown-unknown"
@heap_ptr = global i32 0
declare i32 @ranger_obj_new(i32, ptr)
declare void @ranger_obj_release(i32)
declare void @ranger_str_release(i8*)
declare i32 @ranger_mem_live_objects()
declare void @ranger_mem_reset_stats()
declare void @ranger_obj_retain(i32)
declare void @ranger_ptrarray_push_owned(i32, i32)
declare void @ranger_ptrarray_release(i32)
%struct.JSONArrayUnion = type {  }
%struct.JSONObjectUnion = type {  }
%struct.Fact = type {  }
%struct.RangerFieldDesc = type { i32, i8, i8, i8, i8 }
%struct.RangerTypeDesc = type { i32, i16, i16, ptr }
@JSONArrayUnion_typeDesc = private constant %struct.RangerTypeDesc { i32 0, i16 0, i16 0, ptr null }
@JSONObjectUnion_typeDesc = private constant %struct.RangerTypeDesc { i32 0, i16 0, i16 0, ptr null }
@Fact_typeDesc = private constant %struct.RangerTypeDesc { i32 0, i16 0, i16 0, ptr null }
define dso_local i32 @Fact_factorial(i32 %n) {
entry:
  %n_addr = alloca i32
  store i32 %n, i32* %n_addr
  %.v0 = load i32, i32* %n_addr
  %.c1 = add i32 0, 1
  %.p2 = icmp sle i32 %.v0, %.c1
  br i1 %.p2, label %then0, label %merge2
then0:
  %.c3 = add i32 0, 1
  ret i32 %.c3
merge2:
  %.v4 = load i32, i32* %n_addr
  %.v5 = load i32, i32* %n_addr
  %.c6 = add i32 0, 1
  %.t7 = sub i32 %.v5, %.c6
  %.c8 = call i32 @Fact_factorial(i32 %.t7)
  %.t9 = mul i32 %.v4, %.c8
  ret i32 %.t9
}
