; Generated by Ranger LLVM backend
target triple = "unknown-unknown-unknown"
@heap_ptr = global i32 0
declare i32 @ranger_obj_new(i32, ptr)
declare void @ranger_obj_release(i32)
declare void @ranger_str_release(i8*)
declare i32 @ranger_mem_live_objects()
declare void @ranger_mem_reset_stats()
declare void @ranger_obj_retain(i32)
declare void @ranger_ptrarray_push_owned(i32, i32)
declare void @ranger_ptrarray_release(i32)
%struct.JSONArrayUnion = type {  }
%struct.JSONObjectUnion = type {  }
%struct.Fib = type {  }
%struct.RangerFieldDesc = type { i32, i8, i8, i8, i8 }
%struct.RangerTypeDesc = type { i32, i16, i16, ptr }
@JSONArrayUnion_typeDesc = private constant %struct.RangerTypeDesc { i32 0, i16 0, i16 0, ptr null }
@JSONObjectUnion_typeDesc = private constant %struct.RangerTypeDesc { i32 0, i16 0, i16 0, ptr null }
@Fib_typeDesc = private constant %struct.RangerTypeDesc { i32 0, i16 0, i16 0, ptr null }
define dso_local i32 @Fib_fib(i32 %n) {
entry:
  %n_addr = alloca i32
  store i32 %n, i32* %n_addr
  %.v0 = load i32, i32* %n_addr
  %.c1 = add i32 0, 2
  %.p2 = icmp slt i32 %.v0, %.c1
  br i1 %.p2, label %then0, label %merge2
then0:
  %.v3 = load i32, i32* %n_addr
  ret i32 %.v3
merge2:
  %.v4 = load i32, i32* %n_addr
  %.c5 = add i32 0, 1
  %.t6 = sub i32 %.v4, %.c5
  %.c7 = call i32 @Fib_fib(i32 %.t6)
  %.v8 = load i32, i32* %n_addr
  %.c9 = add i32 0, 2
  %.t10 = sub i32 %.v8, %.c9
  %.c11 = call i32 @Fib_fib(i32 %.t10)
  %.t12 = add i32 %.c7, %.c11
  ret i32 %.t12
}
