#!/usr/bin/env node
class PDFWriter  {
  constructor() {
    this.nextObjNum = 1;
    this.pdfOutput = "";
    this.objectOffsets = [];
  }
  writeObject (content) {
    this.objectOffsets.push(this.pdfOutput.length);
    this.pdfOutput = (this.pdfOutput + ((this.nextObjNum.toString()))) + " 0 obj\n";
    this.pdfOutput = this.pdfOutput + content;
    this.pdfOutput = this.pdfOutput + "\nendobj\n\n";
    this.nextObjNum = this.nextObjNum + 1;
  };
  escapeText (text) {
    let result = "";
    const __len = text.length;
    let i = 0;
    while (i < __len) {
      const ch = text.charCodeAt(i );
      if ( ch == 40 ) {
        result = result + "\\(";
      } else {
        if ( ch == 41 ) {
          result = result + "\\)";
        } else {
          if ( ch == 92 ) {
            result = result + "\\\\";
          } else {
            result = result + (String.fromCharCode(ch));
          }
        }
      }
      i = i + 1;
    };
    return result;
  };
  createHelloWorldPDF (message) {
    this.nextObjNum = 1;
    this.pdfOutput = "";
    this.objectOffsets.length = 0;
    this.pdfOutput = this.pdfOutput + "%PDF-1.4\n";
    this.pdfOutput = this.pdfOutput + "%E2E3CFD3\n";
    this.writeObject("<< /Type /Catalog /Pages 2 0 R >>");
    this.writeObject("<< /Type /Pages /Kids [3 0 R] /Count 1 >>");
    this.writeObject("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>");
    let stream = "";
    stream = stream + "q\n";
    stream = stream + "1 0 0 RG\n";
    stream = stream + "1 0.8 0.8 rg\n";
    stream = stream + "2 w\n";
    stream = stream + "100 600 200 100 re\n";
    stream = stream + "B\n";
    stream = stream + "Q\n";
    stream = stream + "q\n";
    stream = stream + "0 0 1 RG\n";
    stream = stream + "0.8 0.8 1 rg\n";
    stream = stream + "2 w\n";
    stream = stream + "350 600 m\n";
    stream = stream + "450 600 l\n";
    stream = stream + "400 700 l\n";
    stream = stream + "h\n";
    stream = stream + "B\n";
    stream = stream + "Q\n";
    stream = stream + "q\n";
    stream = stream + "0 0.5 0 RG\n";
    stream = stream + "0.8 1 0.8 rg\n";
    stream = stream + "2 w\n";
    const cx = 200;
    const cy = 450;
    const r = 50;
    const k = 27;
    stream = (((stream + (((cx + r).toString()))) + " ") + ((cy.toString()))) + " m\n";
    stream = (((((((((((stream + (((cx + r).toString()))) + " ") + (((cy + k).toString()))) + " ") + (((cx + k).toString()))) + " ") + (((cy + r).toString()))) + " ") + ((cx.toString()))) + " ") + (((cy + r).toString()))) + " c\n";
    stream = (((((((((((stream + (((cx - k).toString()))) + " ") + (((cy + r).toString()))) + " ") + (((cx - r).toString()))) + " ") + (((cy + k).toString()))) + " ") + (((cx - r).toString()))) + " ") + ((cy.toString()))) + " c\n";
    stream = (((((((((((stream + (((cx - r).toString()))) + " ") + (((cy - k).toString()))) + " ") + (((cx - k).toString()))) + " ") + (((cy - r).toString()))) + " ") + ((cx.toString()))) + " ") + (((cy - r).toString()))) + " c\n";
    stream = (((((((((((stream + (((cx + k).toString()))) + " ") + (((cy - r).toString()))) + " ") + (((cx + r).toString()))) + " ") + (((cy - k).toString()))) + " ") + (((cx + r).toString()))) + " ") + ((cy.toString()))) + " c\n";
    stream = stream + "B\n";
    stream = stream + "Q\n";
    stream = stream + "q\n";
    stream = stream + "0.5 0.5 0.5 RG\n";
    stream = stream + "1 w\n";
    stream = stream + "50 350 m\n";
    stream = stream + "562 350 l\n";
    stream = stream + "S\n";
    stream = stream + "Q\n";
    stream = stream + "BT\n";
    stream = stream + "/F1 36 Tf\n";
    stream = stream + "100 300 Td\n";
    stream = ((stream + "(") + this.escapeText(message)) + ") Tj\n";
    stream = stream + "ET\n";
    stream = stream + "BT\n";
    stream = stream + "/F1 14 Tf\n";
    stream = stream + "100 260 Td\n";
    stream = stream + "(Generated by Ranger PDF Writer) Tj\n";
    stream = stream + "ET\n";
    const streamLen = stream.length;
    this.writeObject(((("<< /Length " + ((streamLen.toString()))) + " >>\nstream\n") + stream) + "endstream");
    this.writeObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
    const xrefOffset = this.pdfOutput.length;
    this.pdfOutput = this.pdfOutput + "xref\n";
    this.pdfOutput = ((this.pdfOutput + "0 ") + ((this.nextObjNum.toString()))) + "\n";
    this.pdfOutput = this.pdfOutput + "0000000000 65535 f \n";
    for ( let i = 0; i < this.objectOffsets.length; i++) {
      var offset = this.objectOffsets[i];
      let offsetStr = (offset.toString());
      while ((offsetStr.length) < 10) {
        offsetStr = "0" + offsetStr;
      };
      this.pdfOutput = (this.pdfOutput + offsetStr) + " 00000 n \n";
    };
    this.pdfOutput = this.pdfOutput + "trailer\n";
    this.pdfOutput = ((this.pdfOutput + "<< /Size ") + ((this.nextObjNum.toString()))) + " /Root 1 0 R >>\n";
    this.pdfOutput = this.pdfOutput + "startxref\n";
    this.pdfOutput = (this.pdfOutput + ((xrefOffset.toString()))) + "\n";
    this.pdfOutput = this.pdfOutput + "%%EOF\n";
    return this.pdfOutput;
  };
  savePDF (path, filename, message) {
    const pdfContent = this.createHelloWorldPDF(message);
    require("fs").writeFileSync( path + "/"  + filename, pdfContent);
    console.log((("PDF saved to " + path) + "/") + filename);
  };
}
class Main  {
  constructor() {
  }
}
/* static JavaSript main routine at the end of the JS file */
function __js_main() {
  console.log("=== Ranger PDF Writer ===");
  const writer = new PDFWriter();
  writer.savePDF("./gallery/pdf_writer", "hello_world.pdf", "Hello, World!");
  console.log("PDF generation complete!");
  console.log("Open gallery/pdf_writer/hello_world.pdf to see the result.");
}
__js_main();
