; Generated by Ranger LLVM backend
target triple = "arm64-apple-macosx"
@.str.0 = private unnamed_addr constant [24 x i8] c"=== SPACE INVADERS ===\0A\00"
@.str.1 = private unnamed_addr constant [11 x i8] c"Controls:\0A\00"
@.str.2 = private unnamed_addr constant [21 x i8] c"  LEFT/RIGHT - Move\0A\00"
@.str.3 = private unnamed_addr constant [22 x i8] c"  SPACE      - Shoot\0A\00"
@.str.4 = private unnamed_addr constant [21 x i8] c"  Q          - Quit\0A\00"
@.str.5 = private unnamed_addr constant [18 x i8] c"Starting game...\0A\00"
@.str.6 = private unnamed_addr constant [1 x i8] c"\00"
@.str.7 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.8 = private unnamed_addr constant [2 x i8] c" \00"
@.str.9 = private unnamed_addr constant [2 x i8] c"=\00"
@.str.10 = private unnamed_addr constant [2 x i8] c"|\00"
@.str.11 = private unnamed_addr constant [49 x i8] c"Score:       |  Arrows=move  SPACE=shoot  Q=quit\00"
@.str.12 = private unnamed_addr constant [2 x i8] c"A\00"
@.str.13 = private unnamed_addr constant [2 x i8] c"W\00"
@.str.14 = private unnamed_addr constant [5 x i8] c"%d%s\00"
@.str.15 = private unnamed_addr constant [4 x i8] c"   \00"
@.str.16 = private unnamed_addr constant [18 x i8] c"=== YOU WIN! ===\0A\00"
@.str.17 = private unnamed_addr constant [19 x i8] c"=== GAME OVER ===\0A\00"
@.str.18 = private unnamed_addr constant [5 x i8] c"%s%d\00"
@.str.19 = private unnamed_addr constant [14 x i8] c"Final Score: \00"
@.str.20 = private unnamed_addr constant [5 x i8] c"left\00"
@.str.21 = private unnamed_addr constant [6 x i8] c"right\00"
@.str.22 = private unnamed_addr constant [2 x i8] c"a\00"
@.str.23 = private unnamed_addr constant [2 x i8] c"d\00"
@.str.24 = private unnamed_addr constant [2 x i8] c"D\00"
@.str.25 = private unnamed_addr constant [6 x i8] c"space\00"
@.str.26 = private unnamed_addr constant [2 x i8] c"q\00"
@.str.27 = private unnamed_addr constant [2 x i8] c"Q\00"
declare i32 @printf(i8*, ...)
declare i64 @malloc(i64)
declare i32 @strcmp(i8*, i8*)
declare void @ranger_term_init()
declare i8* @ranger_poll_key()
declare void @ranger_clear_screen()
declare void @ranger_hide_cursor()
declare void @ranger_show_cursor()
declare void @ranger_move_cursor(i32, i32)
declare i32 @sprintf(i8*, i8*, ...)
declare i32 @usleep(i32)
%struct.Alien = type { i32, i32, i32, i32, i32, i32 }
%struct.Bullet = type { i32, i32, i32, i32, i32, i32 }
%struct.Invaders = type { i32, i32, i32, i32, i32, i64, i64, i32, i32, i32, i32, i32, i32, i32, i32 }
define private void @Alien_Constructor(%struct.Alien* %self, i32 %startX, i32 %startY) {
entry:
  %c0 = add i32 0, 0
  %f1 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 0
  store i32 %c0, i32* %f1
  %c2 = add i32 0, 0
  %f3 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 1
  store i32 %c2, i32* %f3
  %c4 = add i32 0, 0
  %f5 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 2
  store i32 %c4, i32* %f5
  %c6 = add i32 0, 0
  %f7 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 3
  store i32 %c6, i32* %f7
  %c8 = icmp ne i32 1, 0
  %z9 = zext i1 %c8 to i32
  %f10 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 4
  store i32 %z9, i32* %f10
  %c11 = icmp ne i32 1, 0
  %z12 = zext i1 %c11 to i32
  %f13 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 5
  store i32 %z12, i32* %f13
  %startX_addr = alloca i32
  store i32 %startX, i32* %startX_addr
  %startY_addr = alloca i32
  store i32 %startY, i32* %startY_addr
  %v14 = load i32, i32* %startX_addr
  %f15 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 0
  store i32 %v14, i32* %f15
  %v16 = load i32, i32* %startY_addr
  %f17 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 1
  store i32 %v16, i32* %f17
  %v18 = load i32, i32* %startX_addr
  %f19 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 2
  store i32 %v18, i32* %f19
  %v20 = load i32, i32* %startY_addr
  %f21 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 3
  store i32 %v20, i32* %f21
  ret void
}
define private void @Alien_savePrev(%struct.Alien* %self) {
entry:
  %f0 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 0
  %v1 = load i32, i32* %f0
  %f2 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 2
  store i32 %v1, i32* %f2
  %f3 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 1
  %v4 = load i32, i32* %f3
  %f5 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 3
  store i32 %v4, i32* %f5
  %f6 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 4
  %v7 = load i32, i32* %f6
  %f8 = getelementptr %struct.Alien, %struct.Alien* %self, i32 0, i32 5
  store i32 %v7, i32* %f8
  ret void
}
define private void @Bullet_Constructor(%struct.Bullet* %self, i32 %startX, i32 %startY) {
entry:
  %c0 = add i32 0, 0
  %f1 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 0
  store i32 %c0, i32* %f1
  %c2 = add i32 0, 0
  %f3 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 1
  store i32 %c2, i32* %f3
  %c4 = add i32 0, 0
  %f5 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 2
  store i32 %c4, i32* %f5
  %c6 = add i32 0, 0
  %f7 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 3
  store i32 %c6, i32* %f7
  %c8 = icmp ne i32 1, 0
  %z9 = zext i1 %c8 to i32
  %f10 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 4
  store i32 %z9, i32* %f10
  %c11 = icmp ne i32 1, 0
  %z12 = zext i1 %c11 to i32
  %f13 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 5
  store i32 %z12, i32* %f13
  %startX_addr = alloca i32
  store i32 %startX, i32* %startX_addr
  %startY_addr = alloca i32
  store i32 %startY, i32* %startY_addr
  %v14 = load i32, i32* %startX_addr
  %f15 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 0
  store i32 %v14, i32* %f15
  %v16 = load i32, i32* %startY_addr
  %f17 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 1
  store i32 %v16, i32* %f17
  %v18 = load i32, i32* %startX_addr
  %f19 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 2
  store i32 %v18, i32* %f19
  %v20 = load i32, i32* %startY_addr
  %f21 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 3
  store i32 %v20, i32* %f21
  ret void
}
define private void @Bullet_savePrev(%struct.Bullet* %self) {
entry:
  %f0 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 0
  %v1 = load i32, i32* %f0
  %f2 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 2
  store i32 %v1, i32* %f2
  %f3 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 1
  %v4 = load i32, i32* %f3
  %f5 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 3
  store i32 %v4, i32* %f5
  %f6 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 4
  %v7 = load i32, i32* %f6
  %f8 = getelementptr %struct.Bullet, %struct.Bullet* %self, i32 0, i32 5
  store i32 %v7, i32* %f8
  ret void
}
define dso_local i32 @main() {
entry:
  %c0 = add i64 0, 120
  %c1 = call i64 @malloc(i64 %c0)
  %p2 = inttoptr i64 %c1 to %struct.Invaders*
  %c3 = add i32 0, 40
  %f4 = getelementptr %struct.Invaders, %struct.Invaders* %p2, i32 0, i32 0
  store i32 %c3, i32* %f4
  %c5 = add i32 0, 18
  %f6 = getelementptr %struct.Invaders, %struct.Invaders* %p2, i32 0, i32 1
  store i32 %c5, i32* %f6
  %c7 = add i32 0, 16
  %f8 = getelementptr %struct.Invaders, %struct.Invaders* %p2, i32 0, i32 2
  store i32 %c7, i32* %f8
  %c9 = add i32 0, 20
  %f10 = getelementptr %struct.Invaders, %struct.Invaders* %p2, i32 0, i32 3
  store i32 %c9, i32* %f10
  %c11 = add i32 0, -1
  %f12 = getelementptr %struct.Invaders, %struct.Invaders* %p2, i32 0, i32 4
  store i32 %c11, i32* %f12
  %c13 = add i32 0, 0
  %f14 = getelementptr %struct.Invaders, %struct.Invaders* %p2, i32 0, i32 7
  store i32 %c13, i32* %f14
  %c15 = add i32 0, 0
  %f16 = getelementptr %struct.Invaders, %struct.Invaders* %p2, i32 0, i32 8
  store i32 %c15, i32* %f16
  %c17 = icmp eq i32 0, 1
  %z18 = zext i1 %c17 to i32
  %f19 = getelementptr %struct.Invaders, %struct.Invaders* %p2, i32 0, i32 9
  store i32 %z18, i32* %f19
  %c20 = icmp eq i32 0, 1
  %z21 = zext i1 %c20 to i32
  %f22 = getelementptr %struct.Invaders, %struct.Invaders* %p2, i32 0, i32 10
  store i32 %z21, i32* %f22
  %c23 = add i32 0, 1
  %f24 = getelementptr %struct.Invaders, %struct.Invaders* %p2, i32 0, i32 11
  store i32 %c23, i32* %f24
  %c25 = add i32 0, 0
  %f26 = getelementptr %struct.Invaders, %struct.Invaders* %p2, i32 0, i32 12
  store i32 %c25, i32* %f26
  %c27 = add i32 0, 8
  %f28 = getelementptr %struct.Invaders, %struct.Invaders* %p2, i32 0, i32 13
  store i32 %c27, i32* %f28
  %c29 = icmp ne i32 1, 0
  %z30 = zext i1 %c29 to i32
  %f31 = getelementptr %struct.Invaders, %struct.Invaders* %p2, i32 0, i32 14
  store i32 %z30, i32* %f31
  call void @Invaders_Constructor(%struct.Invaders* %p2)
  %game_addr = alloca i64
  store i64 %c1, i64* %game_addr
  %s32 = getelementptr inbounds [24 x i8], [24 x i8]* @.str.0, i64 0, i64 0
  %c33 = call i32 @printf(i8* %s32)
  %s34 = getelementptr inbounds [11 x i8], [11 x i8]* @.str.1, i64 0, i64 0
  %c35 = call i32 @printf(i8* %s34)
  %s36 = getelementptr inbounds [21 x i8], [21 x i8]* @.str.2, i64 0, i64 0
  %c37 = call i32 @printf(i8* %s36)
  %s38 = getelementptr inbounds [22 x i8], [22 x i8]* @.str.3, i64 0, i64 0
  %c39 = call i32 @printf(i8* %s38)
  %s40 = getelementptr inbounds [21 x i8], [21 x i8]* @.str.4, i64 0, i64 0
  %c41 = call i32 @printf(i8* %s40)
  %s42 = getelementptr inbounds [18 x i8], [18 x i8]* @.str.5, i64 0, i64 0
  %c43 = call i32 @printf(i8* %s42)
  %s44 = getelementptr inbounds [1 x i8], [1 x i8]* @.str.6, i64 0, i64 0
  %key_addr = alloca i8*
  store i8* %s44, i8** %key_addr
  call void @ranger_term_init()
  call void @ranger_hide_cursor()
  %v45 = load i64, i64* %game_addr
  %p46 = inttoptr i64 %v45 to %struct.Invaders*
  call void @Invaders_gameLoop(%struct.Invaders* %p46)
  %c47 = add i32 0, 0
  ret i32 %c47
}
define private void @Invaders_Constructor(%struct.Invaders* %self) {
entry:
  %c0 = add i32 0, 40
  %f1 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 0
  store i32 %c0, i32* %f1
  %c2 = add i32 0, 18
  %f3 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 1
  store i32 %c2, i32* %f3
  %c4 = add i32 0, 16
  %f5 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 2
  store i32 %c4, i32* %f5
  %c6 = add i32 0, 20
  %f7 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 3
  store i32 %c6, i32* %f7
  %c8 = add i32 0, -1
  %f9 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 4
  store i32 %c8, i32* %f9
  %c10 = add i32 0, 0
  %f11 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 7
  store i32 %c10, i32* %f11
  %c12 = add i32 0, 0
  %f13 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 8
  store i32 %c12, i32* %f13
  %c14 = icmp eq i32 0, 1
  %z15 = zext i1 %c14 to i32
  %f16 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 9
  store i32 %z15, i32* %f16
  %c17 = icmp eq i32 0, 1
  %z18 = zext i1 %c17 to i32
  %f19 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 10
  store i32 %z18, i32* %f19
  %c20 = add i32 0, 1
  %f21 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 11
  store i32 %c20, i32* %f21
  %c22 = add i32 0, 0
  %f23 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 12
  store i32 %c22, i32* %f23
  %c24 = add i32 0, 8
  %f25 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 13
  store i32 %c24, i32* %f25
  %c26 = icmp ne i32 1, 0
  %z27 = zext i1 %c26 to i32
  %f28 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 14
  store i32 %z27, i32* %f28
  %c29 = add i32 0, 32
  %c30 = call i64 @RtPtrArray_new(i32 %c29)
  %f31 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 5
  store i64 %c30, i64* %f31
  %c32 = add i32 0, 32
  %c33 = call i64 @RtPtrArray_new(i32 %c32)
  %f34 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 6
  store i64 %c33, i64* %f34
  call void @Invaders_initAliens(%struct.Invaders* %self)
  ret void
}
define private void @Invaders_initAliens(%struct.Invaders* %self) {
entry:
  %c0 = add i32 0, 0
  %row_addr = alloca i32
  store i32 %c0, i32* %row_addr
  br label %while_cond0
while_cond0:
  %v1 = load i32, i32* %row_addr
  %c2 = add i32 0, 3
  %p3 = icmp slt i32 %v1, %c2
  br i1 %p3, label %while_body1, label %while_exit2
while_body1:
  %c4 = add i32 0, 0
  %col_addr = alloca i32
  store i32 %c4, i32* %col_addr
  br label %while_cond3
while_cond3:
  %v5 = load i32, i32* %col_addr
  %c6 = add i32 0, 8
  %p7 = icmp slt i32 %v5, %c6
  br i1 %p7, label %while_body4, label %while_exit5
while_body4:
  %v8 = load i32, i32* %col_addr
  %c9 = add i32 0, 4
  %t10 = mul i32 %v8, %c9
  %c11 = add i32 0, 4
  %t12 = add i32 %t10, %c11
  %ax_addr = alloca i32
  store i32 %t12, i32* %ax_addr
  %v13 = load i32, i32* %row_addr
  %c14 = add i32 0, 2
  %t15 = add i32 %v13, %c14
  %ay_addr = alloca i32
  store i32 %t15, i32* %ay_addr
  %c16 = add i64 0, 48
  %c17 = call i64 @malloc(i64 %c16)
  %p18 = inttoptr i64 %c17 to %struct.Alien*
  %c19 = add i32 0, 0
  %f20 = getelementptr %struct.Alien, %struct.Alien* %p18, i32 0, i32 0
  store i32 %c19, i32* %f20
  %c21 = add i32 0, 0
  %f22 = getelementptr %struct.Alien, %struct.Alien* %p18, i32 0, i32 1
  store i32 %c21, i32* %f22
  %c23 = add i32 0, 0
  %f24 = getelementptr %struct.Alien, %struct.Alien* %p18, i32 0, i32 2
  store i32 %c23, i32* %f24
  %c25 = add i32 0, 0
  %f26 = getelementptr %struct.Alien, %struct.Alien* %p18, i32 0, i32 3
  store i32 %c25, i32* %f26
  %c27 = icmp ne i32 1, 0
  %z28 = zext i1 %c27 to i32
  %f29 = getelementptr %struct.Alien, %struct.Alien* %p18, i32 0, i32 4
  store i32 %z28, i32* %f29
  %c30 = icmp ne i32 1, 0
  %z31 = zext i1 %c30 to i32
  %f32 = getelementptr %struct.Alien, %struct.Alien* %p18, i32 0, i32 5
  store i32 %z31, i32* %f32
  %v33 = load i32, i32* %ax_addr
  %v34 = load i32, i32* %ay_addr
  call void @Alien_Constructor(%struct.Alien* %p18, i32 %v33, i32 %v34)
  %alien_addr = alloca i64
  store i64 %c17, i64* %alien_addr
  %f35 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 5
  %v36 = load i64, i64* %f35
  %v37 = load i64, i64* %alien_addr
  call void @RtPtrArray_push(i64 %v36, i64 %v37)
  %v38 = load i32, i32* %col_addr
  %c39 = add i32 0, 1
  %t40 = add i32 %v38, %c39
  store i32 %t40, i32* %col_addr
  br label %while_cond3
while_exit5:
  %v41 = load i32, i32* %row_addr
  %c42 = add i32 0, 1
  %t43 = add i32 %v41, %c42
  store i32 %t43, i32* %row_addr
  br label %while_cond0
while_exit2:
  ret void
}
define private void @Invaders_drawAt(%struct.Invaders* %self, i32 %x, i32 %y, i8* %ch) {
entry:
  %x_addr = alloca i32
  store i32 %x, i32* %x_addr
  %y_addr = alloca i32
  store i32 %y, i32* %y_addr
  %ch_addr = alloca i8*
  store i8* %ch, i8** %ch_addr
  %v0 = load i32, i32* %x_addr
  %c1 = add i32 0, 1
  %t2 = add i32 %v0, %c1
  %v3 = load i32, i32* %y_addr
  %c4 = add i32 0, 1
  %t5 = add i32 %v3, %c4
  call void @ranger_move_cursor(i32 %t2, i32 %t5)
  %v6 = load i8*, i8** %ch_addr
  %s7 = getelementptr inbounds [3 x i8], [3 x i8]* @.str.7, i64 0, i64 0
  %c8 = call i32 @printf(i8* %s7, i8* %v6)
  ret void
}
define private void @Invaders_eraseAt(%struct.Invaders* %self, i32 %x, i32 %y) {
entry:
  %x_addr = alloca i32
  store i32 %x, i32* %x_addr
  %y_addr = alloca i32
  store i32 %y, i32* %y_addr
  %v0 = load i32, i32* %x_addr
  %c1 = add i32 0, 1
  %t2 = add i32 %v0, %c1
  %v3 = load i32, i32* %y_addr
  %c4 = add i32 0, 1
  %t5 = add i32 %v3, %c4
  call void @ranger_move_cursor(i32 %t2, i32 %t5)
  %s6 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.8, i64 0, i64 0
  %c7 = call i32 @printf(i8* %s6)
  ret void
}
define private void @Invaders_drawBorders(%struct.Invaders* %self) {
entry:
  %c0 = add i32 0, 1
  %c1 = add i32 0, 1
  call void @ranger_move_cursor(i32 %c0, i32 %c1)
  %c2 = add i32 0, 0
  %i_addr = alloca i32
  store i32 %c2, i32* %i_addr
  %f3 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 0
  %v4 = load i32, i32* %f3
  %c5 = add i32 0, 2
  %t6 = add i32 %v4, %c5
  %borderW_addr = alloca i32
  store i32 %t6, i32* %borderW_addr
  br label %while_cond0
while_cond0:
  %v7 = load i32, i32* %i_addr
  %v8 = load i32, i32* %borderW_addr
  %p9 = icmp slt i32 %v7, %v8
  br i1 %p9, label %while_body1, label %while_exit2
while_body1:
  %s10 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.9, i64 0, i64 0
  %c11 = call i32 @printf(i8* %s10)
  %v12 = load i32, i32* %i_addr
  %c13 = add i32 0, 1
  %t14 = add i32 %v12, %c13
  store i32 %t14, i32* %i_addr
  br label %while_cond0
while_exit2:
  %c15 = add i32 0, 0
  %y_addr = alloca i32
  store i32 %c15, i32* %y_addr
  br label %while_cond3
while_cond3:
  %v16 = load i32, i32* %y_addr
  %f17 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 1
  %v18 = load i32, i32* %f17
  %p19 = icmp slt i32 %v16, %v18
  br i1 %p19, label %while_body4, label %while_exit5
while_body4:
  %c20 = add i32 0, 1
  %v21 = load i32, i32* %y_addr
  %c22 = add i32 0, 2
  %t23 = add i32 %v21, %c22
  call void @ranger_move_cursor(i32 %c20, i32 %t23)
  %s24 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.10, i64 0, i64 0
  %c25 = call i32 @printf(i8* %s24)
  %f26 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 0
  %v27 = load i32, i32* %f26
  %c28 = add i32 0, 2
  %t29 = add i32 %v27, %c28
  %rightX_addr = alloca i32
  store i32 %t29, i32* %rightX_addr
  %v30 = load i32, i32* %rightX_addr
  %v31 = load i32, i32* %y_addr
  %c32 = add i32 0, 2
  %t33 = add i32 %v31, %c32
  call void @ranger_move_cursor(i32 %v30, i32 %t33)
  %s34 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.10, i64 0, i64 0
  %c35 = call i32 @printf(i8* %s34)
  %v36 = load i32, i32* %y_addr
  %c37 = add i32 0, 1
  %t38 = add i32 %v36, %c37
  store i32 %t38, i32* %y_addr
  br label %while_cond3
while_exit5:
  %f39 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 1
  %v40 = load i32, i32* %f39
  %c41 = add i32 0, 2
  %t42 = add i32 %v40, %c41
  %bottomY_addr = alloca i32
  store i32 %t42, i32* %bottomY_addr
  %c43 = add i32 0, 1
  %v44 = load i32, i32* %bottomY_addr
  call void @ranger_move_cursor(i32 %c43, i32 %v44)
  %c45 = add i32 0, 0
  %j_addr = alloca i32
  store i32 %c45, i32* %j_addr
  br label %while_cond6
while_cond6:
  %v46 = load i32, i32* %j_addr
  %v47 = load i32, i32* %borderW_addr
  %p48 = icmp slt i32 %v46, %v47
  br i1 %p48, label %while_body7, label %while_exit8
while_body7:
  %s49 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.9, i64 0, i64 0
  %c50 = call i32 @printf(i8* %s49)
  %v51 = load i32, i32* %j_addr
  %c52 = add i32 0, 1
  %t53 = add i32 %v51, %c52
  store i32 %t53, i32* %j_addr
  br label %while_cond6
while_exit8:
  %f54 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 1
  %v55 = load i32, i32* %f54
  %c56 = add i32 0, 3
  %t57 = add i32 %v55, %c56
  %scoreY_addr = alloca i32
  store i32 %t57, i32* %scoreY_addr
  %c58 = add i32 0, 1
  %v59 = load i32, i32* %scoreY_addr
  call void @ranger_move_cursor(i32 %c58, i32 %v59)
  %s60 = getelementptr inbounds [49 x i8], [49 x i8]* @.str.11, i64 0, i64 0
  %c61 = call i32 @printf(i8* %s60)
  ret void
}
define private void @Invaders_render(%struct.Invaders* %self) {
entry:
  %f0 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 14
  %v1 = load i32, i32* %f0
  %c2 = add i32 0, 0
  %p3 = icmp ne i32 %v1, %c2
  br i1 %p3, label %then0, label %merge2
then0:
  call void @ranger_clear_screen()
  call void @Invaders_drawBorders(%struct.Invaders* %self)
  %c4 = icmp eq i32 0, 1
  %z5 = zext i1 %c4 to i32
  %f6 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 14
  store i32 %z5, i32* %f6
  br label %merge2
merge2:
  %f7 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 4
  %v8 = load i32, i32* %f7
  %c9 = add i32 0, 0
  %p10 = icmp sge i32 %v8, %c9
  br i1 %p10, label %then3, label %merge5
then3:
  %f11 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 4
  %v12 = load i32, i32* %f11
  %f13 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 3
  %v14 = load i32, i32* %f13
  %p15 = icmp ne i32 %v12, %v14
  br i1 %p15, label %then6, label %merge8
then6:
  %f16 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 4
  %v17 = load i32, i32* %f16
  %f18 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 2
  %v19 = load i32, i32* %f18
  call void @Invaders_eraseAt(%struct.Invaders* %self, i32 %v17, i32 %v19)
  br label %merge8
merge8:
  br label %merge5
merge5:
  %f20 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 3
  %v21 = load i32, i32* %f20
  %f22 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 2
  %v23 = load i32, i32* %f22
  %s24 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.12, i64 0, i64 0
  call void @Invaders_drawAt(%struct.Invaders* %self, i32 %v21, i32 %v23, i8* %s24)
  %f25 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 3
  %v26 = load i32, i32* %f25
  %f27 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 4
  store i32 %v26, i32* %f27
  %f28 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 5
  %v29 = load i64, i64* %f28
  %c30 = call i32 @RtPtrArray_len(i64 %v29)
  %c31 = add i32 0, 0
  %idx_addr = alloca i32
  store i32 %c31, i32* %idx_addr
  br label %for_cond9
for_cond9:
  %v32 = load i32, i32* %idx_addr
  %p33 = icmp slt i32 %v32, %c30
  br i1 %p33, label %for_body10, label %for_exit11
for_body10:
  %c34 = call i64 @RtPtrArray_get(i64 %v29, i32 %v32)
  %alien_addr = alloca i64
  store i64 %c34, i64* %alien_addr
  %v35 = load i64, i64* %alien_addr
  %p36 = inttoptr i64 %v35 to %struct.Alien*
  %f37 = getelementptr %struct.Alien, %struct.Alien* %p36, i32 0, i32 5
  %v38 = load i32, i32* %f37
  %c39 = add i32 0, 0
  %p40 = icmp ne i32 %v38, %c39
  br i1 %p40, label %then13, label %merge15
then13:
  %c41 = icmp eq i32 0, 1
  %moved_addr = alloca i1
  store i1 %c41, i1* %moved_addr
  %v42 = load i64, i64* %alien_addr
  %p43 = inttoptr i64 %v42 to %struct.Alien*
  %f44 = getelementptr %struct.Alien, %struct.Alien* %p43, i32 0, i32 2
  %v45 = load i32, i32* %f44
  %v46 = load i64, i64* %alien_addr
  %p47 = inttoptr i64 %v46 to %struct.Alien*
  %f48 = getelementptr %struct.Alien, %struct.Alien* %p47, i32 0, i32 0
  %v49 = load i32, i32* %f48
  %p50 = icmp ne i32 %v45, %v49
  br i1 %p50, label %then16, label %merge18
then16:
  %c51 = icmp ne i32 1, 0
  store i1 %c51, i1* %moved_addr
  br label %merge18
merge18:
  %v52 = load i64, i64* %alien_addr
  %p53 = inttoptr i64 %v52 to %struct.Alien*
  %f54 = getelementptr %struct.Alien, %struct.Alien* %p53, i32 0, i32 3
  %v55 = load i32, i32* %f54
  %v56 = load i64, i64* %alien_addr
  %p57 = inttoptr i64 %v56 to %struct.Alien*
  %f58 = getelementptr %struct.Alien, %struct.Alien* %p57, i32 0, i32 1
  %v59 = load i32, i32* %f58
  %p60 = icmp ne i32 %v55, %v59
  br i1 %p60, label %then19, label %merge21
then19:
  %c61 = icmp ne i32 1, 0
  store i1 %c61, i1* %moved_addr
  br label %merge21
merge21:
  %v62 = load i1, i1* %moved_addr
  br i1 %v62, label %then22, label %merge24
then22:
  %v63 = load i64, i64* %alien_addr
  %p64 = inttoptr i64 %v63 to %struct.Alien*
  %f65 = getelementptr %struct.Alien, %struct.Alien* %p64, i32 0, i32 2
  %v66 = load i32, i32* %f65
  %c67 = add i32 0, 1
  %t68 = add i32 %v66, %c67
  %oldAx_addr = alloca i32
  store i32 %t68, i32* %oldAx_addr
  %v69 = load i32, i32* %oldAx_addr
  %v70 = load i64, i64* %alien_addr
  %p71 = inttoptr i64 %v70 to %struct.Alien*
  %f72 = getelementptr %struct.Alien, %struct.Alien* %p71, i32 0, i32 3
  %v73 = load i32, i32* %f72
  call void @Invaders_eraseAt(%struct.Invaders* %self, i32 %v69, i32 %v73)
  br label %merge24
merge24:
  %v74 = load i64, i64* %alien_addr
  %p75 = inttoptr i64 %v74 to %struct.Alien*
  %f76 = getelementptr %struct.Alien, %struct.Alien* %p75, i32 0, i32 4
  %v77 = load i32, i32* %f76
  %c78 = icmp eq i32 0, 1
  %z79 = zext i1 %c78 to i32
  %p80 = icmp eq i32 %v77, %z79
  br i1 %p80, label %then25, label %merge27
then25:
  %v81 = load i64, i64* %alien_addr
  %p82 = inttoptr i64 %v81 to %struct.Alien*
  %f83 = getelementptr %struct.Alien, %struct.Alien* %p82, i32 0, i32 0
  %v84 = load i32, i32* %f83
  %c85 = add i32 0, 1
  %t86 = add i32 %v84, %c85
  %killAx_addr = alloca i32
  store i32 %t86, i32* %killAx_addr
  %v87 = load i32, i32* %killAx_addr
  %v88 = load i64, i64* %alien_addr
  %p89 = inttoptr i64 %v88 to %struct.Alien*
  %f90 = getelementptr %struct.Alien, %struct.Alien* %p89, i32 0, i32 1
  %v91 = load i32, i32* %f90
  call void @Invaders_eraseAt(%struct.Invaders* %self, i32 %v87, i32 %v91)
  br label %merge27
merge27:
  br label %merge15
merge15:
  %v92 = load i64, i64* %alien_addr
  %p93 = inttoptr i64 %v92 to %struct.Alien*
  %f94 = getelementptr %struct.Alien, %struct.Alien* %p93, i32 0, i32 4
  %v95 = load i32, i32* %f94
  %c96 = add i32 0, 0
  %p97 = icmp ne i32 %v95, %c96
  br i1 %p97, label %then28, label %merge30
then28:
  %v98 = load i64, i64* %alien_addr
  %p99 = inttoptr i64 %v98 to %struct.Alien*
  %f100 = getelementptr %struct.Alien, %struct.Alien* %p99, i32 0, i32 0
  %v101 = load i32, i32* %f100
  %c102 = add i32 0, 1
  %t103 = add i32 %v101, %c102
  %drawX_addr = alloca i32
  store i32 %t103, i32* %drawX_addr
  %v104 = load i32, i32* %drawX_addr
  %v105 = load i64, i64* %alien_addr
  %p106 = inttoptr i64 %v105 to %struct.Alien*
  %f107 = getelementptr %struct.Alien, %struct.Alien* %p106, i32 0, i32 1
  %v108 = load i32, i32* %f107
  %s109 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.13, i64 0, i64 0
  call void @Invaders_drawAt(%struct.Invaders* %self, i32 %v104, i32 %v108, i8* %s109)
  br label %merge30
merge30:
  br label %for_inc12
for_inc12:
  %v110 = load i32, i32* %idx_addr
  %c111 = add i32 0, 1
  %t112 = add i32 %v110, %c111
  store i32 %t112, i32* %idx_addr
  br label %for_cond9
for_exit11:
  %f113 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 6
  %v114 = load i64, i64* %f113
  %c115 = call i32 @RtPtrArray_len(i64 %v114)
  %c116 = add i32 0, 0
  %idx2_addr = alloca i32
  store i32 %c116, i32* %idx2_addr
  br label %for_cond31
for_cond31:
  %v117 = load i32, i32* %idx2_addr
  %p118 = icmp slt i32 %v117, %c115
  br i1 %p118, label %for_body32, label %for_exit33
for_body32:
  %c119 = call i64 @RtPtrArray_get(i64 %v114, i32 %v117)
  %bullet_addr = alloca i64
  store i64 %c119, i64* %bullet_addr
  %v120 = load i64, i64* %bullet_addr
  %p121 = inttoptr i64 %v120 to %struct.Bullet*
  %f122 = getelementptr %struct.Bullet, %struct.Bullet* %p121, i32 0, i32 5
  %v123 = load i32, i32* %f122
  %c124 = add i32 0, 0
  %p125 = icmp ne i32 %v123, %c124
  br i1 %p125, label %then35, label %merge37
then35:
  %v126 = load i64, i64* %bullet_addr
  %p127 = inttoptr i64 %v126 to %struct.Bullet*
  %f128 = getelementptr %struct.Bullet, %struct.Bullet* %p127, i32 0, i32 2
  %v129 = load i32, i32* %f128
  %c130 = add i32 0, 1
  %t131 = add i32 %v129, %c130
  %oldBx_addr = alloca i32
  store i32 %t131, i32* %oldBx_addr
  %v132 = load i32, i32* %oldBx_addr
  %v133 = load i64, i64* %bullet_addr
  %p134 = inttoptr i64 %v133 to %struct.Bullet*
  %f135 = getelementptr %struct.Bullet, %struct.Bullet* %p134, i32 0, i32 3
  %v136 = load i32, i32* %f135
  call void @Invaders_eraseAt(%struct.Invaders* %self, i32 %v132, i32 %v136)
  br label %merge37
merge37:
  %v137 = load i64, i64* %bullet_addr
  %p138 = inttoptr i64 %v137 to %struct.Bullet*
  %f139 = getelementptr %struct.Bullet, %struct.Bullet* %p138, i32 0, i32 4
  %v140 = load i32, i32* %f139
  %c141 = add i32 0, 0
  %p142 = icmp ne i32 %v140, %c141
  br i1 %p142, label %then38, label %merge40
then38:
  %v143 = load i64, i64* %bullet_addr
  %p144 = inttoptr i64 %v143 to %struct.Bullet*
  %f145 = getelementptr %struct.Bullet, %struct.Bullet* %p144, i32 0, i32 0
  %v146 = load i32, i32* %f145
  %c147 = add i32 0, 1
  %t148 = add i32 %v146, %c147
  %bx_addr = alloca i32
  store i32 %t148, i32* %bx_addr
  %v149 = load i32, i32* %bx_addr
  %v150 = load i64, i64* %bullet_addr
  %p151 = inttoptr i64 %v150 to %struct.Bullet*
  %f152 = getelementptr %struct.Bullet, %struct.Bullet* %p151, i32 0, i32 1
  %v153 = load i32, i32* %f152
  %s154 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.10, i64 0, i64 0
  call void @Invaders_drawAt(%struct.Invaders* %self, i32 %v149, i32 %v153, i8* %s154)
  br label %merge40
merge40:
  br label %for_inc34
for_inc34:
  %v155 = load i32, i32* %idx2_addr
  %c156 = add i32 0, 1
  %t157 = add i32 %v155, %c156
  store i32 %t157, i32* %idx2_addr
  br label %for_cond31
for_exit33:
  %f158 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 7
  %v159 = load i32, i32* %f158
  %f160 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 8
  %v161 = load i32, i32* %f160
  %p162 = icmp ne i32 %v159, %v161
  br i1 %p162, label %then41, label %merge43
then41:
  %f163 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 1
  %v164 = load i32, i32* %f163
  %c165 = add i32 0, 3
  %t166 = add i32 %v164, %c165
  %scoreY_addr = alloca i32
  store i32 %t166, i32* %scoreY_addr
  %c167 = add i32 0, 8
  %v168 = load i32, i32* %scoreY_addr
  call void @ranger_move_cursor(i32 %c167, i32 %v168)
  %c169 = add i64 0, 64
  %c170 = call i64 @malloc(i64 %c169)
  %s171 = inttoptr i64 %c170 to i8*
  %s172 = getelementptr inbounds [5 x i8], [5 x i8]* @.str.14, i64 0, i64 0
  %f173 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 7
  %v174 = load i32, i32* %f173
  %s175 = getelementptr inbounds [4 x i8], [4 x i8]* @.str.15, i64 0, i64 0
  %c176 = call i32 @sprintf(i8* %s171, i8* %s172, i32 %v174, i8* %s175)
  %scoreStr_addr = alloca i8*
  store i8* %s171, i8** %scoreStr_addr
  %v177 = load i8*, i8** %scoreStr_addr
  %s178 = getelementptr inbounds [3 x i8], [3 x i8]* @.str.7, i64 0, i64 0
  %c179 = call i32 @printf(i8* %s178, i8* %v177)
  br label %merge43
merge43:
  %f180 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 1
  %v181 = load i32, i32* %f180
  %c182 = add i32 0, 4
  %t183 = add i32 %v181, %c182
  %endY_addr = alloca i32
  store i32 %t183, i32* %endY_addr
  %c184 = add i32 0, 1
  %v185 = load i32, i32* %endY_addr
  call void @ranger_move_cursor(i32 %c184, i32 %v185)
  ret void
}
define private void @Invaders_savePrevState(%struct.Invaders* %self) {
entry:
  %f0 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 7
  %v1 = load i32, i32* %f0
  %f2 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 8
  store i32 %v1, i32* %f2
  %f3 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 5
  %v4 = load i64, i64* %f3
  %c5 = call i32 @RtPtrArray_len(i64 %v4)
  %c6 = add i32 0, 0
  %idx_addr = alloca i32
  store i32 %c6, i32* %idx_addr
  br label %for_cond0
for_cond0:
  %v7 = load i32, i32* %idx_addr
  %p8 = icmp slt i32 %v7, %c5
  br i1 %p8, label %for_body1, label %for_exit2
for_body1:
  %c9 = call i64 @RtPtrArray_get(i64 %v4, i32 %v7)
  %alien_addr = alloca i64
  store i64 %c9, i64* %alien_addr
  %v10 = load i64, i64* %alien_addr
  %p11 = inttoptr i64 %v10 to %struct.Alien*
  call void @Alien_savePrev(%struct.Alien* %p11)
  br label %for_inc3
for_inc3:
  %v12 = load i32, i32* %idx_addr
  %c13 = add i32 0, 1
  %t14 = add i32 %v12, %c13
  store i32 %t14, i32* %idx_addr
  br label %for_cond0
for_exit2:
  %f15 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 6
  %v16 = load i64, i64* %f15
  %c17 = call i32 @RtPtrArray_len(i64 %v16)
  %c18 = add i32 0, 0
  %idx2_addr = alloca i32
  store i32 %c18, i32* %idx2_addr
  br label %for_cond4
for_cond4:
  %v19 = load i32, i32* %idx2_addr
  %p20 = icmp slt i32 %v19, %c17
  br i1 %p20, label %for_body5, label %for_exit6
for_body5:
  %c21 = call i64 @RtPtrArray_get(i64 %v16, i32 %v19)
  %bullet_addr = alloca i64
  store i64 %c21, i64* %bullet_addr
  %v22 = load i64, i64* %bullet_addr
  %p23 = inttoptr i64 %v22 to %struct.Bullet*
  call void @Bullet_savePrev(%struct.Bullet* %p23)
  br label %for_inc7
for_inc7:
  %v24 = load i32, i32* %idx2_addr
  %c25 = add i32 0, 1
  %t26 = add i32 %v24, %c25
  store i32 %t26, i32* %idx2_addr
  br label %for_cond4
for_exit6:
  ret void
}
define private void @Invaders_shoot(%struct.Invaders* %self) {
entry:
  %f0 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 2
  %v1 = load i32, i32* %f0
  %c2 = add i32 0, 1
  %t3 = sub i32 %v1, %c2
  %bulletY_addr = alloca i32
  store i32 %t3, i32* %bulletY_addr
  %c4 = add i64 0, 48
  %c5 = call i64 @malloc(i64 %c4)
  %p6 = inttoptr i64 %c5 to %struct.Bullet*
  %c7 = add i32 0, 0
  %f8 = getelementptr %struct.Bullet, %struct.Bullet* %p6, i32 0, i32 0
  store i32 %c7, i32* %f8
  %c9 = add i32 0, 0
  %f10 = getelementptr %struct.Bullet, %struct.Bullet* %p6, i32 0, i32 1
  store i32 %c9, i32* %f10
  %c11 = add i32 0, 0
  %f12 = getelementptr %struct.Bullet, %struct.Bullet* %p6, i32 0, i32 2
  store i32 %c11, i32* %f12
  %c13 = add i32 0, 0
  %f14 = getelementptr %struct.Bullet, %struct.Bullet* %p6, i32 0, i32 3
  store i32 %c13, i32* %f14
  %c15 = icmp ne i32 1, 0
  %z16 = zext i1 %c15 to i32
  %f17 = getelementptr %struct.Bullet, %struct.Bullet* %p6, i32 0, i32 4
  store i32 %z16, i32* %f17
  %c18 = icmp ne i32 1, 0
  %z19 = zext i1 %c18 to i32
  %f20 = getelementptr %struct.Bullet, %struct.Bullet* %p6, i32 0, i32 5
  store i32 %z19, i32* %f20
  %f21 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 3
  %v22 = load i32, i32* %f21
  %v23 = load i32, i32* %bulletY_addr
  call void @Bullet_Constructor(%struct.Bullet* %p6, i32 %v22, i32 %v23)
  %bullet_addr = alloca i64
  store i64 %c5, i64* %bullet_addr
  %f24 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 6
  %v25 = load i64, i64* %f24
  %v26 = load i64, i64* %bullet_addr
  call void @RtPtrArray_push(i64 %v25, i64 %v26)
  ret void
}
define private void @Invaders_moveLeft(%struct.Invaders* %self) {
entry:
  %f0 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 3
  %v1 = load i32, i32* %f0
  %c2 = add i32 0, 2
  %p3 = icmp sgt i32 %v1, %c2
  br i1 %p3, label %then0, label %merge2
then0:
  %f4 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 3
  %v5 = load i32, i32* %f4
  %c6 = add i32 0, 1
  %t7 = sub i32 %v5, %c6
  %f8 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 3
  store i32 %t7, i32* %f8
  br label %merge2
merge2:
  ret void
}
define private void @Invaders_moveRight(%struct.Invaders* %self) {
entry:
  %f0 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 0
  %v1 = load i32, i32* %f0
  %c2 = add i32 0, 1
  %t3 = sub i32 %v1, %c2
  %maxX_addr = alloca i32
  store i32 %t3, i32* %maxX_addr
  %f4 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 3
  %v5 = load i32, i32* %f4
  %v6 = load i32, i32* %maxX_addr
  %p7 = icmp slt i32 %v5, %v6
  br i1 %p7, label %then0, label %merge2
then0:
  %f8 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 3
  %v9 = load i32, i32* %f8
  %c10 = add i32 0, 1
  %t11 = add i32 %v9, %c10
  %f12 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 3
  store i32 %t11, i32* %f12
  br label %merge2
merge2:
  ret void
}
define private void @Invaders_updateBullets(%struct.Invaders* %self) {
entry:
  %f0 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 6
  %v1 = load i64, i64* %f0
  %c2 = call i32 @RtPtrArray_len(i64 %v1)
  %c3 = add i32 0, 0
  %idx_addr = alloca i32
  store i32 %c3, i32* %idx_addr
  br label %for_cond0
for_cond0:
  %v4 = load i32, i32* %idx_addr
  %p5 = icmp slt i32 %v4, %c2
  br i1 %p5, label %for_body1, label %for_exit2
for_body1:
  %c6 = call i64 @RtPtrArray_get(i64 %v1, i32 %v4)
  %bullet_addr = alloca i64
  store i64 %c6, i64* %bullet_addr
  %v7 = load i64, i64* %bullet_addr
  %p8 = inttoptr i64 %v7 to %struct.Bullet*
  %f9 = getelementptr %struct.Bullet, %struct.Bullet* %p8, i32 0, i32 4
  %v10 = load i32, i32* %f9
  %c11 = add i32 0, 0
  %p12 = icmp ne i32 %v10, %c11
  br i1 %p12, label %then4, label %merge6
then4:
  %v13 = load i64, i64* %bullet_addr
  %p14 = inttoptr i64 %v13 to %struct.Bullet*
  %f15 = getelementptr %struct.Bullet, %struct.Bullet* %p14, i32 0, i32 1
  %v16 = load i32, i32* %f15
  %c17 = add i32 0, 1
  %t18 = sub i32 %v16, %c17
  %v19 = load i64, i64* %bullet_addr
  %p20 = inttoptr i64 %v19 to %struct.Bullet*
  %f21 = getelementptr %struct.Bullet, %struct.Bullet* %p20, i32 0, i32 1
  store i32 %t18, i32* %f21
  %v22 = load i64, i64* %bullet_addr
  %p23 = inttoptr i64 %v22 to %struct.Bullet*
  %f24 = getelementptr %struct.Bullet, %struct.Bullet* %p23, i32 0, i32 1
  %v25 = load i32, i32* %f24
  %c26 = add i32 0, 1
  %p27 = icmp slt i32 %v25, %c26
  br i1 %p27, label %then7, label %merge9
then7:
  %c28 = icmp eq i32 0, 1
  %v29 = load i64, i64* %bullet_addr
  %p30 = inttoptr i64 %v29 to %struct.Bullet*
  %f31 = getelementptr %struct.Bullet, %struct.Bullet* %p30, i32 0, i32 4
  %z32 = zext i1 %c28 to i32
  store i32 %z32, i32* %f31
  br label %merge9
merge9:
  br label %merge6
merge6:
  br label %for_inc3
for_inc3:
  %v33 = load i32, i32* %idx_addr
  %c34 = add i32 0, 1
  %t35 = add i32 %v33, %c34
  store i32 %t35, i32* %idx_addr
  br label %for_cond0
for_exit2:
  ret void
}
define private i32 @Invaders_countAlive(%struct.Invaders* %self) {
entry:
  %c0 = add i32 0, 0
  %count_addr = alloca i32
  store i32 %c0, i32* %count_addr
  %f1 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 5
  %v2 = load i64, i64* %f1
  %c3 = call i32 @RtPtrArray_len(i64 %v2)
  %c4 = add i32 0, 0
  %idx_addr = alloca i32
  store i32 %c4, i32* %idx_addr
  br label %for_cond0
for_cond0:
  %v5 = load i32, i32* %idx_addr
  %p6 = icmp slt i32 %v5, %c3
  br i1 %p6, label %for_body1, label %for_exit2
for_body1:
  %c7 = call i64 @RtPtrArray_get(i64 %v2, i32 %v5)
  %a_addr = alloca i64
  store i64 %c7, i64* %a_addr
  %v8 = load i64, i64* %a_addr
  %p9 = inttoptr i64 %v8 to %struct.Alien*
  %f10 = getelementptr %struct.Alien, %struct.Alien* %p9, i32 0, i32 4
  %v11 = load i32, i32* %f10
  %c12 = add i32 0, 0
  %p13 = icmp ne i32 %v11, %c12
  br i1 %p13, label %then4, label %merge6
then4:
  %v14 = load i32, i32* %count_addr
  %c15 = add i32 0, 1
  %t16 = add i32 %v14, %c15
  store i32 %t16, i32* %count_addr
  br label %merge6
merge6:
  br label %for_inc3
for_inc3:
  %v17 = load i32, i32* %idx_addr
  %c18 = add i32 0, 1
  %t19 = add i32 %v17, %c18
  store i32 %t19, i32* %idx_addr
  br label %for_cond0
for_exit2:
  %v20 = load i32, i32* %count_addr
  ret i32 %v20
}
define private void @Invaders_updateAliens(%struct.Invaders* %self) {
entry:
  %f0 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 12
  %v1 = load i32, i32* %f0
  %f2 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 13
  %v3 = load i32, i32* %f2
  %t4 = srem i32 %v1, %v3
  %moveFrame_addr = alloca i32
  store i32 %t4, i32* %moveFrame_addr
  %v5 = load i32, i32* %moveFrame_addr
  %c6 = add i32 0, 0
  %p7 = icmp ne i32 %v5, %c6
  br i1 %p7, label %then0, label %merge2
then0:
  ret void
merge2:
  %c8 = icmp eq i32 0, 1
  %shouldMoveDown_addr = alloca i1
  store i1 %c8, i1* %shouldMoveDown_addr
  %c9 = add i32 0, 999
  %minX_addr = alloca i32
  store i32 %c9, i32* %minX_addr
  %c10 = add i32 0, 0
  %maxX_addr = alloca i32
  store i32 %c10, i32* %maxX_addr
  %f11 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 5
  %v12 = load i64, i64* %f11
  %c13 = call i32 @RtPtrArray_len(i64 %v12)
  %c14 = add i32 0, 0
  %idx_addr = alloca i32
  store i32 %c14, i32* %idx_addr
  br label %for_cond3
for_cond3:
  %v15 = load i32, i32* %idx_addr
  %p16 = icmp slt i32 %v15, %c13
  br i1 %p16, label %for_body4, label %for_exit5
for_body4:
  %c17 = call i64 @RtPtrArray_get(i64 %v12, i32 %v15)
  %alien_addr = alloca i64
  store i64 %c17, i64* %alien_addr
  %v18 = load i64, i64* %alien_addr
  %p19 = inttoptr i64 %v18 to %struct.Alien*
  %f20 = getelementptr %struct.Alien, %struct.Alien* %p19, i32 0, i32 4
  %v21 = load i32, i32* %f20
  %c22 = add i32 0, 0
  %p23 = icmp ne i32 %v21, %c22
  br i1 %p23, label %then7, label %merge9
then7:
  %v24 = load i64, i64* %alien_addr
  %p25 = inttoptr i64 %v24 to %struct.Alien*
  %f26 = getelementptr %struct.Alien, %struct.Alien* %p25, i32 0, i32 0
  %v27 = load i32, i32* %f26
  %v28 = load i32, i32* %minX_addr
  %p29 = icmp slt i32 %v27, %v28
  br i1 %p29, label %then10, label %merge12
then10:
  %v30 = load i64, i64* %alien_addr
  %p31 = inttoptr i64 %v30 to %struct.Alien*
  %f32 = getelementptr %struct.Alien, %struct.Alien* %p31, i32 0, i32 0
  %v33 = load i32, i32* %f32
  store i32 %v33, i32* %minX_addr
  br label %merge12
merge12:
  %v34 = load i64, i64* %alien_addr
  %p35 = inttoptr i64 %v34 to %struct.Alien*
  %f36 = getelementptr %struct.Alien, %struct.Alien* %p35, i32 0, i32 0
  %v37 = load i32, i32* %f36
  %v38 = load i32, i32* %maxX_addr
  %p39 = icmp sgt i32 %v37, %v38
  br i1 %p39, label %then13, label %merge15
then13:
  %v40 = load i64, i64* %alien_addr
  %p41 = inttoptr i64 %v40 to %struct.Alien*
  %f42 = getelementptr %struct.Alien, %struct.Alien* %p41, i32 0, i32 0
  %v43 = load i32, i32* %f42
  store i32 %v43, i32* %maxX_addr
  br label %merge15
merge15:
  br label %merge9
merge9:
  br label %for_inc6
for_inc6:
  %v44 = load i32, i32* %idx_addr
  %c45 = add i32 0, 1
  %t46 = add i32 %v44, %c45
  store i32 %t46, i32* %idx_addr
  br label %for_cond3
for_exit5:
  %f47 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 0
  %v48 = load i32, i32* %f47
  %c49 = add i32 0, 2
  %t50 = sub i32 %v48, %c49
  %rightBound_addr = alloca i32
  store i32 %t50, i32* %rightBound_addr
  %f51 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 11
  %v52 = load i32, i32* %f51
  %c53 = add i32 0, 0
  %p54 = icmp sgt i32 %v52, %c53
  br i1 %p54, label %then16, label %else17
then16:
  %v55 = load i32, i32* %maxX_addr
  %v56 = load i32, i32* %rightBound_addr
  %p57 = icmp sge i32 %v55, %v56
  br i1 %p57, label %then19, label %merge21
then19:
  %c58 = add i32 0, -1
  %f59 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 11
  store i32 %c58, i32* %f59
  %c60 = icmp ne i32 1, 0
  store i1 %c60, i1* %shouldMoveDown_addr
  br label %merge21
merge21:
  br label %merge18
else17:
  %v61 = load i32, i32* %minX_addr
  %c62 = add i32 0, 1
  %p63 = icmp sle i32 %v61, %c62
  br i1 %p63, label %then22, label %merge24
then22:
  %c64 = add i32 0, 1
  %f65 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 11
  store i32 %c64, i32* %f65
  %c66 = icmp ne i32 1, 0
  store i1 %c66, i1* %shouldMoveDown_addr
  br label %merge24
merge24:
  br label %merge18
merge18:
  %f67 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 5
  %v68 = load i64, i64* %f67
  %c69 = call i32 @RtPtrArray_len(i64 %v68)
  %c70 = add i32 0, 0
  %idx2_addr = alloca i32
  store i32 %c70, i32* %idx2_addr
  br label %for_cond25
for_cond25:
  %v71 = load i32, i32* %idx2_addr
  %p72 = icmp slt i32 %v71, %c69
  br i1 %p72, label %for_body26, label %for_exit27
for_body26:
  %c73 = call i64 @RtPtrArray_get(i64 %v68, i32 %v71)
  store i64 %c73, i64* %alien_addr
  %v74 = load i64, i64* %alien_addr
  %p75 = inttoptr i64 %v74 to %struct.Alien*
  %f76 = getelementptr %struct.Alien, %struct.Alien* %p75, i32 0, i32 4
  %v77 = load i32, i32* %f76
  %c78 = add i32 0, 0
  %p79 = icmp ne i32 %v77, %c78
  br i1 %p79, label %then29, label %merge31
then29:
  %v80 = load i64, i64* %alien_addr
  %p81 = inttoptr i64 %v80 to %struct.Alien*
  %f82 = getelementptr %struct.Alien, %struct.Alien* %p81, i32 0, i32 0
  %v83 = load i32, i32* %f82
  %f84 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 11
  %v85 = load i32, i32* %f84
  %t86 = add i32 %v83, %v85
  %v87 = load i64, i64* %alien_addr
  %p88 = inttoptr i64 %v87 to %struct.Alien*
  %f89 = getelementptr %struct.Alien, %struct.Alien* %p88, i32 0, i32 0
  store i32 %t86, i32* %f89
  %v90 = load i1, i1* %shouldMoveDown_addr
  br i1 %v90, label %then32, label %merge34
then32:
  %v91 = load i64, i64* %alien_addr
  %p92 = inttoptr i64 %v91 to %struct.Alien*
  %f93 = getelementptr %struct.Alien, %struct.Alien* %p92, i32 0, i32 1
  %v94 = load i32, i32* %f93
  %c95 = add i32 0, 1
  %t96 = add i32 %v94, %c95
  %v97 = load i64, i64* %alien_addr
  %p98 = inttoptr i64 %v97 to %struct.Alien*
  %f99 = getelementptr %struct.Alien, %struct.Alien* %p98, i32 0, i32 1
  store i32 %t96, i32* %f99
  %v100 = load i64, i64* %alien_addr
  %p101 = inttoptr i64 %v100 to %struct.Alien*
  %f102 = getelementptr %struct.Alien, %struct.Alien* %p101, i32 0, i32 1
  %v103 = load i32, i32* %f102
  %f104 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 2
  %v105 = load i32, i32* %f104
  %p106 = icmp sge i32 %v103, %v105
  br i1 %p106, label %then35, label %merge37
then35:
  %c107 = icmp ne i32 1, 0
  %z108 = zext i1 %c107 to i32
  %f109 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 9
  store i32 %z108, i32* %f109
  br label %merge37
merge37:
  br label %merge34
merge34:
  br label %merge31
merge31:
  br label %for_inc28
for_inc28:
  %v110 = load i32, i32* %idx2_addr
  %c111 = add i32 0, 1
  %t112 = add i32 %v110, %c111
  store i32 %t112, i32* %idx2_addr
  br label %for_cond25
for_exit27:
  %c113 = call i32 @Invaders_countAlive(%struct.Invaders* %self)
  %aliveCount_addr = alloca i32
  store i32 %c113, i32* %aliveCount_addr
  %v114 = load i32, i32* %aliveCount_addr
  %c115 = add i32 0, 12
  %p116 = icmp slt i32 %v114, %c115
  br i1 %p116, label %then38, label %merge40
then38:
  %c117 = add i32 0, 5
  %f118 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 13
  store i32 %c117, i32* %f118
  br label %merge40
merge40:
  %v119 = load i32, i32* %aliveCount_addr
  %c120 = add i32 0, 6
  %p121 = icmp slt i32 %v119, %c120
  br i1 %p121, label %then41, label %merge43
then41:
  %c122 = add i32 0, 3
  %f123 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 13
  store i32 %c122, i32* %f123
  br label %merge43
merge43:
  %v124 = load i32, i32* %aliveCount_addr
  %c125 = add i32 0, 3
  %p126 = icmp slt i32 %v124, %c125
  br i1 %p126, label %then44, label %merge46
then44:
  %c127 = add i32 0, 1
  %f128 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 13
  store i32 %c127, i32* %f128
  br label %merge46
merge46:
  ret void
}
define private void @Invaders_checkCollisions(%struct.Invaders* %self) {
entry:
  %f0 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 6
  %v1 = load i64, i64* %f0
  %c2 = call i32 @RtPtrArray_len(i64 %v1)
  %c3 = add i32 0, 0
  %bidx_addr = alloca i32
  store i32 %c3, i32* %bidx_addr
  br label %for_cond0
for_cond0:
  %v4 = load i32, i32* %bidx_addr
  %p5 = icmp slt i32 %v4, %c2
  br i1 %p5, label %for_body1, label %for_exit2
for_body1:
  %c6 = call i64 @RtPtrArray_get(i64 %v1, i32 %v4)
  %bullet_addr = alloca i64
  store i64 %c6, i64* %bullet_addr
  %v7 = load i64, i64* %bullet_addr
  %p8 = inttoptr i64 %v7 to %struct.Bullet*
  %f9 = getelementptr %struct.Bullet, %struct.Bullet* %p8, i32 0, i32 4
  %v10 = load i32, i32* %f9
  %c11 = add i32 0, 0
  %p12 = icmp ne i32 %v10, %c11
  br i1 %p12, label %then4, label %merge6
then4:
  %f13 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 5
  %v14 = load i64, i64* %f13
  %c15 = call i32 @RtPtrArray_len(i64 %v14)
  %c16 = add i32 0, 0
  %aidx_addr = alloca i32
  store i32 %c16, i32* %aidx_addr
  br label %for_cond7
for_cond7:
  %v17 = load i32, i32* %aidx_addr
  %p18 = icmp slt i32 %v17, %c15
  br i1 %p18, label %for_body8, label %for_exit9
for_body8:
  %c19 = call i64 @RtPtrArray_get(i64 %v14, i32 %v17)
  %alien_addr = alloca i64
  store i64 %c19, i64* %alien_addr
  %v20 = load i64, i64* %alien_addr
  %p21 = inttoptr i64 %v20 to %struct.Alien*
  %f22 = getelementptr %struct.Alien, %struct.Alien* %p21, i32 0, i32 4
  %v23 = load i32, i32* %f22
  %c24 = add i32 0, 0
  %p25 = icmp ne i32 %v23, %c24
  br i1 %p25, label %then11, label %merge13
then11:
  %v26 = load i64, i64* %bullet_addr
  %p27 = inttoptr i64 %v26 to %struct.Bullet*
  %f28 = getelementptr %struct.Bullet, %struct.Bullet* %p27, i32 0, i32 0
  %v29 = load i32, i32* %f28
  %v30 = load i64, i64* %alien_addr
  %p31 = inttoptr i64 %v30 to %struct.Alien*
  %f32 = getelementptr %struct.Alien, %struct.Alien* %p31, i32 0, i32 0
  %v33 = load i32, i32* %f32
  %p34 = icmp eq i32 %v29, %v33
  br i1 %p34, label %then14, label %merge16
then14:
  %v35 = load i64, i64* %bullet_addr
  %p36 = inttoptr i64 %v35 to %struct.Bullet*
  %f37 = getelementptr %struct.Bullet, %struct.Bullet* %p36, i32 0, i32 1
  %v38 = load i32, i32* %f37
  %v39 = load i64, i64* %alien_addr
  %p40 = inttoptr i64 %v39 to %struct.Alien*
  %f41 = getelementptr %struct.Alien, %struct.Alien* %p40, i32 0, i32 1
  %v42 = load i32, i32* %f41
  %p43 = icmp eq i32 %v38, %v42
  br i1 %p43, label %then17, label %merge19
then17:
  %c44 = icmp eq i32 0, 1
  %v45 = load i64, i64* %bullet_addr
  %p46 = inttoptr i64 %v45 to %struct.Bullet*
  %f47 = getelementptr %struct.Bullet, %struct.Bullet* %p46, i32 0, i32 4
  %z48 = zext i1 %c44 to i32
  store i32 %z48, i32* %f47
  %c49 = icmp eq i32 0, 1
  %v50 = load i64, i64* %alien_addr
  %p51 = inttoptr i64 %v50 to %struct.Alien*
  %f52 = getelementptr %struct.Alien, %struct.Alien* %p51, i32 0, i32 4
  %z53 = zext i1 %c49 to i32
  store i32 %z53, i32* %f52
  %f54 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 7
  %v55 = load i32, i32* %f54
  %c56 = add i32 0, 10
  %t57 = add i32 %v55, %c56
  %f58 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 7
  store i32 %t57, i32* %f58
  br label %merge19
merge19:
  br label %merge16
merge16:
  br label %merge13
merge13:
  br label %for_inc10
for_inc10:
  %v59 = load i32, i32* %aidx_addr
  %c60 = add i32 0, 1
  %t61 = add i32 %v59, %c60
  store i32 %t61, i32* %aidx_addr
  br label %for_cond7
for_exit9:
  br label %merge6
merge6:
  br label %for_inc3
for_inc3:
  %v62 = load i32, i32* %bidx_addr
  %c63 = add i32 0, 1
  %t64 = add i32 %v62, %c63
  store i32 %t64, i32* %bidx_addr
  br label %for_cond0
for_exit2:
  ret void
}
define private void @Invaders_checkWin(%struct.Invaders* %self) {
entry:
  %c0 = call i32 @Invaders_countAlive(%struct.Invaders* %self)
  %aliveCount_addr = alloca i32
  store i32 %c0, i32* %aliveCount_addr
  %v1 = load i32, i32* %aliveCount_addr
  %c2 = add i32 0, 0
  %p3 = icmp eq i32 %v1, %c2
  br i1 %p3, label %then0, label %merge2
then0:
  %c4 = icmp ne i32 1, 0
  %z5 = zext i1 %c4 to i32
  %f6 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 10
  store i32 %z5, i32* %f6
  %c7 = icmp ne i32 1, 0
  %z8 = zext i1 %c7 to i32
  %f9 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 9
  store i32 %z8, i32* %f9
  br label %merge2
merge2:
  ret void
}
define private void @Invaders_update(%struct.Invaders* %self) {
entry:
  %f0 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 12
  %v1 = load i32, i32* %f0
  %c2 = add i32 0, 1
  %t3 = add i32 %v1, %c2
  %f4 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 12
  store i32 %t3, i32* %f4
  call void @Invaders_updateBullets(%struct.Invaders* %self)
  call void @Invaders_updateAliens(%struct.Invaders* %self)
  call void @Invaders_checkCollisions(%struct.Invaders* %self)
  call void @Invaders_checkWin(%struct.Invaders* %self)
  ret void
}
define private void @Invaders_endGame(%struct.Invaders* %self) {
entry:
  call void @ranger_clear_screen()
  %c0 = add i32 0, 1
  %c1 = add i32 0, 1
  call void @ranger_move_cursor(i32 %c0, i32 %c1)
  %f2 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 10
  %v3 = load i32, i32* %f2
  %c4 = add i32 0, 0
  %p5 = icmp ne i32 %v3, %c4
  br i1 %p5, label %then0, label %else1
then0:
  %s6 = getelementptr inbounds [18 x i8], [18 x i8]* @.str.16, i64 0, i64 0
  %c7 = call i32 @printf(i8* %s6)
  br label %merge2
else1:
  %s8 = getelementptr inbounds [19 x i8], [19 x i8]* @.str.17, i64 0, i64 0
  %c9 = call i32 @printf(i8* %s8)
  br label %merge2
merge2:
  %c10 = add i64 0, 64
  %c11 = call i64 @malloc(i64 %c10)
  %s12 = inttoptr i64 %c11 to i8*
  %s13 = getelementptr inbounds [5 x i8], [5 x i8]* @.str.18, i64 0, i64 0
  %s14 = getelementptr inbounds [14 x i8], [14 x i8]* @.str.19, i64 0, i64 0
  %f15 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 7
  %v16 = load i32, i32* %f15
  %c17 = call i32 @sprintf(i8* %s12, i8* %s13, i8* %s14, i32 %v16)
  %finalMsg_addr = alloca i8*
  store i8* %s12, i8** %finalMsg_addr
  call void @ranger_show_cursor()
  ret void
}
define private void @Invaders_gameLoop(%struct.Invaders* %self) {
entry:
  br label %while_cond0
while_cond0:
  %f0 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 9
  %v1 = load i32, i32* %f0
  %c2 = icmp eq i32 0, 1
  %z3 = zext i1 %c2 to i32
  %p4 = icmp eq i32 %v1, %z3
  br i1 %p4, label %while_body1, label %while_exit2
while_body1:
  call void @Invaders_savePrevState(%struct.Invaders* %self)
  call void @Invaders_update(%struct.Invaders* %self)
  call void @Invaders_render(%struct.Invaders* %self)
  %c5 = call i8* @ranger_poll_key()
  %key_addr = alloca i8*
  store i8* %c5, i8** %key_addr
  %v6 = load i8*, i8** %key_addr
  %s7 = getelementptr inbounds [1 x i8], [1 x i8]* @.str.6, i64 0, i64 0
  %c8 = call i32 @strcmp(i8* %v6, i8* %s7)
  %c9 = add i32 0, 0
  %p10 = icmp ne i32 %c8, %c9
  br i1 %p10, label %then3, label %merge5
then3:
  %v11 = load i8*, i8** %key_addr
  call void @Invaders_handleKey(%struct.Invaders* %self, i8* %v11)
  br label %merge5
merge5:
  %c12 = add i32 0, 50
  %c13 = add i32 0, 1000
  %t14 = mul i32 %c12, %c13
  %c15 = call i32 @usleep(i32 %t14)
  br label %while_cond0
while_exit2:
  call void @Invaders_endGame(%struct.Invaders* %self)
  ret void
}
define private void @Invaders_handleKey(%struct.Invaders* %self, i8* %key) {
entry:
  %key_addr = alloca i8*
  store i8* %key, i8** %key_addr
  %v0 = load i8*, i8** %key_addr
  %s1 = getelementptr inbounds [5 x i8], [5 x i8]* @.str.20, i64 0, i64 0
  %c2 = call i32 @strcmp(i8* %v0, i8* %s1)
  %c3 = add i32 0, 0
  %p4 = icmp eq i32 %c2, %c3
  br i1 %p4, label %then0, label %merge2
then0:
  call void @Invaders_moveLeft(%struct.Invaders* %self)
  br label %merge2
merge2:
  %v5 = load i8*, i8** %key_addr
  %s6 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.21, i64 0, i64 0
  %c7 = call i32 @strcmp(i8* %v5, i8* %s6)
  %c8 = add i32 0, 0
  %p9 = icmp eq i32 %c7, %c8
  br i1 %p9, label %then3, label %merge5
then3:
  call void @Invaders_moveRight(%struct.Invaders* %self)
  br label %merge5
merge5:
  %v10 = load i8*, i8** %key_addr
  %s11 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.22, i64 0, i64 0
  %c12 = call i32 @strcmp(i8* %v10, i8* %s11)
  %c13 = add i32 0, 0
  %p14 = icmp eq i32 %c12, %c13
  br i1 %p14, label %then6, label %merge8
then6:
  call void @Invaders_moveLeft(%struct.Invaders* %self)
  br label %merge8
merge8:
  %v15 = load i8*, i8** %key_addr
  %s16 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.12, i64 0, i64 0
  %c17 = call i32 @strcmp(i8* %v15, i8* %s16)
  %c18 = add i32 0, 0
  %p19 = icmp eq i32 %c17, %c18
  br i1 %p19, label %then9, label %merge11
then9:
  call void @Invaders_moveLeft(%struct.Invaders* %self)
  br label %merge11
merge11:
  %v20 = load i8*, i8** %key_addr
  %s21 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.23, i64 0, i64 0
  %c22 = call i32 @strcmp(i8* %v20, i8* %s21)
  %c23 = add i32 0, 0
  %p24 = icmp eq i32 %c22, %c23
  br i1 %p24, label %then12, label %merge14
then12:
  call void @Invaders_moveRight(%struct.Invaders* %self)
  br label %merge14
merge14:
  %v25 = load i8*, i8** %key_addr
  %s26 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.24, i64 0, i64 0
  %c27 = call i32 @strcmp(i8* %v25, i8* %s26)
  %c28 = add i32 0, 0
  %p29 = icmp eq i32 %c27, %c28
  br i1 %p29, label %then15, label %merge17
then15:
  call void @Invaders_moveRight(%struct.Invaders* %self)
  br label %merge17
merge17:
  %v30 = load i8*, i8** %key_addr
  %s31 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.8, i64 0, i64 0
  %c32 = call i32 @strcmp(i8* %v30, i8* %s31)
  %c33 = add i32 0, 0
  %p34 = icmp eq i32 %c32, %c33
  br i1 %p34, label %then18, label %merge20
then18:
  call void @Invaders_shoot(%struct.Invaders* %self)
  br label %merge20
merge20:
  %v35 = load i8*, i8** %key_addr
  %s36 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.25, i64 0, i64 0
  %c37 = call i32 @strcmp(i8* %v35, i8* %s36)
  %c38 = add i32 0, 0
  %p39 = icmp eq i32 %c37, %c38
  br i1 %p39, label %then21, label %merge23
then21:
  call void @Invaders_shoot(%struct.Invaders* %self)
  br label %merge23
merge23:
  %v40 = load i8*, i8** %key_addr
  %s41 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.26, i64 0, i64 0
  %c42 = call i32 @strcmp(i8* %v40, i8* %s41)
  %c43 = add i32 0, 0
  %p44 = icmp eq i32 %c42, %c43
  br i1 %p44, label %then24, label %merge26
then24:
  %c45 = icmp ne i32 1, 0
  %z46 = zext i1 %c45 to i32
  %f47 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 9
  store i32 %z46, i32* %f47
  br label %merge26
merge26:
  %v48 = load i8*, i8** %key_addr
  %s49 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.27, i64 0, i64 0
  %c50 = call i32 @strcmp(i8* %v48, i8* %s49)
  %c51 = add i32 0, 0
  %p52 = icmp eq i32 %c50, %c51
  br i1 %p52, label %then27, label %merge29
then27:
  %c53 = icmp ne i32 1, 0
  %z54 = zext i1 %c53 to i32
  %f55 = getelementptr %struct.Invaders, %struct.Invaders* %self, i32 0, i32 9
  store i32 %z54, i32* %f55
  br label %merge29
merge29:
  ret void
}
define private i64 @RtPtrArray_new(i32 %cap) {
entry:
  %c0 = add i64 0, 16
  %c1 = call i64 @malloc(i64 %c0)
  %c2 = add i64 0, 8
  %z3 = zext i32 %cap to i64
  %t4 = mul i64 %z3, %c2
  %c5 = call i64 @malloc(i64 %t4)
  %c6 = add i64 0, 0
  %c1_p = inttoptr i64 %c1 to i64*
  store i64 %c5, i64* %c1_p
  %c7 = add i32 0, 0
  %c8 = add i64 0, 8
  %t9 = add i64 %c1, %c8
  %t9_p = inttoptr i64 %t9 to i32*
  store i32 %c7, i32* %t9_p
  %c10 = add i64 0, 12
  %t11 = add i64 %c1, %c10
  %t11_p = inttoptr i64 %t11 to i32*
  store i32 %cap, i32* %t11_p
  ret i64 %c1
}
define private void @RtPtrArray_push(i64 %desc, i64 %val) {
entry:
  %c0 = add i64 0, 8
  %t1 = add i64 %desc, %c0
  %m2_p = inttoptr i64 %t1 to i32*
  %m2 = load i32, i32* %m2_p
  %c3 = add i64 0, 12
  %t4 = add i64 %desc, %c3
  %m5_p = inttoptr i64 %t4 to i32*
  %m5 = load i32, i32* %m5_p
  %p6 = icmp sge i32 %m2, %m5
  br i1 %p6, label %ptr_done0, label %ptr_cont1
ptr_cont1:
  %m7_p = inttoptr i64 %desc to i64*
  %m7 = load i64, i64* %m7_p
  %c8 = add i32 0, 8
  %t9 = mul i32 %m2, %c8
  %z10 = zext i32 %t9 to i64
  %t11 = add i64 %m7, %z10
  %t11_p = inttoptr i64 %t11 to i64*
  store i64 %val, i64* %t11_p
  %c12 = add i32 0, 1
  %t13 = add i32 %m2, %c12
  %c14 = add i64 0, 8
  %t15 = add i64 %desc, %c14
  %t15_p = inttoptr i64 %t15 to i32*
  store i32 %t13, i32* %t15_p
  br label %ptr_done0
ptr_done0:
  ret void
}
define private i64 @RtPtrArray_get(i64 %desc, i32 %idx) {
entry:
  %m0_p = inttoptr i64 %desc to i64*
  %m0 = load i64, i64* %m0_p
  %c1 = add i32 0, 8
  %t2 = mul i32 %idx, %c1
  %z3 = zext i32 %t2 to i64
  %t4 = add i64 %m0, %z3
  %m5_p = inttoptr i64 %t4 to i64*
  %m5 = load i64, i64* %m5_p
  ret i64 %m5
}
define private i32 @RtPtrArray_len(i64 %desc) {
entry:
  %c0 = add i64 0, 8
  %t1 = add i64 %desc, %c0
  %m2_p = inttoptr i64 %t1 to i32*
  %m2 = load i32, i32* %m2_p
  ret i32 %m2
}
