//! rust_sprite_char — a WASM guest that drives the ready character set over the
//! RGSP1 sprite ABI. It owns the whole little game (character-select menu + play)
//! and ships NO art: it picks characters from the host catalog by numeric id, the
//! same way a guest plays a sound by RG_WASM_SOUND_*.
//!
//! The ABI plumbing (block layout, exports, input edges) lives in the shared
//! `ranger_game` crate (gallery/game_engine/lib/ranger_game) — this file is only
//! the game: a small state struct + one tick function. The exports the host
//! calls (sprite_ptr / sprite_size / sprite_init / sprite_tick / rg_abi_version)
//! are generated by `ranger_game::sprite_game!` at the bottom.

use ranger_game::input::Buttons;
use ranger_game::sprite::{Anim, Dir, Frame, Mode, Scene, Slot, SpriteGame};

/// Characters shown in the select menu (catalog ids 1..=4 of the ready set).
const CHAR_COUNT: i32 = 4;
/// One character cell is 64 px; positions place the cell's top-left.
const CELL: i32 = 64;
/// The synthesised hop reverts to walk after this long.
const JUMP_MS: i32 = 500;
/// The menu confirm arms only after this much menu time AND an ACTION-up tick.
/// The host's setupScene ticks once with input=0 before the first real frame, so
/// a release-only check would arm on that synthetic tick while the launch button
/// is physically still held — the time floor absorbs it.
const MENU_ARM_MS: i32 = 250;

struct SpriteChar {
    mode: Mode,
    /// 0..3 highlighted character in the menu.
    cursor: i32,
    /// Committed character id.
    sel: i32,
    play_anim: Anim,
    play_dir: Dir,
    play_clock: i32,
    menu_clock: i32,
    /// Require ACTION to be released once before a menu confirm counts, so the
    /// button still held from launching the game doesn't instantly skip the menu.
    armed: bool,
}

impl SpriteChar {
    fn tick_menu(&mut self, f: &Frame, s: &mut Scene) {
        self.menu_clock += f.dt_ms;
        // Arm the confirm only once ACTION has been seen released after the
        // arming grace (ignores the button still held from launching the game
        // and the host's synthetic input=0 setup tick).
        if self.menu_clock >= MENU_ARM_MS && !f.input.held(Buttons::ACTION) {
            self.armed = true;
        }
        if f.input.pressed(Buttons::LEFT) {
            self.cursor = (self.cursor + CHAR_COUNT - 1) % CHAR_COUNT;
        }
        if f.input.pressed(Buttons::RIGHT) {
            self.cursor = (self.cursor + 1) % CHAR_COUNT;
        }
        if self.armed && f.input.pressed(Buttons::ACTION) {
            self.mode = Mode::Play;
            self.sel = self.cursor + 1;
            self.play_anim = Anim::Walk;
            self.play_dir = Dir::Down;
            self.play_clock = 0;
            // Show the picked character right away instead of a blank frame.
            self.render_play(f, s);
            return;
        }

        // Four characters in a row; the highlighted one walks in place + sits
        // higher.
        let base_y = f.view_h / 2 - CELL / 2;
        for i in 0..CHAR_COUNT {
            let x = f.view_w * (i + 1) / (CHAR_COUNT + 1) - CELL / 2;
            let slot = Slot::character(i + 1).at(x, base_y);
            if i == self.cursor {
                s.push(slot.at(x, base_y - 10).clock(self.menu_clock));
            } else {
                s.push(slot);
            }
        }
    }

    fn tick_play(&mut self, f: &Frame, s: &mut Scene) {
        // Back (host feeds BACK when the player presses Q/Esc in play) returns
        // to the character-select menu instead of quitting to the launcher.
        if f.input.pressed(Buttons::BACK) {
            self.mode = Mode::Menu;
            self.armed = false;
            self.tick_menu(f, s);
            return;
        }
        if self.play_anim == Anim::Jump {
            self.play_clock += f.dt_ms;
            if self.play_clock >= JUMP_MS {
                self.play_anim = Anim::Walk;
                self.play_clock = 0;
            }
        } else if f.input.pressed(Buttons::ACTION) {
            self.play_anim = Anim::Jump;
            self.play_clock = 0;
        } else {
            let mut moving = false;
            if f.input.held(Buttons::LEFT) {
                self.play_dir = Dir::Left;
                moving = true;
            }
            if f.input.held(Buttons::RIGHT) {
                self.play_dir = Dir::Right;
                moving = true;
            }
            if f.input.held(Buttons::UP) {
                self.play_dir = Dir::Up;
                moving = true;
            }
            if f.input.held(Buttons::DOWN) {
                self.play_dir = Dir::Down;
                moving = true;
            }
            if moving {
                self.play_clock += f.dt_ms;
            } else {
                self.play_clock = 0;
            }
        }
        self.render_play(f, s);
    }

    fn render_play(&self, f: &Frame, s: &mut Scene) {
        let x = f.view_w / 2 - CELL / 2;
        let y = f.view_h * 2 / 3 - CELL / 2;
        s.push(
            Slot::character(self.sel)
                .anim(self.play_anim)
                .dir(self.play_dir)
                .at(x, y)
                .clock(self.play_clock),
        );
    }
}

impl SpriteGame for SpriteChar {
    fn init() -> Self {
        SpriteChar {
            mode: Mode::Menu,
            cursor: 0,
            sel: 1,
            play_anim: Anim::Walk,
            play_dir: Dir::Down,
            play_clock: 0,
            menu_clock: 0,
            armed: false,
        }
    }

    fn tick(&mut self, f: &Frame, s: &mut Scene) {
        match self.mode {
            Mode::Menu => self.tick_menu(f, s),
            Mode::Play => self.tick_play(f, s),
        }
        s.set_mode(self.mode);
    }
}

ranger_game::sprite_game!(SpriteChar);
