#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The console page, assembled.
//
//   node gallery/firesim/demo/build.mjs                 # for `firesim:demo`
//   node gallery/firesim/demo/build.mjs --out DIR       # for the site
//
// NO BUNDLER. The compiled app is one self-contained CommonJS file — the
// Ranger sources import each other and the compiler flattens them — so
// turning it into an ES module is a wrapper and a re-export. The only other
// things the page loads are EVG's own browser helpers, which are already ES
// modules; they are COPIED beside the page rather than inlined, so the file
// the browser runs is the file in the repository.
//
// The consequence worth stating: this page has no build step that can go
// stale against the module it draws, and no `npm install` behind it. That is
// the same claim the simulator makes about itself.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MODULE = path.join(HERE, "..");
const GALLERY = path.join(MODULE, "..");

const argv = process.argv.slice(2);
const outFlag = argv.indexOf("--out");
const OUT = outFlag >= 0 ? path.resolve(argv[outFlag + 1]) : null;

const COMPILED = path.join(MODULE, "bin", "FiresimConsole.cjs");
if (!fs.existsSync(COMPILED)) {
  console.error("the console is not built — run `npm run firesim:demo:build` first");
  process.exit(3);
}

// --- the app, as an ES module -------------------------------------------------
const cjs = fs.readFileSync(COMPILED, "utf8");
const names = [...cjs.matchAll(/^module\.exports\.(\w+)\s*=/gm)].map((m) => m[1]);
if (!names.includes("FiresimConsole")) {
  console.error("the compiled module does not export FiresimConsole");
  process.exit(4);
}
// `require("fs")` appears inside the font loader, which the browser never
// reaches. Left as it is: it is an identifier that is never evaluated, and
// rewriting the compiler's output would make this file a second source of
// truth about what the app is.
const wrapped = `// Generated by gallery/firesim/demo/build.mjs — do not edit.
// SPDX-License-Identifier: AGPL-3.0-or-later
const module = { exports: {} };
{
${cjs}
}
const FiresimModule = module.exports;
export default FiresimModule;
export const { ${names.join(", ")} } = FiresimModule;
`;
fs.writeFileSync(path.join(HERE, "generated-host.js"), wrapped);

// --- the stylesheet and the rules, as strings ---------------------------------
// Neither is fetched. The page and the headless check have to style and parse
// exactly the same text, and a browser has no filesystem to read a fixture
// from anyway.
const css = fs.readFileSync(path.join(HERE, "firesim-console.css"), "utf8");
const rules = fs.readFileSync(path.join(MODULE, "fixtures", "console.rules"), "utf8");
fs.writeFileSync(
  path.join(HERE, "generated.js"),
  "// Generated by gallery/firesim/demo/build.mjs — do not edit.\n" +
    `export const CONSOLE_CSS = ${JSON.stringify(css)};\n` +
    `export const CONSOLE_RULES = ${JSON.stringify(rules)};\n`,
);

// --- EVG's browser helpers, copied beside the page ----------------------------
// Followed TRANSITIVELY from what `main.js` imports, so a helper that grows a
// new relative import does not silently stop being copied — which is a page
// that 404s in the browser and passes every check in Node.
const ENTRY_IMPORTS = ["evg/gl/evg-webgl.js", "evg/gl/evg-a11y.js", "evg/gl/evg-measure.js"];

function relativeImports(text) {
  const out = [];
  for (const m of text.matchAll(/(?:^|\s)(?:import|export)[^;]*?from\s*["'](\.[^"']+)["']/g)) out.push(m[1]);
  for (const m of text.matchAll(/import\s*\(\s*["'](\.[^"']+)["']\s*\)/g)) out.push(m[1]);
  return out;
}

// Every helper the page needs, as paths relative to `gallery/`.
function helperClosure() {
  const seen = new Set();
  const queue = [...ENTRY_IMPORTS];
  while (queue.length) {
    const rel = queue.shift();
    if (seen.has(rel)) continue;
    const from = path.join(GALLERY, rel);
    if (!fs.existsSync(from)) {
      console.error(`the page imports ${rel}, which is not in gallery/`);
      process.exit(4);
    }
    seen.add(rel);
    for (const next of relativeImports(fs.readFileSync(from, "utf8"))) {
      queue.push(path.posix.normalize(path.posix.join(path.posix.dirname(rel), next)));
    }
  }
  return [...seen];
}

const HELPERS = helperClosure();
function copyHelpers(root) {
  for (const rel of HELPERS) {
    const to = path.join(root, rel);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(path.join(GALLERY, rel), to);
  }
}
copyHelpers(HERE);

// And the page's own imports resolve where they are put. A page whose script
// 404s looks exactly like a page whose app threw.
function assertResolvable(root) {
  for (const name of ["main.js", "generated-host.js", "generated.js"]) {
    const file = path.join(root, name);
    for (const rel of relativeImports(fs.readFileSync(file, "utf8"))) {
      const target = path.join(path.dirname(file), rel);
      if (!fs.existsSync(target)) {
        console.error(`${name} imports ${rel}, which is not beside it in ${path.relative(process.cwd(), root)}`);
        process.exit(4);
      }
    }
  }
}
assertResolvable(HERE);

// --- the datasets the page can load -------------------------------------------
// `gallery/realtrainer`'s reference seed, as it stands, plus the rules that
// belong with it. Copied rather than embedded: 400 kB is not something the
// page should carry before anyone has asked for it.
const DATASETS = [
  [path.join(GALLERY, "realtrainer", "fixtures", "reference", "seed.json"), "realtrainer.json"],
  [path.join(MODULE, "fixtures", "realtrainer.rules"), "realtrainer.rules"],
];
function copyDatasets(root) {
  const dir = path.join(root, "datasets");
  fs.mkdirSync(dir, { recursive: true });
  for (const [from, name] of DATASETS) {
    if (!fs.existsSync(from)) {
      console.error(`the dataset ${path.relative(process.cwd(), from)} is missing`);
      process.exit(4);
    }
    fs.copyFileSync(from, path.join(dir, name));
  }
}
copyDatasets(HERE);

const written = ["generated-host.js", "generated.js", ...HELPERS, ...DATASETS.map((d) => `datasets/${d[1]}`)];

// --- the site copy ------------------------------------------------------------
if (OUT) {
  fs.mkdirSync(OUT, { recursive: true });
  for (const name of ["index.html", "main.js", "generated-host.js", "generated.js"]) {
    fs.copyFileSync(path.join(HERE, name), path.join(OUT, name));
  }
  copyHelpers(OUT);
  copyDatasets(OUT);
  assertResolvable(OUT);
  process.stdout.write(`  ${path.relative(process.cwd(), OUT)}  index.html + ${written.length} modules\n`);
} else {
  const kb = (wrapped.length / 1024).toFixed(0);
  process.stdout.write(`  gallery/firesim/demo  generated-host.js ${kb} kB, ${names.length} exports; EVG helpers copied\n`);
}
