/**
 * Bundle the menubar demo page.
 *
 * The stylesheet is generated into a module rather than fetched, so the page
 * and `npm run ui:menubar:png` style the tree from exactly the same text and
 * cannot drift. esbuild is resolved out of the conformance host's directory,
 * so there is one install for the playground, the gate and this.
 *
 * It asks for esbuild ALONE, via `requireHostTool`, and not for the reference
 * host `requireDom` demands. Everything bundled here is this repository's own
 * source: nothing on the page imports React or a Radix component. Demanding
 * the reference host as well made this exit 3 on any machine without it —
 * including CI, where the root install supplies esbuild and the host is never
 * installed, so `ui:demo:page` failed there while passing on a developer
 * machine that happened to have run `ui:conformance:install`.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { MissingDomDeps, requireHostTool } from "../conformance/dom-adapter.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const UI = path.join(HERE, "..");

function requireDom(name) {
  try {
    return requireHostTool(name);
  } catch (e) {
    console.error(e instanceof MissingDomDeps ? e.message : String(e));
    process.exit(3);
  }
}

const DEMOS = ["FilterDemo", "EventCalDemo", "MessageDemo", "ControlsDemo", "MenubarDemo", "ToolbarDemo", "SortableDemo", "MotionDemo", "TableDemo", "DropdownDemo", "DialogDemo", "TreeDemo", "TimelineDemo", "ResizeDemo", "FormDemo", "ProfileDemo", "DashboardDemo", "CalendarDemo"];
for (const name of DEMOS) {
  if (!fs.existsSync(path.join(UI, "bin", name + ".cjs"))) {
    console.error(`compiled ${name} missing — run \`npm run ui:demo:build\` first`);
    process.exit(3);
  }
}

// One-line re-exports, so the page imports paths that are the same in the
// bundle and in the editor rather than reaching into ../bin.
fs.writeFileSync(
  path.join(HERE, "generated-host.js"),
  "// Generated by demo/build.mjs — do not edit.\n" +
    'export { MenubarDemo } from "../bin/MenubarDemo.cjs";\n' +
    'export { ToolbarDemo } from "../bin/ToolbarDemo.cjs";\n' +
    'export { SortableDemo } from "../bin/SortableDemo.cjs";\n' +
    'export { MotionDemo } from "../bin/MotionDemo.cjs";\n' +
    'export { TableDemo } from "../bin/TableDemo.cjs";\n' +
    'export { DropdownDemo } from "../bin/DropdownDemo.cjs";\n' +
    'export { DialogDemo } from "../bin/DialogDemo.cjs";\n' +
    'export { TreeDemo } from "../bin/TreeDemo.cjs";\n' +
    'export { TimelineDemo } from "../bin/TimelineDemo.cjs";\n' +
    'export { ResizeDemo } from "../bin/ResizeDemo.cjs";\n' +
    'export { FormDemo } from "../bin/FormDemo.cjs";\n' +
    'export { ProfileDemo } from "../bin/ProfileDemo.cjs";\n' +
    'export { DashboardDemo } from "../bin/DashboardDemo.cjs";\n' +
    'export { CalendarDemo } from "../bin/CalendarDemo.cjs";\n' +
    'export { FilterDemo } from "../bin/FilterDemo.cjs";\n' +
    'export { EventCalDemo } from "../bin/EventCalDemo.cjs";\n' +
    'export { MessageDemo } from "../bin/MessageDemo.cjs";\n' +
    'export { ControlsDemo } from "../bin/ControlsDemo.cjs";\n' +
    // The whole modules too, as a list: the browser's text measurer is
    // installed into every one of them (`gallery/evg/gl/evg-measure.js`),
    // because two copies of a class are two classes and each compiled demo
    // has its own `EVGDefaultMeasurer`.
    // (`export * as` makes no local binding, so the list below could not
    // name them; an import that is then re-exported does.)
    DEMOS.map((n) => `import * as ${n}Module from "../bin/${n}.cjs";\n`).join("") +
    `export { ${DEMOS.map((n) => n + "Module").join(", ")} };\n` +
    `export const MODULES = [${DEMOS.map((n) => n + "Module").join(", ")}];\n`,
);

const css = (f) => JSON.stringify(fs.readFileSync(path.join(HERE, f), "utf8"));
fs.writeFileSync(
  path.join(HERE, "generated.js"),
  "// Generated by demo/build.mjs — do not edit.\n" +
    `export const MENUBAR_CSS = ${css("menubar.css")};\n` +
    `export const TOOLBAR_CSS = ${css("toolbar.css")};\n` +
    `export const SORTABLE_CSS = ${css("sortable.css")};\n` +
    `export const MOTION_CSS = ${css("motion.css")};\n` +
    `export const TABLE_CSS = ${css("table.css")};\n` +
    `export const DROPDOWN_CSS = ${css("dropdown.css")};\n` +
    `export const DIALOG_CSS = ${css("dialog.css")};\n` +
    `export const TREE_CSS = ${css("tree.css")};\n` +
    `export const TIMELINE_CSS = ${css("timeline.css")};\n` +
    `export const RESIZE_CSS = ${css("resize.css")};\n` +
    `export const FORM_CSS = ${css("form.css")};\n` +
    `export const PROFILE_CSS = ${css("profile.css")};\n` +
    `export const DASHBOARD_CSS = ${css("dashboard.css")};\n` +
    `export const CALENDAR_CSS = ${css("calendar.css")};\n` +
    `export const FILTERS_CSS = ${css("filters.css")};\n` +
    `export const EVENTCAL_CSS = ${css("eventcal.css")};\n` +
    `export const MESSAGE_CSS = ${css("message.css")};\n` +
    `export const CONTROLS_CSS = ${css("controls.css")};\n`,
);

const esbuild = requireDom("esbuild");

// The dashboard's chart measures its own axis labels with `UITextRenderer`,
// which owns a `FontManager`, which looks for font FILES — one `existsSync`,
// and nothing else in the whole bundle touches the filesystem.
//
// A browser has no filesystem, so the honest answer to "is there a font file
// at this path" is NO, and that is exactly what this stub says. It is not a
// workaround for a dependency that should not be there: `hasFont` stays false
// and the renderer falls back to its estimating measurer, which is the same
// path the Node gate takes, because the gate registers no font directory
// either. If a real face is ever wanted in the browser it arrives as a fetch,
// not as a file, and this stub goes on telling the truth.
const noFilesystem = {
  name: "no-filesystem",
  setup(build) {
    build.onResolve({ filter: /^fs$/ }, () => ({ path: "fs", namespace: "stub-fs" }));
    build.onLoad({ filter: /.*/, namespace: "stub-fs" }, () => ({
      contents: "export const existsSync = () => false;\n" +
        "export const readFileSync = () => { throw new Error('no filesystem in the browser'); };\n" +
        "export const readdirSync = () => [];\n" +
        "export default { existsSync, readFileSync, readdirSync };\n",
      loader: "js",
    }));
  },
};

await esbuild.build({
  entryPoints: [path.join(HERE, "main.js")],
  bundle: true,
  format: "esm",
  outfile: path.join(HERE, "bundle.js"),
  plugins: [noFilesystem],
  logLevel: "info",
});
