//! Linear ABI autopeli logic (traffic AI + player controls).
//! Host runs GamePhysics; this module reads/writes the shared RGW1 block and
//! authors an RGU1 HUD.
//!
//! The ABI plumbing (block layouts, exports, input handling, impulse/event
//! cursors) lives in the shared `ranger_game` crate
//! (gallery/game_engine/lib/ranger_game) — this file is only the game: road /
//! oil / ramp / traffic data, driving + feedback rules, and the HUD content.
//! The exports the host calls (abi_base / init / update / declare_resources,
//! plus rg_ui_ptr / rg_ui_size / rg_ui_revision) are generated by
//! `ranger_game::world_game!` and `ranger_game::ui_exports!` at the bottom.
//!
//! GAME vs GAME ENGINE — reading guide
//! -----------------------------------
//! Two kinds of code live in this file, and the comments call them out:
//!
//!   * GAME (this car game): all the data and rules that are only true for
//!     autopeli — the track/oil/ramp/traffic tables, the driving + feedback
//!     physics tuning, the body id-code taxonomy, the HUD content, and the
//!     meaning we assign to each control/scalar/event channel.
//!
//!   * GAME ENGINE INTERFACE (the environment): every place we cross into the
//!     shared `ranger_game` crate — the `World`/`Frame`/`Input` handles, the
//!     `resources`/`ui` builders, the `WorldGame` trait we implement, and the
//!     `world_game!`/`ui_exports!` macros. These are the engine's generic
//!     transport; they carry our bytes but assign them no meaning.
//!
//! Convention used below: a line tagged `// [engine]` is a call across the
//! Game Engine interface (the `ranger_game` crate / the shared RGW1·RGU1
//! blocks). Everything NOT so tagged is this game's own logic. Section banners
//! (`// == GAME ... ==`) mark whole blocks that are purely the game.

mod hud;

// [engine] The only things this game imports are the Game Engine's generic
// transport types/helpers; nothing here knows the word "autopeli".
use ranger_game::input::{Buttons, Input};
use ranger_game::world::{event, World, WorldGame};
use ranger_game::{resources, FP};

// == GAME: constants, id-code taxonomy and channel conventions ==============
// Everything in this block is meaning THIS GAME invented. The Game Engine
// transports body ids, control channels, scalars, sounds and event sub-ids as
// opaque integers — the assignments here are ours alone.

const STEER_SCALE: i32 = 1000;

// Body id codes are this game's convention (the transport assigns no meaning):
// 0/1 players, 2..16 traffic, 100.. cones, 200.. bars, 1000/1001 walls.
pub const BODY_P1: i32 = 0;
pub const BODY_P2: i32 = 1;
pub const TRAFFIC_START: i32 = 2;
pub const TRAFFIC_COUNT: i32 = 15;
pub const BODY_COUNT: i32 = 2 + TRAFFIC_COUNT;
pub const ID_WALL_L: i32 = 1000;
pub const ID_WALL_R: i32 = 1001;

// Sound sub-ids index the palette declare_resources() registers.
pub const SND_WALL: i32 = 1;
pub const SND_BOUNCE: i32 = 2;
pub const SND_WIN: i32 = 3;

const CAR_MASS: i32 = 1200;
const CONE_MASS: i32 = 3;
const WIN_SCORE: i32 = 5000;
const FINISH_Y: i32 = 140;
const BRAKE_SCREECH_CD_MS: i32 = 900;
const BRAKE_SCREECH_MIN_SPD: i32 = 18;
const OIL_EFFECT_MS: i32 = 260;
const OIL_RECOVER_MS: i32 = 380;
const HIT_FLASH_MS: i32 = 260;

// == GAME: track data (guest-owned world; the host never re-hardcodes this) ==
// The road/oil/ramp/traffic tables ARE the car game. The Game Engine has no
// concept of a "road" — it only spawns the bodies we place from this data.

struct RoadPt {
    y: i32,
    x: i32,
    half: i32,
}

const ROAD: [RoadPt; 16] = [
    RoadPt {
        y: 6000,
        x: 240,
        half: 126,
    },
    RoadPt {
        y: 5600,
        x: 220,
        half: 104,
    },
    RoadPt {
        y: 5200,
        x: 200,
        half: 78,
    },
    RoadPt {
        y: 4800,
        x: 250,
        half: 96,
    },
    RoadPt {
        y: 4400,
        x: 300,
        half: 114,
    },
    RoadPt {
        y: 4000,
        x: 255,
        half: 94,
    },
    RoadPt {
        y: 3600,
        x: 210,
        half: 108,
    },
    RoadPt {
        y: 3200,
        x: 250,
        half: 94,
    },
    RoadPt {
        y: 2800,
        x: 310,
        half: 110,
    },
    RoadPt {
        y: 2400,
        x: 250,
        half: 92,
    },
    RoadPt {
        y: 2000,
        x: 170,
        half: 98,
    },
    RoadPt {
        y: 1600,
        x: 220,
        half: 90,
    },
    RoadPt {
        y: 1200,
        x: 290,
        half: 104,
    },
    RoadPt {
        y: 800,
        x: 250,
        half: 88,
    },
    RoadPt {
        y: 400,
        x: 210,
        half: 74,
    },
    RoadPt {
        y: 100,
        x: 240,
        half: 112,
    },
];

struct OilPatch {
    y: i32,
    lane_milli: i32,
    r: i32,
}

const OIL: [OilPatch; 9] = [
    OilPatch {
        y: 5460,
        lane_milli: 350,
        r: 34,
    },
    OilPatch {
        y: 5050,
        lane_milli: -450,
        r: 30,
    },
    OilPatch {
        y: 4300,
        lane_milli: 420,
        r: 38,
    },
    OilPatch {
        y: 3740,
        lane_milli: -280,
        r: 32,
    },
    OilPatch {
        y: 3060,
        lane_milli: 500,
        r: 36,
    },
    OilPatch {
        y: 2480,
        lane_milli: -500,
        r: 40,
    },
    OilPatch {
        y: 1780,
        lane_milli: 340,
        r: 34,
    },
    OilPatch {
        y: 1080,
        lane_milli: -350,
        r: 31,
    },
    OilPatch {
        y: 560,
        lane_milli: 250,
        r: 28,
    },
];

struct RampDef {
    y: i32,
    lane_milli: i32,
    w: i32,
    h: i32,
}

const RAMPS: [RampDef; 5] = [
    RampDef {
        y: 5350,
        lane_milli: 50,
        w: 38,
        h: 22,
    },
    RampDef {
        y: 4720,
        lane_milli: -420,
        w: 34,
        h: 20,
    },
    RampDef {
        y: 3500,
        lane_milli: 380,
        w: 40,
        h: 22,
    },
    RampDef {
        y: 2640,
        lane_milli: -350,
        w: 38,
        h: 20,
    },
    RampDef {
        y: 1160,
        lane_milli: 320,
        w: 36,
        h: 20,
    },
];

struct TrafficDef {
    y: i32,
    lane_milli: i32,
    throttle_milli: i32,
    weave: i32,
    weave_speed_milli: i32,
    phase_milli: i32,
}

const TRAFFIC: [TrafficDef; 15] = [
    TrafficDef {
        y: 5520,
        lane_milli: -580,
        throttle_milli: 450,
        weave: 4,
        weave_speed_milli: 1,
        phase_milli: 200,
    },
    TrafficDef {
        y: 5260,
        lane_milli: 500,
        throttle_milli: 390,
        weave: 7,
        weave_speed_milli: 1,
        phase_milli: 1400,
    },
    TrafficDef {
        y: 4930,
        lane_milli: -180,
        throttle_milli: 490,
        weave: 3,
        weave_speed_milli: 2,
        phase_milli: 2200,
    },
    TrafficDef {
        y: 4590,
        lane_milli: 620,
        throttle_milli: 420,
        weave: 5,
        weave_speed_milli: 1,
        phase_milli: 3100,
    },
    TrafficDef {
        y: 4270,
        lane_milli: -580,
        throttle_milli: 520,
        weave: 4,
        weave_speed_milli: 1,
        phase_milli: 4500,
    },
    TrafficDef {
        y: 3950,
        lane_milli: 200,
        throttle_milli: 370,
        weave: 8,
        weave_speed_milli: 1,
        phase_milli: 800,
    },
    TrafficDef {
        y: 3610,
        lane_milli: -620,
        throttle_milli: 470,
        weave: 4,
        weave_speed_milli: 1,
        phase_milli: 5400,
    },
    TrafficDef {
        y: 3280,
        lane_milli: 580,
        throttle_milli: 430,
        weave: 6,
        weave_speed_milli: 1,
        phase_milli: 2700,
    },
    TrafficDef {
        y: 2940,
        lane_milli: -100,
        throttle_milli: 540,
        weave: 3,
        weave_speed_milli: 2,
        phase_milli: 1900,
    },
    TrafficDef {
        y: 2570,
        lane_milli: 620,
        throttle_milli: 400,
        weave: 7,
        weave_speed_milli: 1,
        phase_milli: 3800,
    },
    TrafficDef {
        y: 2190,
        lane_milli: -580,
        throttle_milli: 500,
        weave: 5,
        weave_speed_milli: 1,
        phase_milli: 5900,
    },
    TrafficDef {
        y: 1810,
        lane_milli: 260,
        throttle_milli: 380,
        weave: 8,
        weave_speed_milli: 1,
        phase_milli: 4100,
    },
    TrafficDef {
        y: 1420,
        lane_milli: -620,
        throttle_milli: 460,
        weave: 4,
        weave_speed_milli: 1,
        phase_milli: 500,
    },
    TrafficDef {
        y: 1040,
        lane_milli: 580,
        throttle_milli: 510,
        weave: 5,
        weave_speed_milli: 1,
        phase_milli: 2900,
    },
    TrafficDef {
        y: 650,
        lane_milli: -200,
        throttle_milli: 420,
        weave: 7,
        weave_speed_milli: 1,
        phase_milli: 5100,
    },
];

// == GAME: integer / fixed-point helpers =====================================
// Pure math the game uses to reason in the engine's FP (×256) coordinate
// space. No engine calls here — just arithmetic on values we read/write.

fn clamp(v: i32, lo: i32, hi: i32) -> i32 {
    if v < lo {
        lo
    } else if v > hi {
        hi
    } else {
        v
    }
}

fn clamp_f(v: f64, lo: f64, hi: f64) -> f64 {
    if v < lo {
        lo
    } else if v > hi {
        hi
    } else {
        v
    }
}

fn decay_timer(t: i32, dt: i32) -> i32 {
    let next = t - dt;
    if next < 0 {
        0
    } else {
        next
    }
}

fn sin_milli(phase_milli: i64) -> i32 {
    let x = (phase_milli % 6283) as f64 / 1000.0;
    let x2 = x * x;
    let x3 = x2 * x;
    let x5 = x3 * x2;
    (x - x3 / 6.0 + x5 / 120.0) as i32 * 1000
}

fn sin_f(x: f64) -> f64 {
    let x2 = x * x;
    let x3 = x2 * x;
    let x5 = x3 * x2;
    x - x3 / 6.0 + x5 / 120.0
}

// == GAME: track geometry (road shape, oil/ramp hit tests, surface grip) =====
// All derived from the GAME data tables above; the engine knows none of it.

fn road_at(y_fp: i32) -> (i32, i32) {
    let y = y_fp / FP;
    let first = &ROAD[0];
    if y >= first.y {
        return (first.x * FP, first.half * FP);
    }
    let last = &ROAD[15];
    if y <= last.y {
        return (last.x * FP, last.half * FP);
    }
    let mut i = ((first.y - y) / 400) as usize;
    if i > 14 {
        i = 14;
    }
    let a = &ROAD[i];
    let b = &ROAD[i + 1];
    let span = a.y - b.y;
    let mut t = 0i32;
    if span > 0 {
        t = ((a.y - y) * FP) / span;
    }
    let cx = a.x * FP + (b.x * FP - a.x * FP) * t / FP;
    let half = a.half * FP + (b.half * FP - a.half * FP) * t / FP;
    (cx, half)
}

fn lane_x(y: i32, lane_milli: i32, margin: i32) -> i32 {
    let (cx, half) = road_at(y * FP);
    let usable = half - margin * FP;
    cx + usable * clamp(lane_milli, -1000, 1000) / 1000
}

fn cx_lane(y_fp: i32, lane_milli: i32) -> i32 {
    let (cx, half) = road_at(y_fp);
    let usable = half - 22 * FP;
    cx + usable * clamp(lane_milli, -1000, 1000) / 1000
}

fn patch_x(o: &OilPatch) -> i32 {
    lane_x(o.y, o.lane_milli, 18)
}

fn on_oil(x_fp: i32, y_fp: i32) -> bool {
    let y = y_fp / FP;
    let mut i = 0;
    while i < OIL.len() {
        let o = &OIL[i];
        let px = patch_x(o);
        let dx = (x_fp - px) as f64 / FP as f64;
        let dy = (y - o.y) as f64;
        if dx * dx + dy * dy < (o.r * o.r) as f64 {
            return true;
        }
        i += 1;
    }
    false
}

fn road_grip_milli(x_fp: i32, y_fp: i32) -> i32 {
    let (cx, half) = road_at(y_fp);
    let edge = half - 16 * FP;
    let off = x_fp - cx;
    let mut grip = 1000;
    if off < 0 {
        if -off > edge {
            grip = 450;
        }
    } else if off > edge {
        grip = 450;
    }
    grip
}

fn surface_grip_for_player(idx: i32, x_fp: i32, y_fp: i32) -> i32 {
    let grip = road_grip_milli(x_fp, y_fp);
    if idx > BODY_P2 && on_oil(x_fp, y_fp) && grip > 500 {
        return 500;
    }
    grip
}

fn hit_ramp(x_fp: i32, y_fp: i32) -> bool {
    let y = y_fp / FP;
    let half_w = |w: i32| (w * FP) / 2;
    let mut i = 0;
    while i < RAMPS.len() {
        let r = &RAMPS[i];
        let rx = lane_x(r.y, r.lane_milli, 24);
        let hw = half_w(r.w);
        if x_fp >= rx - hw && x_fp <= rx + hw && y >= r.y && y <= r.y + r.h {
            return true;
        }
        i += 1;
    }
    false
}

// == GAME: body id-code predicates (this game's contact vocabulary) ==========
// The engine hands us raw `body_a`/`body_b` id codes in contacts; deciding
// that 0/1 are players, 100.. are cones, etc. is purely our taxonomy.

fn is_player(code: i32) -> bool {
    code == BODY_P1 || code == BODY_P2
}

fn is_wall(code: i32) -> bool {
    code == ID_WALL_L || code == ID_WALL_R
}

fn is_cone(code: i32) -> bool {
    (100..200).contains(&code)
}

fn is_bar(code: i32) -> bool {
    (200..300).contains(&code)
}

fn is_traffic(code: i32) -> bool {
    code >= TRAFFIC_START && code < TRAFFIC_START + TRAFFIC_COUNT
}

// == GAME: driving + traffic AI ==============================================
// This is the car game's behaviour. It consumes engine inputs/poses and
// produces engine controls/impulses, but the mapping (buttons -> steer, the
// oil spin burst, the ramp launch, the traffic weave) is all game design.

/// GAME rule: map the engine's generic digital input into THIS game's control
/// channel convention — ch0 steer, ch1 throttle, ch2 brake, ch3 grip (all
/// milli / STEER_SCALE units). The `Input` type and `Buttons` bits are the
/// engine interface; what a pressed button MEANS for a car is the game.
fn drive_from_input(input: Input) -> (i32, i32, i32) {
    let mut steer = 0;
    let mut throttle = 0;
    let mut brake = 0;
    if input.held(Buttons::LEFT) {
        // [engine] read a digital input bit through the shared Input handle.
        steer = -STEER_SCALE;
    }
    if input.held(Buttons::RIGHT) {
        // [engine]
        steer = STEER_SCALE;
    }
    if input.held(Buttons::UP) {
        // [engine]
        throttle = STEER_SCALE;
    }
    if input.held(Buttons::DOWN) {
        // [engine]
        brake = STEER_SCALE;
    }
    (steer, throttle, brake)
}

fn traffic_control(w: &World, idx: i32, t: &TrafficDef, now: i32) -> (i32, i32, i32, i32) {
    let b = w.body(idx); // [engine] read this body's host-simulated pose
    let look_y = b.y_fp - 115 * FP;
    let (cx, half) = road_at(look_y);
    let phase = now as i64 * t.weave_speed_milli as i64 * 12 / 10000 + t.phase_milli as i64;
    let wave = sin_milli(phase) * t.weave / 1000;
    let target_x = cx + (half - 23 * FP) * t.lane_milli / 1000 + wave * FP;
    let error = target_x - b.x_fp;
    let mut steer = clamp(error / 34, -STEER_SCALE, STEER_SCALE);
    let (here_cx, here_half) = road_at(b.y_fp);
    let safe_l = here_cx - here_half + 16 * FP;
    let safe_r = here_cx + here_half - 16 * FP;
    if b.x_fp < safe_l {
        steer = STEER_SCALE;
    }
    if b.x_fp > safe_r {
        steer = -STEER_SCALE;
    }
    let grip = surface_grip_for_player(idx, b.x_fp, b.y_fp);
    (steer, t.throttle_milli, 0, grip)
}

fn body_vx_vy_fp(w: &World, idx: i32) -> (i32, i32) {
    let b = w.body(idx); // [engine] read pose (angle/speed) to derive velocity
    let ang_deg = b.angle as f64 / 1000.0;
    let rad = ang_deg * core::f64::consts::PI / 180.0;
    let speed = b.speed as f64 / FP as f64;
    let vx = (rad.sin() * speed * FP as f64) as i32;
    let vy = (-rad.cos() * speed * FP as f64) as i32;
    (vx, vy)
}

fn oil_entry_spin(w: &World, idx: i32, steer: i32, now: i32) -> i32 {
    let b = w.body(idx); // [engine] read pose to size the game's spin burst
    let mut spd_f = b.speed as f64 / FP as f64;
    if spd_f < 40.0 {
        spd_f = 40.0;
    }
    let x = b.x_fp as f64 / FP as f64;
    let y = b.y_fp as f64 / FP as f64;
    let phase = now as f64 * 0.012 + x * 0.06 + y * 0.04;
    let sign = if sin_f(phase) >= 0.0 { 1.0 } else { -1.0 };
    let wobble = sin_f(phase) * spd_f * 0.08;
    let steer_spin = (steer as f64 / STEER_SCALE as f64) * spd_f * 0.12;
    ((wobble + steer_spin + sign * 22.0) * FP as f64) as i32
}

fn spin_stabilizer_fp(w: &World, idx: i32, oil_recover: bool) -> i32 {
    let av = w.body(idx).ang_vel as f64 / FP as f64; // [engine] read angular vel
    let mut abs = av;
    if abs < 0.0 {
        abs = -abs;
    }
    let (start, full, base, span) = if oil_recover {
        (35.0, 180.0, 0.28, 0.42)
    } else {
        (200.0, 420.0, 0.10, 0.20)
    };
    if abs < start {
        return 0;
    }
    let mut t = (abs - start) / (full - start);
    t = clamp_f(t, 0.0, 1.0);
    let strength = base + t * span;
    (-av * strength * FP as f64) as i32
}

fn cone_launch_impulse(
    w: &World,
    player: i32,
    body_b: i32,
    nx_m: i32,
    ny_m: i32,
) -> (i32, i32, i32) {
    let mut nx = nx_m;
    let mut ny = ny_m;
    if body_b == player {
        nx = -nx;
        ny = -ny;
    }
    let nx_f = nx as f64 / 1000.0;
    let ny_f = ny as f64 / 1000.0;
    let (cvx, cvy) = body_vx_vy_fp(w, player);
    let cvx_f = cvx as f64 / FP as f64;
    let cvy_f = cvy as f64 / FP as f64;
    let share = CAR_MASS as f64 / (CAR_MASS + CONE_MASS) as f64;
    let lvx_f = cvx_f * share * 0.25 + nx_f * 25.0;
    let lvy_f = cvy_f * share * 0.25 + ny_f * 25.0;
    let ang_f = nx_f * 200.0 + ny_f * 90.0;
    (
        (lvx_f * FP as f64) as i32,
        (lvy_f * FP as f64) as i32,
        (ang_f * FP as f64) as i32,
    )
}

// == GAME: audio / rumble / particle feedback ================================
// WHEN to buzz, screech or spray sparks (and how hard) is game feel. HOW the
// event reaches the host is the engine: we queue generic events whose sub-ids
// and payload layout are OUR convention — `event::PARTICLES` etc. are just the
// engine's event-kind tags, the sub-id/args meaning is the game's.

fn push_particles(w: &mut World, x_fp: i32, y_fp: i32, amount: i32) {
    // [engine] enqueue a generic PARTICLES event on the shared block.
    w.push_event(event::PARTICLES, 0, x_fp, y_fp, amount);
}

fn push_rumble(w: &mut World, pad: i32, ms: i32, strength: i32) {
    // [engine] enqueue a generic RUMBLE event on the shared block.
    w.push_event(event::RUMBLE, pad, strength, strength, ms);
}

fn collision_rumble(w: &mut World, player: i32, imp_fp: i32, kind: i32) {
    let imp = imp_fp as f64 / FP as f64;
    if imp < 22.0 {
        return;
    }
    let pad = if player == BODY_P2 { 1 } else { 0 };
    let (ms, strength) = if kind == 1 {
        (38, 6500 + clamp((imp * 40.0) as i32, 0, 9000))
    } else if kind == 2 {
        (
            55 + clamp((imp * 0.35) as i32, 0, 100),
            12000 + clamp((imp * 70.0) as i32, 0, 18000),
        )
    } else {
        (
            60 + clamp((imp * 0.45) as i32, 0, 130),
            14000 + clamp((imp * 90.0) as i32, 0, 24000),
        )
    };
    push_rumble(w, pad, ms, strength);
}

fn push_collision_feedback(w: &mut World, player: i32, other: i32, imp_fp: i32) {
    if is_wall(other) || is_bar(other) || is_traffic(other) {
        let imp = imp_fp as f64 / FP as f64;
        if imp >= 18.0 {
            w.sound(SND_WALL); // [engine] play a palette sound by our sound id
        }
        let kind = if is_traffic(other) { 2 } else { 0 };
        collision_rumble(w, player, imp_fp, kind);
        return;
    }
    if is_cone(other) {
        w.sound(SND_BOUNCE); // [engine] play a palette sound by our sound id
        collision_rumble(w, player, imp_fp, 1);
    }
}

// == GAME: per-player state ==================================================
// This struct lives in the guest's own memory, NOT in the engine block. It is
// the game's private bookkeeping (crash count, cooldowns, boost timer). The
// engine neither sees nor cares about these fields.

#[derive(Clone, Copy, Default)]
struct PlayerState {
    ramp_cd: i32,
    brake_cd: i32,
    air: i32, // boost/air time left, ms (transported via the generic scalars)
    oil_cd: i32,
    oil_recover: i32,
    oil_was: bool,
    // HUD-visible state.
    hits: i32,
    last_hit: i32, // 0 none, 1 wall, 2 bar, 3 car(traffic), 4 cone
    flash: i32,    // ms remaining on the crash flash
    grip: i32,     // 0..1000
}

impl PlayerState {
    /// Record a collision for the HUD. Cone (kind 4) is a light bump: show
    /// the label but don't count it as a hit or flash the counter red.
    fn note_hit(&mut self, other: i32) {
        let kind = if is_wall(other) {
            1
        } else if is_bar(other) {
            2
        } else if is_traffic(other) {
            3
        } else if is_cone(other) {
            4
        } else {
            0
        };
        if kind == 0 {
            return;
        }
        self.last_hit = kind;
        if kind != 4 {
            self.hits += 1;
            self.flash = HIT_FLASH_MS;
        }
    }

    fn hud(&self) -> hud::PlayerHud {
        hud::PlayerHud {
            hits: self.hits,
            last_hit: self.last_hit,
            grip: self.grip,
            boost: self.air > 0,
            flash: self.flash > 0,
        }
    }
}

fn tick_brake_audio(w: &mut World, player: i32, brake: i32, cd: &mut i32, dt: i32) {
    *cd = decay_timer(*cd, dt);
    if brake <= 0 || *cd > 0 {
        return;
    }
    let spd = w.body(player).speed; // [engine] read pose speed
    if spd / FP >= BRAKE_SCREECH_MIN_SPD {
        w.sound(SND_BOUNCE); // [engine] play a palette sound
        *cd = BRAKE_SCREECH_CD_MS;
    }
}

/// Oil spin burst + spin stabilizer + ramp launch for one player.
fn apply_player_extras(
    w: &mut World,
    ps: &mut PlayerState,
    idx: i32,
    steer: i32,
    now: i32,
    dt: i32,
) {
    let b = w.body(idx); // [engine] read this player's pose
    let on = on_oil(b.x_fp, b.y_fp); // game: is that pose over an oil patch?
    if on && !ps.oil_was {
        w.sound(SND_BOUNCE); // [engine] play a palette sound
        let burst = oil_entry_spin(w, idx, steer, now); // game: how much spin
        if burst != 0 {
            w.push_impulse(idx, 0, 0, burst); // [engine] queue angular impulse
        }
    }
    ps.oil_was = on;
    if ps.oil_cd > 0 {
        ps.oil_cd = decay_timer(ps.oil_cd, dt);
    }
    if ps.oil_recover > 0 {
        ps.oil_recover = decay_timer(ps.oil_recover, dt);
    }
    let recover = ps.oil_recover > 0;
    let damp = spin_stabilizer_fp(w, idx, recover); // game: anti-spin torque
    if damp != 0 {
        w.push_impulse(idx, 0, 0, damp); // [engine] queue angular impulse
    }
    if ps.ramp_cd <= 0 && hit_ramp(b.x_fp, b.y_fp) {
        w.push_impulse(idx, 0, -95 * FP, 320 * FP); // [engine] queue launch impulse
        ps.ramp_cd = 700;
        ps.air = 900;
        let pad = if idx == BODY_P2 { 1 } else { 0 };
        w.sound(SND_BOUNCE); // [engine] play a palette sound
        push_rumble(w, pad, 70, 12000);
    }
}

// == GAME: the game object + its WorldGame implementation ====================
// `Autopeli` is the whole game state (guest memory). Its methods are where
// game rules meet the Game Engine: they READ engine data (contacts, poses,
// score) and WRITE engine data (controls, impulses, events, camera, HUD).
// Look for the `// [engine]` tags to see exactly where the boundary is crossed.

struct Autopeli {
    players: [PlayerState; 2],
    someone_won: bool,
    ui_rev: u32,
    ui_last_sig: i32,
}

impl Autopeli {
    /// Contacts arrive host-written before update(): count hits, launch hit
    /// cones with impulses, and emit sound/rumble/particle feedback.
    fn process_contacts(&mut self, w: &mut World) {
        let cnt = w.contact_count(); // [engine] how many contacts the host wrote
        let mut hits = w.hits(); // [engine] read the shared hit counter
        let mut ci = 0;
        while ci < cnt {
            let c = w.contact(ci); // [engine] read one host-written contact
            if c.phase == 1 {
                let (player, other) = if is_player(c.body_a) {
                    (c.body_a, c.body_b)
                } else if is_player(c.body_b) {
                    (c.body_b, c.body_a)
                } else {
                    (-1, -1)
                };
                if player >= 0 {
                    self.players[player as usize].note_hit(other);
                    if is_wall(other) || is_bar(other) || is_traffic(other) {
                        hits += 1;
                        let imp = c.impulse_fp as f64 / FP as f64;
                        if is_wall(other) && imp > 80.0 {
                            push_particles(w, c.x_fp, c.y_fp, 6);
                        }
                        if is_bar(other) && imp > 45.0 {
                            push_particles(w, c.x_fp, c.y_fp, 6);
                        }
                        if is_traffic(other) && imp > 55.0 {
                            push_particles(w, c.x_fp, c.y_fp, 5);
                        }
                    }
                    if is_cone(other) {
                        // game: compute how a struck cone should fly...
                        let (lx, ly, ang) =
                            cone_launch_impulse(w, player, c.body_b, c.nx_milli, c.ny_milli);
                        w.push_impulse(other, lx, ly, ang); // [engine] ...then queue it
                    }
                    push_collision_feedback(w, player, other, c.impulse_fp);
                }
            }
            ci += 1;
        }
        w.set_hits(hits); // [engine] publish the updated shared hit counter
    }

    fn check_win(&mut self, w: &mut World) {
        if self.someone_won {
            return;
        }
        let y1 = w.body(BODY_P1).y_fp / FP; // [engine] read pose
        let y2 = w.body(BODY_P2).y_fp / FP; // [engine] read pose
        // game rule: crossing FINISH_Y wins the race.
        if y1 < FINISH_Y || y2 < FINISH_Y {
            let score = w.score(); // [engine] read the shared score
            w.set_score(score + WIN_SCORE); // [engine] publish the new score
            w.sound(SND_WIN); // [engine] play a palette sound
            self.someone_won = true;
        }
    }

    /// Rebuild the HUD document only when its rendered content changed,
    /// bumping `revision` so the host can skip identical frames.
    fn ui_refresh(&mut self) {
        let p1 = self.players[0].hud();
        let p2 = self.players[1].hud();
        let sig = hud_signature(p1, p2);
        if sig != self.ui_last_sig {
            self.ui_last_sig = sig;
            self.ui_rev += 1;
            // [engine] author the RGU1 HUD document (via the ui builder in hud.rs)
            hud::build_hud(p1, p2, self.ui_rev);
        }
    }
}

/// A small signature of everything the HUD renders, so revision only bumps
/// when the displayed content actually changes (snapshot-first).
fn hud_signature(p1: hud::PlayerHud, p2: hud::PlayerHud) -> i32 {
    let mut s: i32 = 17;
    let mut mix = |v: i32| {
        s = s.wrapping_mul(31).wrapping_add(v);
    };
    mix(p1.hits);
    mix(p1.last_hit);
    mix(p1.grip / 10);
    mix(p1.boost as i32);
    mix(p1.flash as i32);
    mix(p2.hits);
    mix(p2.last_hit);
    mix(p2.grip / 10);
    mix(p2.boost as i32);
    mix(p2.flash as i32);
    s
}

// GAME ENGINE INTERFACE: `WorldGame` is the engine's contract. We implement
// its three hooks; the `world_game!` macro (bottom of file) turns them into the
// exact WASM exports the host calls (init / update / declare_resources). The
// engine drives us — it calls these; we never call the host directly.
impl WorldGame for Autopeli {
    // [engine] hook: the host calls this once after load. Body of the fn is the
    // GAME telling the engine which spritesheets/rects it will draw with; the
    // string names, sizes and frame counts are all game data.
    fn declare_resources() {
        resources::sheet("p1", "assets/car1.png", 471, 909, 4, 454, 10);
        resources::sheet("p2", "assets/car2.png", 471, 908, 4, 454, 10);
        resources::sheet("trafficCar", "assets/othercar.png", 285, 625, 7, 312, 10);
        resources::sheet("cone", "assets/cone.png", 204, 275, 9, 252, 10);
        resources::sheet("oil", "assets/oil.png", 891, 706, 9, 353, 0);
        resources::rect("bar", 8, 46, 210, 215, 225, 5);
    }

    // [engine] hook: the host calls this once to build initial state. We hand
    // the engine our scene (body count + spawn positions computed from GAME
    // track data) and return the game state struct it will keep for us.
    fn init(w: &mut World) -> Self {
        w.set_body_count(BODY_COUNT); // [engine] declare how many bodies exist

        let spawn_y = (6000 - 140) * FP; // game: start line just below the top
        let (sx, _) = road_at(spawn_y); // game: where the road centre is there
        w.set_body_pos(BODY_P1, sx - 28 * FP, spawn_y); // [engine] place body
        w.set_body_pos(BODY_P2, sx + 28 * FP, spawn_y); // [engine] place body

        let mut ti = 0;
        while ti < TRAFFIC_COUNT {
            let t = &TRAFFIC[ti as usize]; // game data
            let x = cx_lane(t.y * FP, t.lane_milli); // game: lane -> world x
            w.set_body_pos(TRAFFIC_START + ti, x, t.y * FP); // [engine] place body
            ti += 1;
        }

        // [engine] Publish an empty (but valid) HUD document at revision 0; the
        // first ui_refresh builds the real one at revision 1.
        ranger_game::ui::reset();
        ranger_game::ui::finish(0);

        Autopeli {
            players: [PlayerState::default(); 2],
            someone_won: false,
            ui_rev: 0,
            ui_last_sig: -1,
        }
    }

    // [engine] hook: the host calls this every frame. `f` (Frame) is engine
    // input the host wrote this tick; `w` (World) is the engine's read/write
    // handle onto the shared block. The BODY of this method is the game loop.
    fn update(&mut self, f: &ranger_game::world::Frame, w: &mut World) {
        self.process_contacts(w); // game step (reads engine contacts inside)

        let dt = f.dt_ms; // [engine] frame delta the host supplied
        let now = f.time_ms; // [engine] host clock the host supplied

        // game: turn engine input into our control-channel triples.
        let (p_steer, p_th, p_br) = drive_from_input(f.input); // [engine] f.input
        let (p2_steer, p2_th, p2_br) = drive_from_input(f.input_p2); // [engine]

        // Oil entry effect timers arm when a player rolls onto a patch
        // (oil_was itself is updated later, in apply_player_extras).
        for (i, idx) in [BODY_P1, BODY_P2].iter().enumerate() {
            let b = w.body(*idx); // [engine] read pose
            let ps = &mut self.players[i]; // game state
            if on_oil(b.x_fp, b.y_fp) && !ps.oil_was {
                ps.oil_cd = OIL_EFFECT_MS;
                ps.oil_recover = OIL_RECOVER_MS;
            }
        }

        let b1 = w.body(BODY_P1); // [engine] read pose
        let b2 = w.body(BODY_P2); // [engine] read pose
        let p1_grip = surface_grip_for_player(BODY_P1, b1.x_fp, b1.y_fp); // game
        let p2_grip = surface_grip_for_player(BODY_P2, b2.x_fp, b2.y_fp); // game
        self.players[0].grip = p1_grip; // game state (for the HUD)
        self.players[1].grip = p2_grip;
        // [engine] hand the engine each player's controls (our ch0..ch3 meaning).
        w.set_control(BODY_P1, p_steer, p_th, p_br, p1_grip);
        w.set_control(BODY_P2, p2_steer, p2_th, p2_br, p2_grip);

        let mut ti = 0;
        while ti < TRAFFIC_COUNT {
            let idx = TRAFFIC_START + ti;
            let t = &TRAFFIC[ti as usize]; // game data
            let (st, th, br, gr) = traffic_control(w, idx, t, now); // game AI
            w.set_control(idx, st, th, br, gr); // [engine] hand over controls
            ti += 1;
        }

        {
            let mut cd = self.players[0].brake_cd;
            tick_brake_audio(w, BODY_P1, p_br, &mut cd, dt);
            self.players[0].brake_cd = cd;
            let mut cd2 = self.players[1].brake_cd;
            tick_brake_audio(w, BODY_P2, p2_br, &mut cd2, dt);
            self.players[1].brake_cd = cd2;
        }
        for ps in self.players.iter_mut() {
            ps.ramp_cd = decay_timer(ps.ramp_cd, dt);
            ps.air = decay_timer(ps.air, dt);
            ps.flash = decay_timer(ps.flash, dt);
        }

        {
            let mut ps = self.players[0];
            apply_player_extras(w, &mut ps, BODY_P1, p_steer, now, dt);
            self.players[0] = ps;
            let mut ps2 = self.players[1];
            apply_player_extras(w, &mut ps2, BODY_P2, p2_steer, now, dt);
            self.players[1] = ps2;
        }
        // [engine] stash the game's boost timers in the two generic scalars
        // (the engine has no idea these mean "air time" — that's our meaning).
        w.set_scalar(0, self.players[0].air);
        w.set_scalar(1, self.players[1].air);

        let cam = w.body(BODY_P1).y_fp - 120 * FP; // [engine] read pose; game: offset
        w.set_camera_y(cam); // [engine] tell the engine where to scroll
        self.check_win(w); // game step (touches engine score inside)

        self.ui_refresh(); // game step (authors the engine HUD inside)
    }
}

// GAME ENGINE INTERFACE: these two macros generate the raw WASM exports the
// host looks up (abi_base / init / update / declare_resources / rg_abi_version
// and rg_ui_ptr / rg_ui_size / rg_ui_revision). They are pure engine plumbing —
// the game supplies only the `Autopeli` type above.
ranger_game::world_game!(Autopeli);
ranger_game::ui_exports!();
