//! rust_pose_arena — the first WASM guest driven by RGP1 pose input.
//!
//! It is the pose counterpart of `games/sprite_char`: a real `.wasm` game the
//! launcher loads through the shared sprite host, but instead of a gamepad it
//! reacts to a camera + AI model streaming pose over the RGP1 ABI. The whole
//! game is this file plus the `ranger_game` crate — no C++, no bespoke host (the
//! earlier `pose/native_game/pose_game.cc` drew with SDL directly; this goes
//! through the WASM bridge like every other game in `games/`).
//!
//! What it does each tick:
//!   1. reads the streamed [`Pose`] (present / gesture / landmarks) over RGP1,
//!   2. authors an RGU1 HUD showing the LATEST POSE EVENT AS TEXT (the minimum
//!      requirement — gesture name, body-present, landmark count, nose x/y), and
//!   3. draws a ready character from the host catalog (mage / knight — the new
//!      sprite-demo characters) via RGSP1, following the tracked head so the
//!      sprite features live behind the WASM engine.
//!
//! Game logic is deliberately light: the pose→gameplay rules are not specified
//! yet, so this proves the pipeline (pose in → text + sprite out) and stays easy
//! to edit. The host renders the RGU1 text and MAY overlay the skeleton from the
//! same RGP1 block it streamed.
//!
//! ABI plumbing (block layouts, exports, the pose reader) lives in
//! `ranger_game`; the exports the host calls (`sprite_*`, `rg_pose_*`, `rg_ui_*`,
//! `rg_required_caps`) are generated by the macros at the bottom.

use ranger_game::pose::Pose;
use ranger_game::sprite::{Anim, Dir, Frame, Scene, Slot, SpritePoseGame};
use ranger_game::{fp, px, ui};

// --- Gesture vocabulary (THIS GAME's convention; the ABI assigns no meaning).
// Matches the fake/native pose sources (game_pose_provider.rgr, rg_pose.h):
// 0 none, 1 arms-up, 2 lean-left, 3 lean-right.
const G_NONE: i32 = 0;
const G_ARMS_UP: i32 = 1;
const G_LEAN_LEFT: i32 = 2;
const G_LEAN_RIGHT: i32 = 3;

// --- Landmarks this game reads (BlazePose ordering; which one drives the game
// is the guest's choice — see RGP1 §2.4). We only need the head (nose).
const LM_NOSE: i32 = 0;

// --- Catalog characters (the sprite-demo roster: 1 hero, 2 knight, 3 mage,
// 4 rogue). We use the two NEW ones the sprite demo added.
const CHAR_KNIGHT: i32 = 2;
const CHAR_MAGE: i32 = 3;

// --- RGU1 node ids (stable; the host maps highlight/selection back by id).
const UI_ROOT: i32 = 1;
const UI_TITLE: i32 = 2;
const UI_GESTURE: i32 = 3;
const UI_BODY: i32 = 4;
const UI_COORDS: i32 = 5;
const UI_HINT: i32 = 6;

fn gesture_name(g: i32) -> &'static str {
    match g {
        G_ARMS_UP => "ARMS UP",
        G_LEAN_LEFT => "LEAN LEFT",
        G_LEAN_RIGHT => "LEAN RIGHT",
        _ => "-",
    }
}

/// Format a small non-negative integer into `buf`, returning the used slice.
/// `no_std`-friendly (no alloc); enough for HUD counts/coords.
fn fmt_uint(mut v: i32, buf: &mut [u8]) -> usize {
    if v < 0 {
        v = 0;
    }
    let mut tmp = [0u8; 12];
    let mut n = 0;
    if v == 0 {
        tmp[0] = b'0';
        n = 1;
    } else {
        while v > 0 && n < tmp.len() {
            tmp[n] = b'0' + (v % 10) as u8;
            v /= 10;
            n += 1;
        }
    }
    let mut w = 0;
    while w < n && w < buf.len() {
        buf[w] = tmp[n - 1 - w];
        w += 1;
    }
    w
}

/// Append `s` bytes into `buf` at `pos`, returning the new position.
fn put(buf: &mut [u8], pos: usize, s: &[u8]) -> usize {
    let mut p = pos;
    let mut i = 0;
    while i < s.len() && p < buf.len() {
        buf[p] = s[i];
        p += 1;
        i += 1;
    }
    p
}

struct PoseArena {
    /// Which catalog character to draw (toggles between the two new ones).
    character: i32,
    /// Latest gesture seen (for edge detection).
    last_gesture: i32,
    /// Rising-edge count of ARMS_UP (a tiny bit of state to prove reactions).
    arms_up_reps: i32,
    /// Per-slot walk clock so the sprite animates while the body moves.
    walk_clock: i32,
    /// Last facing direction (kept when the body stops).
    face: Dir,
    /// RGU1 revision (bump only when the rendered content changes).
    ui_rev: u32,
    ui_last_sig: i32,
}

impl PoseArena {
    /// Rebuild the HUD only when its text changed, bumping the revision so the
    /// host can skip re-parsing identical frames (snapshot-first, IDEAL §2.3).
    fn refresh_hud(&mut self, present: bool, gesture: i32, lm_count: i32, nx: i32, ny: i32) {
        let sig = hud_signature(present, gesture, self.arms_up_reps, lm_count, nx, ny);
        if sig == self.ui_last_sig {
            return;
        }
        self.ui_last_sig = sig;
        self.ui_rev += 1;

        // "GESTURE: <name> (reps N)"
        let mut gline = [0u8; 40];
        let mut gp = put(&mut gline, 0, b"GESTURE: ");
        gp = put(&mut gline, gp, gesture_name(gesture).as_bytes());
        if self.arms_up_reps > 0 {
            gp = put(&mut gline, gp, b"  x");
            let mut nb = [0u8; 12];
            let nlen = fmt_uint(self.arms_up_reps, &mut nb);
            gp = put(&mut gline, gp, &nb[..nlen]);
        }

        // "BODY: yes / --  (LM N)"
        let mut bline = [0u8; 40];
        let mut bp = if present {
            put(&mut bline, 0, b"BODY: yes  LM ")
        } else {
            put(&mut bline, 0, b"BODY: --   LM ")
        };
        let mut cb = [0u8; 12];
        let clen = fmt_uint(lm_count, &mut cb);
        bp = put(&mut bline, bp, &cb[..clen]);

        // "NOSE x,y" in view pixels.
        let mut cline = [0u8; 40];
        let mut cp = put(&mut cline, 0, b"NOSE ");
        let mut xb = [0u8; 12];
        let xlen = fmt_uint(nx, &mut xb);
        cp = put(&mut cline, cp, &xb[..xlen]);
        cp = put(&mut cline, cp, b",");
        let mut yb = [0u8; 12];
        let ylen = fmt_uint(ny, &mut yb);
        cp = put(&mut cline, cp, &yb[..ylen]);

        ui::reset();
        let mut card = ui::root(UI_ROOT);
        card.column().pad(6).bg(11, 16, 32, 200);
        card.label(UI_TITLE, "POSE ARENA").font(16).color(255, 220, 120, 255);
        card.label(UI_GESTURE, core::str::from_utf8(&gline[..gp]).unwrap_or("GESTURE: ?"))
            .font(13)
            .color(140, 230, 180, 255);
        card.label(UI_BODY, core::str::from_utf8(&bline[..bp]).unwrap_or("BODY: ?"))
            .font(11)
            .color(210, 220, 240, 255);
        card.label(UI_COORDS, core::str::from_utf8(&cline[..cp]).unwrap_or("NOSE ?"))
            .font(11)
            .color(180, 200, 230, 255);
        card.label(UI_HINT, "arms up = jump / switch char")
            .font(10)
            .color(120, 140, 170, 255);
        ui::finish(self.ui_rev);
    }
}

/// A small signature of everything the HUD renders, so the revision only bumps
/// when displayed content actually changes.
fn hud_signature(present: bool, gesture: i32, reps: i32, lm: i32, nx: i32, ny: i32) -> i32 {
    let mut s: i32 = 17;
    let mut mix = |v: i32| s = s.wrapping_mul(31).wrapping_add(v);
    mix(present as i32);
    mix(gesture);
    mix(reps);
    mix(lm);
    mix(nx);
    mix(ny);
    s
}

impl SpritePoseGame for PoseArena {
    fn init() -> Self {
        PoseArena {
            character: CHAR_MAGE,
            last_gesture: G_NONE,
            arms_up_reps: 0,
            walk_clock: 0,
            face: Dir::Down,
            ui_rev: 0,
            ui_last_sig: -1,
        }
    }

    fn tick(&mut self, frame: &Frame, pose: &Pose, scene: &mut Scene) {
        let present = pose.present();
        let gesture = pose.gesture();
        let lm_count = pose.landmark_count();
        let nose = pose.landmark(LM_NOSE);

        // Rising edge of ARMS_UP: count a rep and toggle the drawn character so
        // both new sprite-demo characters (mage / knight) are exercised.
        if present && gesture == G_ARMS_UP && self.last_gesture != G_ARMS_UP {
            self.arms_up_reps += 1;
            self.character = if self.character == CHAR_MAGE {
                CHAR_KNIGHT
            } else {
                CHAR_MAGE
            };
        }
        self.last_gesture = gesture;

        // Map the normalized nose position into view pixels (secondary to the
        // HUD; the sprite following the head is a bonus, not core logic yet).
        // x_fp is normalized[0,1] * 256, so px = x_fp * view / 256.
        let nx_px = px(nose.x_fp * frame.view_w);
        let ny_px = px(nose.y_fp * frame.view_h);

        // Facing + walk animation from the head's horizontal motion.
        if nose.vx > 8 {
            self.face = Dir::Right;
        } else if nose.vx < -8 {
            self.face = Dir::Left;
        } else if gesture == G_LEAN_LEFT {
            self.face = Dir::Left;
        } else if gesture == G_LEAN_RIGHT {
            self.face = Dir::Right;
        }
        let moving = present && (nose.speed.abs() > 4 || gesture != G_NONE);
        if moving {
            self.walk_clock += frame.dt_ms;
        } else {
            self.walk_clock = 0;
        }

        // Draw the character at the tracked head (feet a bit below the nose).
        // Arms-up shows the jump pose. Only when a body is present.
        if present {
            let anim = if gesture == G_ARMS_UP {
                Anim::Jump
            } else if moving {
                Anim::Walk
            } else {
                Anim::Walk
            };
            let feet_y = ny_px + 40;
            scene.push(
                Slot::character(self.character)
                    .anim(anim)
                    .dir(self.face)
                    .at(nx_px, feet_y)
                    .clock(self.walk_clock),
            );
        } else {
            // No body: park the character in the centre so the screen isn't empty.
            let cx = frame.view_w / 2;
            let cy = frame.view_h / 2 + 40;
            scene.push(
                Slot::character(self.character)
                    .anim(Anim::Walk)
                    .dir(Dir::Down)
                    .at(cx, cy)
                    .clock(0),
            );
        }
        // Keep the reference alive for future world scaling (silences unused fp).
        let _ = fp(0);

        self.refresh_hud(present, gesture, lm_count, nx_px, ny_px);
    }
}

ranger_game::sprite_pose_game!(PoseArena);
ranger_game::ui_exports!();

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn formats_small_uints() {
        let mut b = [0u8; 12];
        let n = fmt_uint(0, &mut b);
        assert_eq!(&b[..n], b"0");
        let n = fmt_uint(240, &mut b);
        assert_eq!(&b[..n], b"240");
        let n = fmt_uint(-5, &mut b);
        assert_eq!(&b[..n], b"0", "negatives clamp to 0");
    }

    #[test]
    fn puts_bytes_bounded() {
        let mut b = [0u8; 4];
        let p = put(&mut b, 0, b"POSE");
        assert_eq!(p, 4);
        let p = put(&mut b, 3, b"XY"); // only 1 byte fits
        assert_eq!(p, 4);
    }

    #[test]
    fn gesture_names_match_the_source_vocabulary() {
        assert_eq!(gesture_name(G_ARMS_UP), "ARMS UP");
        assert_eq!(gesture_name(G_LEAN_LEFT), "LEAN LEFT");
        assert_eq!(gesture_name(G_LEAN_RIGHT), "LEAN RIGHT");
        assert_eq!(gesture_name(G_NONE), "-");
        assert_eq!(gesture_name(99), "-");
    }
}
