// GENERATED by gallery/vela/tools/vela_chart_page.rgr — do not edit by hand.
//
// No specification was read to draw this page. Every chart on it was built
// by CALLING gallery/vela/src/VlChart.rgr, and the lines printed beside each
// chart are the calls that built it — read out of the tool's own source, so
// the code on the page and the code that drew it cannot drift apart.
//
// Regenerate with:  npm run vela:showcase

import { View, Label, Path } from "./evg_types";

function render() {
  return (
    <View className="page">
      <Label className="title">Kaavio-API</Label>
      <View className="rule" />
      <Label className="body">{"Yhtäkään spesifikaatiota ei luettu. Jokainen kaavio on rakennettu kutsumalla VlChart-rajapintaa, ja kaavion yllä lukevat rivit ovat ne kutsut jotka sen piirsivät — luettuna generaattorin omasta lähdekoodista, jotta sivun koodi ja sivun piirtänyt koodi eivät voi erkaantua."}</Label>
      <View className="row chartRow">
        <View className="chartCell">
          <Label className="subhead">Summa alueittain</Label>
          <View className="codeBlock">
            <Label className="codeLine">{"def chart (VlChart.create(rows))"}</Label>
            <Label className="codeLine">{"chart.size(150 95)"}</Label>
            <Label className="codeLine">{"def bars (chart.bar())"}</Label>
            <Label className="codeLine">{"bars.x(\"region\").keepOrder()"}</Label>
            <Label className="codeLine">{"bars.y(\"sales\").aggregate(\"sum\").title(\"myynti\")"}</Label>
          </View>
        <View className="chartBox">
          <View className="chart" position="relative" width="220.55px" height="172px">
            <Path className="chartFrame" position="absolute" left="0px" top="0px" width="220.55px" height="172px" viewBox="0 0 220.55 172" fill="none" strokeWidth="1" d="M66.05,10.5 L216.05,10.5 L216.05,105.5 L66.05,105.5 Z" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="220.55px" height="172px" viewBox="0 0 220.55 172" fill="none" strokeWidth="1" d="M66.05,105.5 L216.05,105.5 M66.05,73.5 L216.05,73.5 M66.05,42.5 L216.05,42.5 M66.05,10.5 L216.05,10.5" />
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="220.55px" height="172px" viewBox="0 0 220.55 172" fill="none" strokeWidth="1" d="M103.05,105.5 L103.05,110.5 M178.05,105.5 L178.05,110.5" />
            <Label className="chartLabel" position="absolute" left="84.362px" top="106.5px" width="37.375px" textAlign="center" fontSize="10px" rotate="270">Länsi</Label>
            <Label className="chartLabel" position="absolute" left="165.863px" top="106.5px" width="24.375px" textAlign="center" fontSize="10px" rotate="270">Itä</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="220.55px" height="172px" viewBox="0 0 220.55 172" fill="none" strokeWidth="1" d="M66.05,105.5 L216.05,105.5" />
            <Label className="chartTitle" position="absolute" left="116.6px" top="156.5px" width="48.9px" textAlign="center" fontSize="11px" fontWeight="bold">region</Label>
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="220.55px" height="172px" viewBox="0 0 220.55 172" fill="none" strokeWidth="1" d="M66.05,105.5 L61.05,105.5 M66.05,73.5 L61.05,73.5 M66.05,42.5 L61.05,42.5 M66.05,10.5 L61.05,10.5" />
            <Label className="chartLabel" position="absolute" left="46.425px" top="100.5px" width="12.625px" textAlign="right" fontSize="10px">0</Label>
            <Label className="chartLabel" position="absolute" left="33.175px" top="68.833px" width="25.875px" textAlign="right" fontSize="10px">200</Label>
            <Label className="chartLabel" position="absolute" left="33.175px" top="37.167px" width="25.875px" textAlign="right" fontSize="10px">400</Label>
            <Label className="chartLabel" position="absolute" left="33.175px" top="5.5px" width="25.875px" textAlign="right" fontSize="10px">600</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="220.55px" height="172px" viewBox="0 0 220.55 172" fill="none" strokeWidth="1" d="M66.05,105.5 L66.05,10.5" />
            <Label className="chartTitle" position="absolute" left="-0px" top="51.4px" width="48.9px" textAlign="center" fontSize="11px" fontWeight="bold" rotate="-90">myynti</Label>
            <Path className="chartFill0" position="absolute" left="0px" top="0px" width="220.55px" height="172px" viewBox="0 0 220.55 172" stroke="none" d="M69.3,15.5417 L136.8,15.5417 L136.8,105 L69.3,105 Z M144.3,40.7167 L211.8,40.7167 L211.8,105 L144.3,105 Z" />
          </View>
        </View>
          <Label className="caption">31 piirtokomentoa</Label>
        </View>
        <View className="chartCell">
          <Label className="subhead">Aikasarja · tyypit datasta</Label>
          <View className="codeBlock">
            <Label className="codeLine">{"def chart (VlChart.create(rows))"}</Label>
            <Label className="codeLine">{"chart.size(100 85)"}</Label>
            <Label className="codeLine">{"def line (chart.line())"}</Label>
            <Label className="codeLine">{"line.withPoints(true)"}</Label>
            <Label className="codeLine">{"line.x(\"quarter\").y(\"sales\").color(\"region\")"}</Label>
          </View>
        <View className="chartBox">
          <View className="chart" position="relative" width="244.975px" height="127px">
            <Path className="chartFrame" position="absolute" left="0px" top="0px" width="244.975px" height="127px" viewBox="0 0 244.975 127" fill="none" strokeWidth="1" d="M62.475,5.5 L162.475,5.5 L162.475,90.5 L62.475,90.5 Z" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="244.975px" height="127px" viewBox="0 0 244.975 127" fill="none" strokeWidth="1" d="M62.475,5.5 L62.475,90.5 M95.475,5.5 L95.475,90.5 M128.475,5.5 L128.475,90.5 M162.475,5.5 L162.475,90.5" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="244.975px" height="127px" viewBox="0 0 244.975 127" fill="none" strokeWidth="1" d="M62.475,90.5 L162.475,90.5 M62.475,66.5 L162.475,66.5 M62.475,43.5 L162.475,43.5 M62.475,19.5 L162.475,19.5" />
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="244.975px" height="127px" viewBox="0 0 244.975 127" fill="none" strokeWidth="1" d="M62.475,90.5 L62.475,95.5 M95.475,90.5 L95.475,95.5 M128.475,90.5 L128.475,95.5 M162.475,90.5 L162.475,95.5" />
            <Label className="chartLabel" position="absolute" left="62.475px" top="97.5px" width="32.5px" textAlign="left" fontSize="10px">2016</Label>
            <Label className="chartLabel" position="absolute" left="109.35px" top="97.5px" width="53.125px" textAlign="right" fontSize="10px">October</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="244.975px" height="127px" viewBox="0 0 244.975 127" fill="none" strokeWidth="1" d="M62.475,90.5 L162.475,90.5" />
            <Label className="chartTitle" position="absolute" left="84.45px" top="111.5px" width="56.05px" textAlign="center" fontSize="11px" fontWeight="bold">quarter</Label>
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="244.975px" height="127px" viewBox="0 0 244.975 127" fill="none" strokeWidth="1" d="M62.475,90.5 L57.475,90.5 M62.475,66.5 L57.475,66.5 M62.475,43.5 L57.475,43.5 M62.475,19.5 L57.475,19.5" />
            <Label className="chartLabel" position="absolute" left="42.85px" top="85.5px" width="12.625px" textAlign="right" fontSize="10px">0</Label>
            <Label className="chartLabel" position="absolute" left="36.225px" top="61.889px" width="19.25px" textAlign="right" fontSize="10px">50</Label>
            <Label className="chartLabel" position="absolute" left="29.6px" top="38.278px" width="25.875px" textAlign="right" fontSize="10px">100</Label>
            <Label className="chartLabel" position="absolute" left="29.6px" top="14.667px" width="25.875px" textAlign="right" fontSize="10px">150</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="244.975px" height="127px" viewBox="0 0 244.975 127" fill="none" strokeWidth="1" d="M62.475,90.5 L62.475,5.5" />
            <Label className="chartTitle" position="absolute" left="0px" top="41.4px" width="41.75px" textAlign="center" fontSize="11px" fontWeight="bold" rotate="-90">sales</Label>
            <Path className="chartStroke1" position="absolute" left="0px" top="0px" width="244.975px" height="127px" viewBox="0 0 244.975 127" fill="none" strokeWidth="2" d="M61.975,33.3333 L95.1867,21.5278 L128.3984,27.6667 L161.975,10.6667" />
            <Path className="chartStroke0" position="absolute" left="0px" top="0px" width="244.975px" height="127px" viewBox="0 0 244.975 127" fill="none" strokeWidth="2" d="M61.975,46.0833 L95.1867,48.4444 L128.3984,40.8889 L161.975,32.8611" />
            <Path className="chartFill1" position="absolute" left="0px" top="0px" width="244.975px" height="127px" viewBox="0 0 244.975 127" stroke="none" d="M64.7136,33.3333 C64.7136,34.8458 63.4875,36.0719 61.975,36.0719 C60.4625,36.0719 59.2364,34.8458 59.2364,33.3333 C59.2364,31.8208 60.4625,30.5947 61.975,30.5947 C63.4875,30.5947 64.7136,31.8208 64.7136,33.3333 Z M97.9253,21.5278 C97.9253,23.0403 96.6992,24.2664 95.1867,24.2664 C93.6742,24.2664 92.4481,23.0403 92.4481,21.5278 C92.4481,20.0153 93.6742,18.7892 95.1867,18.7892 C96.6992,18.7892 97.9253,20.0153 97.9253,21.5278 Z M131.137,27.6667 C131.137,29.1792 129.9109,30.4053 128.3984,30.4053 C126.8859,30.4053 125.6597,29.1792 125.6597,27.6667 C125.6597,26.1542 126.8859,24.9281 128.3984,24.9281 C129.9109,24.9281 131.137,26.1542 131.137,27.6667 Z M164.7136,10.6667 C164.7136,12.1792 163.4875,13.4053 161.975,13.4053 C160.4625,13.4053 159.2364,12.1792 159.2364,10.6667 C159.2364,9.1542 160.4625,7.9281 161.975,7.9281 C163.4875,7.9281 164.7136,9.1542 164.7136,10.6667 Z" />
            <Path className="chartFill0" position="absolute" left="0px" top="0px" width="244.975px" height="127px" viewBox="0 0 244.975 127" stroke="none" d="M64.7136,46.0833 C64.7136,47.5958 63.4875,48.8219 61.975,48.8219 C60.4625,48.8219 59.2364,47.5958 59.2364,46.0833 C59.2364,44.5708 60.4625,43.3447 61.975,43.3447 C63.4875,43.3447 64.7136,44.5708 64.7136,46.0833 Z M97.9253,48.4444 C97.9253,49.9569 96.6992,51.1831 95.1867,51.1831 C93.6742,51.1831 92.4481,49.9569 92.4481,48.4444 C92.4481,46.932 93.6742,45.7058 95.1867,45.7058 C96.6992,45.7058 97.9253,46.932 97.9253,48.4444 Z M131.137,40.8889 C131.137,42.4014 129.9109,43.6275 128.3984,43.6275 C126.8859,43.6275 125.6597,42.4014 125.6597,40.8889 C125.6597,39.3764 126.8859,38.1503 128.3984,38.1503 C129.9109,38.1503 131.137,39.3764 131.137,40.8889 Z M164.7136,32.8611 C164.7136,34.3736 163.4875,35.5997 161.975,35.5997 C160.4625,35.5997 159.2364,34.3736 159.2364,32.8611 C159.2364,31.3486 160.4625,30.1225 161.975,30.1225 C163.4875,30.1225 164.7136,31.3486 164.7136,32.8611 Z" />
            <Path className="chartFill0 chartStroke0" position="absolute" left="0px" top="0px" width="244.975px" height="127px" viewBox="0 0 244.975 127" strokeWidth="1.5" d="M194.975,27 C194.975,29.7614 192.7364,32 189.975,32 C187.2136,32 184.975,29.7614 184.975,27 C184.975,24.2386 187.2136,22 189.975,22 C192.7364,22 194.975,24.2386 194.975,27 Z" />
            <Label className="chartLabel" position="absolute" left="199.975px" top="22px" width="24.375px" textAlign="left" fontSize="10px">Itä</Label>
            <Path className="chartFill1 chartStroke1" position="absolute" left="0px" top="0px" width="244.975px" height="127px" viewBox="0 0 244.975 127" strokeWidth="1.5" d="M194.975,45 C194.975,47.7614 192.7364,50 189.975,50 C187.2136,50 184.975,47.7614 184.975,45 C184.975,42.2386 187.2136,40 189.975,40 C192.7364,40 194.975,42.2386 194.975,45 Z" />
            <Label className="chartLabel" position="absolute" left="199.975px" top="40px" width="37.375px" textAlign="left" fontSize="10px">Länsi</Label>
            <Label className="chartTitle" position="absolute" left="183.975px" top="5px" width="48.9px" textAlign="left" fontSize="11px" fontWeight="bold">region</Label>
          </View>
        </View>
          <Label className="caption">66 piirtokomentoa</Label>
        </View>
      </View>
      <View className="row chartRow">
        <View className="chartCell">
          <Label className="subhead">Jaettu enkoodaus · kaksi merkkiä</Label>
          <View className="codeBlock">
            <Label className="codeLine">{"def chart (VlChart.create(rows))"}</Label>
            <Label className="codeLine">{"chart.size(100 85)"}</Label>
            <Label className="codeLine">{"chart.x(\"quarter\").y(\"sales\").color(\"region\")"}</Label>
            <Label className="codeLine">{"chart.area().markOpacity(0.35)"}</Label>
            <Label className="codeLine">{"chart.line()"}</Label>
          </View>
        <View className="chartBox">
          <View className="chart" position="relative" width="244.975px" height="132px">
            <Path className="chartFrame" position="absolute" left="0px" top="0px" width="244.975px" height="132px" viewBox="0 0 244.975 132" fill="none" strokeWidth="1" d="M62.475,10.5 L162.475,10.5 L162.475,95.5 L62.475,95.5 Z" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="244.975px" height="132px" viewBox="0 0 244.975 132" fill="none" strokeWidth="1" d="M62.475,10.5 L62.475,95.5 M95.475,10.5 L95.475,95.5 M128.475,10.5 L128.475,95.5 M162.475,10.5 L162.475,95.5" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="244.975px" height="132px" viewBox="0 0 244.975 132" fill="none" strokeWidth="1" d="M62.475,95.5 L162.475,95.5 M62.475,67.5 L162.475,67.5 M62.475,38.5 L162.475,38.5 M62.475,10.5 L162.475,10.5" />
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="244.975px" height="132px" viewBox="0 0 244.975 132" fill="none" strokeWidth="1" d="M62.475,95.5 L62.475,100.5 M95.475,95.5 L95.475,100.5 M128.475,95.5 L128.475,100.5 M162.475,95.5 L162.475,100.5" />
            <Label className="chartLabel" position="absolute" left="62.475px" top="102.5px" width="32.5px" textAlign="left" fontSize="10px">2016</Label>
            <Label className="chartLabel" position="absolute" left="109.35px" top="102.5px" width="53.125px" textAlign="right" fontSize="10px">October</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="244.975px" height="132px" viewBox="0 0 244.975 132" fill="none" strokeWidth="1" d="M62.475,95.5 L162.475,95.5" />
            <Label className="chartTitle" position="absolute" left="84.45px" top="116.5px" width="56.05px" textAlign="center" fontSize="11px" fontWeight="bold">quarter</Label>
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="244.975px" height="132px" viewBox="0 0 244.975 132" fill="none" strokeWidth="1" d="M62.475,95.5 L57.475,95.5 M62.475,67.5 L57.475,67.5 M62.475,38.5 L57.475,38.5 M62.475,10.5 L57.475,10.5" />
            <Label className="chartLabel" position="absolute" left="42.85px" top="90.5px" width="12.625px" textAlign="right" fontSize="10px">0</Label>
            <Label className="chartLabel" position="absolute" left="29.6px" top="62.167px" width="25.875px" textAlign="right" fontSize="10px">100</Label>
            <Label className="chartLabel" position="absolute" left="29.6px" top="33.833px" width="25.875px" textAlign="right" fontSize="10px">200</Label>
            <Label className="chartLabel" position="absolute" left="29.6px" top="5.5px" width="25.875px" textAlign="right" fontSize="10px">300</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="244.975px" height="132px" viewBox="0 0 244.975 132" fill="none" strokeWidth="1" d="M62.475,95.5 L62.475,10.5" />
            <Label className="chartTitle" position="absolute" left="0px" top="46.4px" width="41.75px" textAlign="center" fontSize="11px" fontWeight="bold" rotate="-90">sales</Label>
            <Path className="chartFill1" position="absolute" left="0px" top="0px" width="244.975px" height="132px" viewBox="0 0 244.975 132" stroke="none" opacity="0.35" d="M61.975,61 L95.1867,53.9167 L128.3984,57.6 L161.975,47.4 L161.975,95 L128.3984,95 L95.1867,95 L61.975,95 Z" />
            <Path className="chartFill0" position="absolute" left="0px" top="0px" width="244.975px" height="132px" viewBox="0 0 244.975 132" stroke="none" opacity="0.35" d="M61.975,34.65 L95.1867,28.9833 L128.3984,28.1333 L161.975,13.1167 L161.975,47.4 L128.3984,57.6 L95.1867,53.9167 L61.975,61 Z" />
            <Path className="chartStroke1" position="absolute" left="0px" top="0px" width="244.975px" height="132px" viewBox="0 0 244.975 132" fill="none" strokeWidth="2" d="M61.975,61 L95.1867,53.9167 L128.3984,57.6 L161.975,47.4" />
            <Path className="chartStroke0" position="absolute" left="0px" top="0px" width="244.975px" height="132px" viewBox="0 0 244.975 132" fill="none" strokeWidth="2" d="M61.975,68.65 L95.1867,70.0667 L128.3984,65.5333 L161.975,60.7167" />
            <Path className="chartFill0 chartStroke0" position="absolute" left="0px" top="0px" width="244.975px" height="132px" viewBox="0 0 244.975 132" strokeWidth="1.5" opacity="0.35" d="M194.975,32 C194.975,34.7614 192.7364,37 189.975,37 C187.2136,37 184.975,34.7614 184.975,32 C184.975,29.2386 187.2136,27 189.975,27 C192.7364,27 194.975,29.2386 194.975,32 Z" />
            <Label className="chartLabel" position="absolute" left="199.975px" top="27px" width="24.375px" textAlign="left" fontSize="10px">Itä</Label>
            <Path className="chartFill1 chartStroke1" position="absolute" left="0px" top="0px" width="244.975px" height="132px" viewBox="0 0 244.975 132" strokeWidth="1.5" opacity="0.35" d="M194.975,50 C194.975,52.7614 192.7364,55 189.975,55 C187.2136,55 184.975,52.7614 184.975,50 C184.975,47.2386 187.2136,45 189.975,45 C192.7364,45 194.975,47.2386 194.975,50 Z" />
            <Label className="chartLabel" position="absolute" left="199.975px" top="45px" width="37.375px" textAlign="left" fontSize="10px">Länsi</Label>
            <Label className="chartTitle" position="absolute" left="183.975px" top="10px" width="48.9px" textAlign="left" fontSize="11px" fontWeight="bold">region</Label>
          </View>
        </View>
          <Label className="caption">64 piirtokomentoa</Label>
        </View>
        <View className="chartCell">
          <Label className="subhead">Ryhmitellyt pylväät</Label>
          <View className="codeBlock">
            <Label className="codeLine">{"def chart (VlChart.create(rows))"}</Label>
            <Label className="codeLine">{"chart.size(100 85)"}</Label>
            <Label className="codeLine">{"def bars (chart.bar())"}</Label>
            <Label className="codeLine">{"bars.x(\"quarter\").timeUnit(\"yearquarter\").type(\"ordinal\")"}</Label>
            <Label className="codeLine">{"bars.y(\"sales\").color(\"region\").xOffset(\"region\")"}</Label>
          </View>
        <View className="chartBox">
          <View className="chart" position="relative" width="240.975px" height="127px">
            <Path className="chartFrame" position="absolute" left="0px" top="0px" width="240.975px" height="127px" viewBox="0 0 240.975 127" fill="none" strokeWidth="1" d="M62.475,5.5 L162.475,5.5 L162.475,90.5 L62.475,90.5 Z" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="240.975px" height="127px" viewBox="0 0 240.975 127" fill="none" strokeWidth="1" d="M62.475,90.5 L162.475,90.5 M62.475,66.5 L162.475,66.5 M62.475,43.5 L162.475,43.5 M62.475,19.5 L162.475,19.5" />
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="240.975px" height="127px" viewBox="0 0 240.975 127" fill="none" strokeWidth="1" d="M76.475,90.5 L76.475,95.5 M100.475,90.5 L100.475,95.5 M123.475,90.5 L123.475,95.5 M147.475,90.5 L147.475,95.5" />
            <Label className="chartLabel" position="absolute" left="51.073px" top="97.5px" width="50.375px" textAlign="center" fontSize="10px">2016 Q1</Label>
            <Label className="chartLabel" position="absolute" left="122.502px" top="97.5px" width="50.375px" textAlign="center" fontSize="10px">2016 Q4</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="240.975px" height="127px" viewBox="0 0 240.975 127" fill="none" strokeWidth="1" d="M62.475,90.5 L162.475,90.5" />
            <Label className="chartTitle" position="absolute" left="37.219px" top="111.5px" width="150.512px" textAlign="center" fontSize="11px" fontWeight="bold">quarter (year-quarter)</Label>
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="240.975px" height="127px" viewBox="0 0 240.975 127" fill="none" strokeWidth="1" d="M62.475,90.5 L57.475,90.5 M62.475,66.5 L57.475,66.5 M62.475,43.5 L57.475,43.5 M62.475,19.5 L57.475,19.5" />
            <Label className="chartLabel" position="absolute" left="42.85px" top="85.5px" width="12.625px" textAlign="right" fontSize="10px">0</Label>
            <Label className="chartLabel" position="absolute" left="36.225px" top="61.889px" width="19.25px" textAlign="right" fontSize="10px">50</Label>
            <Label className="chartLabel" position="absolute" left="29.6px" top="38.278px" width="25.875px" textAlign="right" fontSize="10px">100</Label>
            <Label className="chartLabel" position="absolute" left="29.6px" top="14.667px" width="25.875px" textAlign="right" fontSize="10px">150</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="240.975px" height="127px" viewBox="0 0 240.975 127" fill="none" strokeWidth="1" d="M62.475,90.5 L62.475,5.5" />
            <Label className="chartTitle" position="absolute" left="0px" top="41.4px" width="41.75px" textAlign="center" fontSize="11px" fontWeight="bold" rotate="-90">sales</Label>
            <Path className="chartFill1" position="absolute" left="0px" top="0px" width="240.975px" height="127px" viewBox="0 0 240.975 127" stroke="none" d="M76.2607,33.3333 L85.7845,33.3333 L85.7845,90 L76.2607,90 Z M100.0702,21.5278 L109.594,21.5278 L109.594,90 L100.0702,90 Z M123.8798,27.6667 L133.4036,27.6667 L133.4036,90 L123.8798,90 Z M147.6893,10.6667 L157.2131,10.6667 L157.2131,90 L147.6893,90 Z" />
            <Path className="chartFill0" position="absolute" left="0px" top="0px" width="240.975px" height="127px" viewBox="0 0 240.975 127" stroke="none" d="M66.7369,46.0833 L76.2607,46.0833 L76.2607,90 L66.7369,90 Z M90.5464,48.4444 L100.0702,48.4444 L100.0702,90 L90.5464,90 Z M114.356,40.8889 L123.8798,40.8889 L123.8798,90 L114.356,90 Z M138.1655,32.8611 L147.6893,32.8611 L147.6893,90 L138.1655,90 Z" />
            <Path className="chartFill0" position="absolute" left="0px" top="0px" width="240.975px" height="127px" viewBox="0 0 240.975 127" stroke="none" d="M180.975,22 L190.975,22 L190.975,32 L180.975,32 Z" />
            <Label className="chartLabel" position="absolute" left="195.975px" top="22px" width="24.375px" textAlign="left" fontSize="10px">Itä</Label>
            <Path className="chartFill1" position="absolute" left="0px" top="0px" width="240.975px" height="127px" viewBox="0 0 240.975 127" stroke="none" d="M180.975,35 L190.975,35 L190.975,45 L180.975,45 Z" />
            <Label className="chartLabel" position="absolute" left="195.975px" top="35px" width="37.375px" textAlign="left" fontSize="10px">Länsi</Label>
            <Label className="chartTitle" position="absolute" left="179.975px" top="5px" width="48.9px" textAlign="left" fontSize="11px" fontWeight="bold">region</Label>
          </View>
        </View>
          <Label className="caption">54 piirtokomentoa</Label>
        </View>
      </View>
    </View>
  );
}

export default render;
