// GENERATED by gallery/vela/tools/vela_evg.rgr — do not edit by hand.
//
// Each chart below is an unmodified Vega specification, compiled from a
// Vega-Lite example, run through the Vela runtime and drawn with the EVG
// vector layer: every gridline, bar, wedge and label is path data and text
// this repository computed, in all three targets.
//
// Regenerate with:  npm run vela:showcase

import { View, Label, Path } from "./evg_types";

function render() {
  return (
    <View className="page">
      <Label className="title">Lisää</Label>
      <View className="rule" />
      <View className="row chartRow">
        <View className="chartCell">
        <View className="chartBox">
          <View className="chart" position="relative" width="242px" height="118px">
            <Path className="chartFrame" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" fill="none" strokeWidth="1" opacity="0.4" d="M35.5,5.5 L185.5,5.5 L185.5,83.5 L35.5,83.5 Z" />
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" fill="none" strokeWidth="1" d="M43.5,83.5 L43.5,88.5 M60.5,83.5 L60.5,88.5 M76.5,83.5 L76.5,88.5 M93.5,83.5 L93.5,88.5 M110.5,83.5 L110.5,88.5 M126.5,83.5 L126.5,88.5 M143.5,83.5 L143.5,88.5 M160.5,83.5 L160.5,88.5 M176.5,83.5 L176.5,88.5" />
            <Label className="chartLabel" position="absolute" left="36.271px" top="84.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">A</Label>
            <Label className="chartLabel" position="absolute" left="52.938px" top="84.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">B</Label>
            <Label className="chartLabel" position="absolute" left="69.604px" top="84.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">C</Label>
            <Label className="chartLabel" position="absolute" left="86.271px" top="84.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">D</Label>
            <Label className="chartLabel" position="absolute" left="102.938px" top="84.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">E</Label>
            <Label className="chartLabel" position="absolute" left="119.604px" top="84.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">F</Label>
            <Label className="chartLabel" position="absolute" left="136.271px" top="84.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">G</Label>
            <Label className="chartLabel" position="absolute" left="152.938px" top="84.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">H</Label>
            <Label className="chartLabel" position="absolute" left="169.604px" top="84.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">I</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" fill="none" strokeWidth="1" d="M35.5,83.5 L185.5,83.5" />
            <Label className="chartTitle" position="absolute" left="103.925px" top="102.5px" width="13.15px" textAlign="center" fontSize="11px" fontWeight="bold">a</Label>
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" fill="none" strokeWidth="1" d="M35.5,24.5 L30.5,24.5 M35.5,63.5 L30.5,63.5" />
            <Label className="chartLabel" position="absolute" left="16px" top="19.5px" width="12.5px" textAlign="right" fontSize="10px">x</Label>
            <Label className="chartLabel" position="absolute" left="16px" top="58.5px" width="12.5px" textAlign="right" fontSize="10px">y</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" fill="none" strokeWidth="1" d="M35.5,5.5 L35.5,83.5" />
            <Label className="chartTitle" position="absolute" left="3.325px" top="37.9px" width="13.15px" textAlign="center" fontSize="11px" fontWeight="bold" rotate="-90">g</Label>
            <Path className="chartFill0" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M35,5 L51.6667,5 L51.6667,44 L35,44 Z" />
            <Path className="chartFill1" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M51.6667,44 L68.3333,44 L68.3333,83 L51.6667,83 Z" />
            <Path className="chartFill2" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M68.3333,5 L85,5 L85,44 L68.3333,44 Z" />
            <Path className="chartFill3" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M85,44 L101.6667,44 L101.6667,83 L85,83 Z" />
            <Path className="chartFill4" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M101.6667,5 L118.3333,5 L118.3333,44 L101.6667,44 Z" />
            <Path className="chartFill5" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M118.3333,44 L135,44 L135,83 L118.3333,83 Z" />
            <Path className="chartFill6" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M135,5 L151.6667,5 L151.6667,44 L135,44 Z" />
            <Path className="chartFill7" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M151.6667,44 L168.3333,44 L168.3333,83 L151.6667,83 Z" />
            <Path className="chartFill8" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M168.3333,5 L185,5 L185,44 L168.3333,44 Z" />
            <Path className="chartFill6" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,97.05 L219,97.05 L219,99 L203,99 Z" />
            <Path className="chartFill9" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,95.1 L219,95.1 L219,97.05 L203,97.05 Z" />
            <Path className="chartFill10" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,93.15 L219,93.15 L219,95.1 L203,95.1 Z" />
            <Path className="chartFill11" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,91.2 L219,91.2 L219,93.15 L203,93.15 Z" />
            <Path className="chartFill12" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,89.25 L219,89.25 L219,91.2 L203,91.2 Z" />
            <Path className="chartFill0" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,87.3 L219,87.3 L219,89.25 L203,89.25 Z" />
            <Path className="chartFill13" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,85.35 L219,85.35 L219,87.3 L203,87.3 Z" />
            <Path className="chartFill14" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,83.4 L219,83.4 L219,85.35 L203,85.35 Z" />
            <Path className="chartFill15" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,81.45 L219,81.45 L219,83.4 L203,83.4 Z" />
            <Path className="chartFill16" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,79.5 L219,79.5 L219,81.45 L203,81.45 Z" />
            <Path className="chartFill17" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,77.55 L219,77.55 L219,79.5 L203,79.5 Z" />
            <Path className="chartFill18" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,75.6 L219,75.6 L219,77.55 L203,77.55 Z" />
            <Path className="chartFill19" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,73.65 L219,73.65 L219,75.6 L203,75.6 Z" />
            <Path className="chartFill20" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,71.7 L219,71.7 L219,73.65 L203,73.65 Z" />
            <Path className="chartFill21" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,69.75 L219,69.75 L219,71.7 L203,71.7 Z" />
            <Path className="chartFill22" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,67.8 L219,67.8 L219,69.75 L203,69.75 Z" />
            <Path className="chartFill23" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,65.85 L219,65.85 L219,67.8 L203,67.8 Z" />
            <Path className="chartFill24" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,63.9 L219,63.9 L219,65.85 L203,65.85 Z" />
            <Path className="chartFill25" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,61.95 L219,61.95 L219,63.9 L203,63.9 Z" />
            <Path className="chartFill26" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,60 L219,60 L219,61.95 L203,61.95 Z" />
            <Path className="chartFill1" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,58.05 L219,58.05 L219,60 L203,60 Z" />
            <Path className="chartFill27" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,56.1 L219,56.1 L219,58.05 L203,58.05 Z" />
            <Path className="chartFill28" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,54.15 L219,54.15 L219,56.1 L203,56.1 Z" />
            <Path className="chartFill29" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,52.2 L219,52.2 L219,54.15 L203,54.15 Z" />
            <Path className="chartFill30" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,50.25 L219,50.25 L219,52.2 L203,52.2 Z" />
            <Path className="chartFill31" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,48.3 L219,48.3 L219,50.25 L203,50.25 Z" />
            <Path className="chartFill32" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,46.35 L219,46.35 L219,48.3 L203,48.3 Z" />
            <Path className="chartFill33" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,44.4 L219,44.4 L219,46.35 L203,46.35 Z" />
            <Path className="chartFill34" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,42.45 L219,42.45 L219,44.4 L203,44.4 Z" />
            <Path className="chartFill35" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,40.5 L219,40.5 L219,42.45 L203,42.45 Z" />
            <Path className="chartFill36" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,38.55 L219,38.55 L219,40.5 L203,40.5 Z" />
            <Path className="chartFill37" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,36.6 L219,36.6 L219,38.55 L203,38.55 Z" />
            <Path className="chartFill38" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,34.65 L219,34.65 L219,36.6 L203,36.6 Z" />
            <Path className="chartFill39" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,32.7 L219,32.7 L219,34.65 L203,34.65 Z" />
            <Path className="chartFill40" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,30.75 L219,30.75 L219,32.7 L203,32.7 Z" />
            <Path className="chartFill41" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,28.8 L219,28.8 L219,30.75 L203,30.75 Z" />
            <Path className="chartFill42" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,26.85 L219,26.85 L219,28.8 L203,28.8 Z" />
            <Path className="chartFill43" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,24.9 L219,24.9 L219,26.85 L203,26.85 Z" />
            <Path className="chartFill44" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,22.95 L219,22.95 L219,24.9 L203,24.9 Z" />
            <Path className="chartFill45" position="absolute" left="0px" top="0px" width="242px" height="118px" viewBox="0 0 242 118" stroke="none" d="M203,21 L219,21 L219,22.95 L203,22.95 Z" />
            <Label className="chartLabel" position="absolute" left="221px" top="89px" width="19.25px" textAlign="left" fontSize="10px">19</Label>
            <Label className="chartLabel" position="absolute" left="221px" top="21px" width="19.25px" textAlign="left" fontSize="10px">91</Label>
            <Label className="chartTitle" position="absolute" left="203px" top="5px" width="13.15px" textAlign="left" fontSize="11px" fontWeight="bold">b</Label>
          </View>
        </View>
          <Label className="caption">Lämpökartta · liukuväri · 89 komentoa</Label>
        </View>
        <View className="chartCell">
        <View className="chartBox">
          <View className="chart" position="relative" width="206px" height="123px">
            <Path className="chartFrame" position="absolute" left="0px" top="0px" width="206px" height="123px" viewBox="0 0 206 123" fill="none" strokeWidth="1" opacity="0.4" d="M51.5,10.5 L201.5,10.5 L201.5,88.5 L51.5,88.5 Z" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="206px" height="123px" viewBox="0 0 206 123" fill="none" strokeWidth="1" opacity="0.25" d="M51.5,88.5 L201.5,88.5 M51.5,49.5 L201.5,49.5 M51.5,10.5 L201.5,10.5" />
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="206px" height="123px" viewBox="0 0 206 123" fill="none" strokeWidth="1" d="M88.5,88.5 L88.5,93.5 M163.5,88.5 L163.5,93.5" />
            <Label className="chartLabel" position="absolute" left="82.25px" top="89.5px" width="12.5px" textAlign="center" fontSize="10px" rotate="270">x</Label>
            <Label className="chartLabel" position="absolute" left="157.25px" top="89.5px" width="12.5px" textAlign="center" fontSize="10px" rotate="270">y</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="206px" height="123px" viewBox="0 0 206 123" fill="none" strokeWidth="1" d="M51.5,88.5 L201.5,88.5" />
            <Label className="chartTitle" position="absolute" left="119.925px" top="107.5px" width="13.15px" textAlign="center" fontSize="11px" fontWeight="bold">g</Label>
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="206px" height="123px" viewBox="0 0 206 123" fill="none" strokeWidth="1" d="M51.5,88.5 L46.5,88.5 M51.5,49.5 L46.5,49.5 M51.5,10.5 L46.5,10.5" />
            <Label className="chartLabel" position="absolute" left="31.875px" top="83.5px" width="12.625px" textAlign="right" fontSize="10px">0</Label>
            <Label className="chartLabel" position="absolute" left="25.25px" top="44.5px" width="19.25px" textAlign="right" fontSize="10px">50</Label>
            <Label className="chartLabel" position="absolute" left="18.625px" top="5.5px" width="25.875px" textAlign="right" fontSize="10px">100</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="206px" height="123px" viewBox="0 0 206 123" fill="none" strokeWidth="1" d="M51.5,88.5 L51.5,10.5" />
            <Label className="chartTitle" position="absolute" left="3.325px" top="42.9px" width="13.15px" textAlign="center" fontSize="11px" fontWeight="bold" rotate="-90">b</Label>
            <Path className="chartStroke46" position="absolute" left="0px" top="0px" width="206px" height="123px" viewBox="0 0 206 123" fill="none" strokeWidth="1" d="M88.5,73.18 L88.5,66.16 M163.5,46.66 L163.5,45.49 M88.5,47.44 L88.5,24.82 M163.5,19.36 L163.5,17.02" />
            <Path className="chartFill47" position="absolute" left="0px" top="0px" width="206px" height="123px" viewBox="0 0 206 123" stroke="none" d="M81.5,47.44 L95.5,47.44 L95.5,66.16 L81.5,66.16 Z M156.5,19.36 L170.5,19.36 L170.5,45.49 L156.5,45.49 Z" />
            <Path className="chartFill48" position="absolute" left="0px" top="0px" width="206px" height="123px" viewBox="0 0 206 123" stroke="none" opacity="0.7" d="M81.5,53.96 L95.5,53.96 L95.5,54.96 L81.5,54.96 Z M156.5,32.12 L170.5,32.12 L170.5,33.12 L156.5,33.12 Z" />
          </View>
        </View>
          <Label className="caption">Laatikkojana · 34 komentoa</Label>
        </View>
      </View>
      <View className="row chartRow">
        <View className="chartCell">
        <View className="chartBox">
          <View className="chart" position="relative" width="252px" height="125px">
            <Path className="chartFrame" position="absolute" left="0px" top="0px" width="252px" height="125px" viewBox="0 0 252 125" fill="none" strokeWidth="1" opacity="0.4" d="M51.5,10.5 L201.5,10.5 L201.5,88.5 L51.5,88.5 Z" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="252px" height="125px" viewBox="0 0 252 125" fill="none" strokeWidth="1" opacity="0.25" d="M70.5,10.5 L70.5,88.5 M107.5,10.5 L107.5,88.5 M145.5,10.5 L145.5,88.5 M182.5,10.5 L182.5,88.5" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="252px" height="125px" viewBox="0 0 252 125" fill="none" strokeWidth="1" opacity="0.25" d="M51.5,88.5 L201.5,88.5 M51.5,49.5 L201.5,49.5 M51.5,10.5 L201.5,10.5" />
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="252px" height="125px" viewBox="0 0 252 125" fill="none" strokeWidth="1" d="M70.5,88.5 L70.5,93.5 M107.5,88.5 L107.5,93.5 M145.5,88.5 L145.5,93.5 M182.5,88.5 L182.5,93.5" />
            <Label className="chartLabel" position="absolute" left="63.938px" top="95.5px" width="12.625px" textAlign="center" fontSize="10px">2</Label>
            <Label className="chartLabel" position="absolute" left="101.438px" top="95.5px" width="12.625px" textAlign="center" fontSize="10px">4</Label>
            <Label className="chartLabel" position="absolute" left="138.938px" top="95.5px" width="12.625px" textAlign="center" fontSize="10px">6</Label>
            <Label className="chartLabel" position="absolute" left="176.438px" top="95.5px" width="12.625px" textAlign="center" fontSize="10px">8</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="252px" height="125px" viewBox="0 0 252 125" fill="none" strokeWidth="1" d="M51.5,88.5 L201.5,88.5" />
            <Label className="chartTitle" position="absolute" left="119.925px" top="109.5px" width="13.15px" textAlign="center" fontSize="11px" fontWeight="bold">c</Label>
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="252px" height="125px" viewBox="0 0 252 125" fill="none" strokeWidth="1" d="M51.5,88.5 L46.5,88.5 M51.5,49.5 L46.5,49.5 M51.5,10.5 L46.5,10.5" />
            <Label className="chartLabel" position="absolute" left="31.875px" top="83.5px" width="12.625px" textAlign="right" fontSize="10px">0</Label>
            <Label className="chartLabel" position="absolute" left="25.25px" top="44.5px" width="19.25px" textAlign="right" fontSize="10px">50</Label>
            <Label className="chartLabel" position="absolute" left="18.625px" top="5.5px" width="25.875px" textAlign="right" fontSize="10px">100</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="252px" height="125px" viewBox="0 0 252 125" fill="none" strokeWidth="1" d="M51.5,88.5 L51.5,10.5" />
            <Label className="chartTitle" position="absolute" left="3.325px" top="42.9px" width="13.15px" textAlign="center" fontSize="11px" fontWeight="bold" rotate="-90">b</Label>
            <Path className="chartStroke47" position="absolute" left="0px" top="0px" width="252px" height="125px" viewBox="0 0 252 125" fill="none" strokeWidth="2" d="M69.75,54.46 L88.5,47.44 L107.25,24.82 L126,66.16 L182.25,73.18" />
            <Path className="chartStroke49" position="absolute" left="0px" top="0px" width="252px" height="125px" viewBox="0 0 252 125" fill="none" strokeWidth="2" d="M51,20.14 L144.75,46.66 L163.5,17.02 L201,45.1" />
            <Path className="chartStroke47" position="absolute" left="0px" top="0px" width="252px" height="125px" viewBox="0 0 252 125" fill="none" strokeWidth="1.5" d="M224,32 L234,32" />
            <Label className="chartLabel" position="absolute" left="239px" top="27px" width="12.5px" textAlign="left" fontSize="10px">x</Label>
            <Path className="chartStroke49" position="absolute" left="0px" top="0px" width="252px" height="125px" viewBox="0 0 252 125" fill="none" strokeWidth="1.5" d="M224,45 L234,45" />
            <Label className="chartLabel" position="absolute" left="239px" top="40px" width="12.5px" textAlign="left" fontSize="10px">y</Label>
            <Label className="chartTitle" position="absolute" left="223px" top="10px" width="13.15px" textAlign="left" fontSize="11px" fontWeight="bold">g</Label>
          </View>
        </View>
          <Label className="caption">Monisarjainen viiva · 55 komentoa</Label>
        </View>
        <View className="chartCell">
        <View className="chartBox">
          <View className="chart" position="relative" width="248px" height="125px">
            <Path className="chartFrame" position="absolute" left="0px" top="0px" width="248px" height="125px" viewBox="0 0 248 125" fill="none" strokeWidth="1" opacity="0.4" d="M51.5,10.5 L201.5,10.5 L201.5,88.5 L51.5,88.5 Z" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="248px" height="125px" viewBox="0 0 248 125" fill="none" strokeWidth="1" opacity="0.25" d="M70.5,10.5 L70.5,88.5 M107.5,10.5 L107.5,88.5 M145.5,10.5 L145.5,88.5 M182.5,10.5 L182.5,88.5" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="248px" height="125px" viewBox="0 0 248 125" fill="none" strokeWidth="1" opacity="0.25" d="M51.5,88.5 L201.5,88.5 M51.5,49.5 L201.5,49.5 M51.5,10.5 L201.5,10.5" />
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="248px" height="125px" viewBox="0 0 248 125" fill="none" strokeWidth="1" d="M70.5,88.5 L70.5,93.5 M107.5,88.5 L107.5,93.5 M145.5,88.5 L145.5,93.5 M182.5,88.5 L182.5,93.5" />
            <Label className="chartLabel" position="absolute" left="63.938px" top="95.5px" width="12.625px" textAlign="center" fontSize="10px">2</Label>
            <Label className="chartLabel" position="absolute" left="101.438px" top="95.5px" width="12.625px" textAlign="center" fontSize="10px">4</Label>
            <Label className="chartLabel" position="absolute" left="138.938px" top="95.5px" width="12.625px" textAlign="center" fontSize="10px">6</Label>
            <Label className="chartLabel" position="absolute" left="176.438px" top="95.5px" width="12.625px" textAlign="center" fontSize="10px">8</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="248px" height="125px" viewBox="0 0 248 125" fill="none" strokeWidth="1" d="M51.5,88.5 L201.5,88.5" />
            <Label className="chartTitle" position="absolute" left="119.925px" top="109.5px" width="13.15px" textAlign="center" fontSize="11px" fontWeight="bold">c</Label>
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="248px" height="125px" viewBox="0 0 248 125" fill="none" strokeWidth="1" d="M51.5,88.5 L46.5,88.5 M51.5,49.5 L46.5,49.5 M51.5,10.5 L46.5,10.5" />
            <Label className="chartLabel" position="absolute" left="31.875px" top="83.5px" width="12.625px" textAlign="right" fontSize="10px">0</Label>
            <Label className="chartLabel" position="absolute" left="25.25px" top="44.5px" width="19.25px" textAlign="right" fontSize="10px">50</Label>
            <Label className="chartLabel" position="absolute" left="18.625px" top="5.5px" width="25.875px" textAlign="right" fontSize="10px">100</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="248px" height="125px" viewBox="0 0 248 125" fill="none" strokeWidth="1" d="M51.5,88.5 L51.5,10.5" />
            <Label className="chartTitle" position="absolute" left="3.325px" top="42.9px" width="13.15px" textAlign="center" fontSize="11px" fontWeight="bold" rotate="-90">b</Label>
            <Path className="chartFill47" position="absolute" left="0px" top="0px" width="248px" height="125px" viewBox="0 0 248 125" stroke="none" d="M51,18.58 L69.75,35.74 L88.5,32.23 L107.25,20.92 L126,41.59 L144.75,31.84 L163.5,17.02 L182.25,45.1 L201,31.06 L201,31.06 L182.25,59.92 L163.5,17.02 L144.75,31.84 L126,63.43 L107.25,84.1 L88.5,72.79 L69.75,69.28 L51,18.58 Z" />
            <Path className="chartFill49" position="absolute" left="0px" top="0px" width="248px" height="125px" viewBox="0 0 248 125" stroke="none" d="M51,18.58 L69.75,69.28 L88.5,72.79 L107.25,84.1 L126,63.43 L144.75,31.84 L163.5,17.02 L182.25,59.92 L201,31.06 L201,73.96 L182.25,59.92 L163.5,88 L144.75,73.18 L126,63.43 L107.25,84.1 L88.5,72.79 L69.75,69.28 L51,86.44 Z" />
            <Path className="chartFill47" position="absolute" left="0px" top="0px" width="248px" height="125px" viewBox="0 0 248 125" stroke="none" d="M230,32 C230,34.7614 227.7614,37 225,37 C222.2386,37 220,34.7614 220,32 C220,29.2386 222.2386,27 225,27 C227.7614,27 230,29.2386 230,32 Z" />
            <Label className="chartLabel" position="absolute" left="235px" top="27px" width="12.5px" textAlign="left" fontSize="10px">x</Label>
            <Path className="chartFill49" position="absolute" left="0px" top="0px" width="248px" height="125px" viewBox="0 0 248 125" stroke="none" d="M230,45 C230,47.7614 227.7614,50 225,50 C222.2386,50 220,47.7614 220,45 C220,42.2386 222.2386,40 225,40 C227.7614,40 230,42.2386 230,45 Z" />
            <Label className="chartLabel" position="absolute" left="235px" top="40px" width="12.5px" textAlign="left" fontSize="10px">y</Label>
            <Label className="chartTitle" position="absolute" left="219px" top="10px" width="13.15px" textAlign="left" fontSize="11px" fontWeight="bold">g</Label>
          </View>
        </View>
          <Label className="caption">Virtakaavio · 55 komentoa</Label>
        </View>
      </View>
      <View className="row chartRow">
        <View className="chartCell">
        <View className="chartBox">
          <View className="chart" position="relative" width="210px" height="125px">
            <Path className="chartFrame" position="absolute" left="0px" top="0px" width="210px" height="125px" viewBox="0 0 210 125" fill="none" strokeWidth="1" opacity="0.4" d="M51.5,10.5 L201.5,10.5 L201.5,88.5 L51.5,88.5 Z" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="210px" height="125px" viewBox="0 0 210 125" fill="none" strokeWidth="1" opacity="0.25" d="M51.5,10.5 L51.5,88.5 M107.5,10.5 L107.5,88.5 M163.5,10.5 L163.5,88.5" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="210px" height="125px" viewBox="0 0 210 125" fill="none" strokeWidth="1" opacity="0.25" d="M51.5,88.5 L201.5,88.5 M51.5,49.5 L201.5,49.5 M51.5,10.5 L201.5,10.5" />
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="210px" height="125px" viewBox="0 0 210 125" fill="none" strokeWidth="1" d="M51.5,88.5 L51.5,93.5 M107.5,88.5 L107.5,93.5 M163.5,88.5 L163.5,93.5" />
            <Label className="chartLabel" position="absolute" left="51.5px" top="95.5px" width="32.5px" textAlign="left" fontSize="10px">2024</Label>
            <Label className="chartLabel" position="absolute" left="87.38px" top="95.5px" width="40.125px" textAlign="center" fontSize="10px">April</Label>
            <Label className="chartLabel" position="absolute" left="146.573px" top="95.5px" width="33.625px" textAlign="center" fontSize="10px">July</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="210px" height="125px" viewBox="0 0 210 125" fill="none" strokeWidth="1" d="M51.5,88.5 L201.5,88.5" />
            <Label className="chartTitle" position="absolute" left="119.925px" top="109.5px" width="13.15px" textAlign="center" fontSize="11px" fontWeight="bold">t</Label>
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="210px" height="125px" viewBox="0 0 210 125" fill="none" strokeWidth="1" d="M51.5,88.5 L46.5,88.5 M51.5,49.5 L46.5,49.5 M51.5,10.5 L46.5,10.5" />
            <Label className="chartLabel" position="absolute" left="31.875px" top="83.5px" width="12.625px" textAlign="right" fontSize="10px">0</Label>
            <Label className="chartLabel" position="absolute" left="25.25px" top="44.5px" width="19.25px" textAlign="right" fontSize="10px">50</Label>
            <Label className="chartLabel" position="absolute" left="18.625px" top="5.5px" width="25.875px" textAlign="right" fontSize="10px">100</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="210px" height="125px" viewBox="0 0 210 125" fill="none" strokeWidth="1" d="M51.5,88.5 L51.5,10.5" />
            <Label className="chartTitle" position="absolute" left="3.325px" top="42.9px" width="13.15px" textAlign="center" fontSize="11px" fontWeight="bold" rotate="-90">b</Label>
            <Path className="chartStroke47" position="absolute" left="0px" top="0px" width="210px" height="125px" viewBox="0 0 210 125" fill="none" strokeWidth="2" d="M51,66.16 L70.0574,45.1 L87.8852,54.46 L106.9426,17.02 L125.3852,24.82 L144.4426,46.66 L162.8852,73.18 L181.9426,20.14 L201,47.44" />
          </View>
        </View>
          <Label className="caption">Aika-akseli · 34 komentoa</Label>
        </View>
        <View className="chartCell">
        <View className="chartBox">
          <View className="chart" position="relative" width="163.125px" height="141px">
            <Path className="chartFill47" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M60,5 L62.7146,5.067 L65.4226,5.268 L68.1174,5.6023 L70.7924,6.0693 L73.4411,6.6677 L76.057,7.3961 L78.6338,8.2527 L70.1639,31.7742 L68.7584,31.307 L67.3315,30.9096 L65.8868,30.5832 L64.4277,30.3285 L62.9578,30.1462 L61.4807,30.0366 L60,30 Z" />
            <Path className="chartFill49" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M78.6338,8.2527 L81.1204,9.2168 L83.5573,10.3004 L85.9388,11.5008 L88.2594,12.8152 L90.5135,14.2406 L92.6959,15.7735 L94.8013,17.4105 L96.825,19.1476 L98.7621,20.9807 L100.608,22.9057 L102.3584,24.9178 L104.0093,27.0124 L105.5567,29.1846 L106.9969,31.4292 L85.6347,44.4159 L84.8491,43.1916 L84.0051,42.0068 L83.1046,40.8642 L82.1498,39.7667 L81.1429,38.7168 L80.0864,37.7169 L78.9826,36.7694 L77.8341,35.8765 L76.6437,35.0403 L75.4142,34.2628 L74.1485,33.5459 L72.8494,32.8911 L71.5202,32.3001 L70.1639,31.7742 Z" />
            <Path className="chartFill50" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M106.9969,31.4292 L108.3203,33.7294 L109.5313,36.0907 L110.6269,38.5077 L111.6047,40.9748 L112.4623,43.4861 L113.1978,46.0359 L113.8094,48.6182 L114.2958,51.227 L114.6558,53.8562 L114.8885,56.4997 L114.9935,59.1514 L89.9964,59.5371 L89.9392,58.0907 L89.8122,56.6488 L89.6159,55.2147 L89.3506,53.7917 L89.017,52.3832 L88.6158,50.9924 L88.148,49.6226 L87.6147,48.2769 L87.0171,46.9586 L86.3565,45.6706 L85.6347,44.4159 Z" />
            <Path className="chartFill51" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M114.9935,59.1514 L114.9693,61.8372 L114.8141,64.5186 L114.5281,67.1893 L114.1121,69.8428 L113.567,72.4729 L112.8942,75.0732 L112.0953,77.6375 L111.1721,80.1598 L110.1268,82.634 L108.9621,85.0543 L107.6805,87.4147 L106.2853,89.7098 L104.7796,91.9341 L103.1672,94.0822 L101.4518,96.149 L99.6375,98.1296 L97.7288,100.0192 L95.73,101.8135 L93.6461,103.508 L91.4819,105.0987 L89.2426,106.5819 L86.9335,107.954 L84.5603,109.2117 L73.3965,86.8428 L74.691,86.1567 L75.9505,85.4083 L77.1719,84.5993 L78.3524,83.7316 L79.4891,82.8073 L80.5793,81.8287 L81.6205,80.798 L82.6101,79.7176 L83.5457,78.5903 L84.4252,77.4186 L85.2465,76.2054 L86.0076,74.9535 L86.7066,73.666 L87.3419,72.3458 L87.912,70.9963 L88.4156,69.6205 L88.8514,68.2217 L89.2184,66.8034 L89.5157,65.3688 L89.7426,63.9214 L89.8986,62.4647 L89.9833,61.0021 L89.9964,59.5371 Z" />
            <Path className="chartFill52" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M84.5603,109.2117 L82.0703,110.3776 L79.5252,111.4176 L76.9314,112.329 L74.2952,113.1098 L71.6232,113.7578 L68.9223,114.2715 L66.199,114.6495 L63.4603,114.891 L60.7129,114.9954 L57.9637,114.9623 L55.2196,114.7919 L52.4874,114.4845 L49.7741,114.041 L47.0862,113.4625 L44.4307,112.7503 L41.8141,111.9064 L39.2429,110.9327 L36.7235,109.8318 L34.2624,108.6063 L31.8655,107.2594 L44.6539,85.7779 L45.9613,86.5125 L47.3037,87.181 L48.6779,87.7815 L50.0804,88.3126 L51.5077,88.7729 L52.9561,89.1613 L54.4222,89.4769 L55.9022,89.7188 L57.3925,89.8865 L58.8893,89.9794 L60.3888,89.9975 L61.8874,89.9406 L63.3813,89.8088 L64.8667,89.6026 L66.3399,89.3224 L67.7974,88.969 L69.2353,88.5431 L70.6501,88.0459 L72.0384,87.4787 L73.3965,86.8428 Z" />
            <Path className="chartFill53" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M31.8655,107.2594 L29.6885,105.8935 L27.5777,104.4274 L25.5377,102.8643 L23.573,101.2076 L21.6877,99.461 L19.8861,97.6282 L18.1722,95.7132 L16.5495,93.7202 L15.0217,91.6537 L13.5921,89.518 L12.2639,87.3178 L11.0399,85.058 L9.9227,82.7435 L8.915,80.3793 L32.1354,71.116 L32.6851,72.4056 L33.2945,73.668 L33.9621,74.9006 L34.6866,76.1007 L35.4664,77.2656 L36.2997,78.3929 L37.1848,79.4799 L38.1197,80.5245 L39.1024,81.5242 L40.1307,82.4769 L41.2024,83.3805 L42.3151,84.2331 L43.4665,85.0328 L44.6539,85.7779 Z" />
            <Path className="chartFill54" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M8.915,80.3793 L8.0155,77.9615 L7.2305,75.5042 L6.5615,73.0127 L6.0101,70.4926 L5.5775,67.9495 L30.315,64.3361 L30.551,65.7233 L30.8517,67.0978 L31.2166,68.4568 L31.6448,69.7972 L32.1354,71.116 Z" />
            <Path className="chartFill55" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M5.5775,67.9495 L5.2545,65.2844 L5.0618,62.6067 L5.0001,59.9228 L5.0693,57.2392 L5.2695,54.562 L5.6,51.8979 L6.0602,49.253 L6.6489,46.6338 L7.3646,44.0463 L8.2058,41.4969 L9.1704,38.9916 L10.2561,36.5364 L11.4603,34.137 L12.7801,31.7992 L14.2125,29.5287 L15.7539,27.3307 L17.4007,25.2106 L19.1491,23.1734 L20.9947,21.2239 L22.9333,19.3667 L24.9602,17.6064 L27.0706,15.9471 L42.0385,35.9712 L40.8874,36.8762 L39.7818,37.8364 L38.7244,38.8494 L37.7177,39.9127 L36.764,41.024 L35.8658,42.1804 L35.025,43.3793 L34.2437,44.6178 L33.5238,45.8929 L32.867,47.2016 L32.2748,48.5409 L31.7486,49.9074 L31.2898,51.298 L30.8994,52.7093 L30.5783,54.138 L30.3273,55.5807 L30.147,57.0338 L30.0378,58.4941 L30,59.9579 L30.0337,61.4219 L30.1388,62.8824 L30.315,64.3361 Z" />
            <Path className="chartFill56" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M27.0706,15.9471 L29.2851,14.3755 L31.5744,12.9152 L33.933,11.5695 L36.3551,10.342 L38.8349,9.2355 L41.3662,8.2527 L43.943,7.3961 L46.5589,6.6677 L49.2076,6.0693 L51.8826,5.6023 L54.5774,5.268 L57.2854,5.067 L60,5 L60,30 L58.5193,30.0366 L57.0422,30.1462 L55.5723,30.3285 L54.1132,30.5832 L52.6685,30.9096 L51.2416,31.307 L49.8361,31.7742 L48.4554,32.3103 L47.1028,32.9138 L45.7816,33.5834 L44.4951,34.3174 L43.2464,35.1139 L42.0385,35.9712 Z" />
            <Path className="chartFill47" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M144,27 C144,29.7614 141.7614,32 139,32 C136.2386,32 134,29.7614 134,27 C134,24.2386 136.2386,22 139,22 C141.7614,22 144,24.2386 144,27 Z" />
            <Label className="chartLabel" position="absolute" left="149px" top="22px" width="14.125px" textAlign="left" fontSize="10px">A</Label>
            <Path className="chartFill49" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M144,40 C144,42.7614 141.7614,45 139,45 C136.2386,45 134,42.7614 134,40 C134,37.2386 136.2386,35 139,35 C141.7614,35 144,37.2386 144,40 Z" />
            <Label className="chartLabel" position="absolute" left="149px" top="35px" width="14.125px" textAlign="left" fontSize="10px">B</Label>
            <Path className="chartFill50" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M144,53 C144,55.7614 141.7614,58 139,58 C136.2386,58 134,55.7614 134,53 C134,50.2386 136.2386,48 139,48 C141.7614,48 144,50.2386 144,53 Z" />
            <Label className="chartLabel" position="absolute" left="149px" top="48px" width="14.125px" textAlign="left" fontSize="10px">C</Label>
            <Path className="chartFill51" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M144,66 C144,68.7614 141.7614,71 139,71 C136.2386,71 134,68.7614 134,66 C134,63.2386 136.2386,61 139,61 C141.7614,61 144,63.2386 144,66 Z" />
            <Label className="chartLabel" position="absolute" left="149px" top="61px" width="14.125px" textAlign="left" fontSize="10px">D</Label>
            <Path className="chartFill52" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M144,79 C144,81.7614 141.7614,84 139,84 C136.2386,84 134,81.7614 134,79 C134,76.2386 136.2386,74 139,74 C141.7614,74 144,76.2386 144,79 Z" />
            <Label className="chartLabel" position="absolute" left="149px" top="74px" width="14.125px" textAlign="left" fontSize="10px">E</Label>
            <Path className="chartFill53" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M144,92 C144,94.7614 141.7614,97 139,97 C136.2386,97 134,94.7614 134,92 C134,89.2386 136.2386,87 139,87 C141.7614,87 144,89.2386 144,92 Z" />
            <Label className="chartLabel" position="absolute" left="149px" top="87px" width="14.125px" textAlign="left" fontSize="10px">F</Label>
            <Path className="chartFill54" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M144,105 C144,107.7614 141.7614,110 139,110 C136.2386,110 134,107.7614 134,105 C134,102.2386 136.2386,100 139,100 C141.7614,100 144,102.2386 144,105 Z" />
            <Label className="chartLabel" position="absolute" left="149px" top="100px" width="14.125px" textAlign="left" fontSize="10px">G</Label>
            <Path className="chartFill55" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M144,118 C144,120.7614 141.7614,123 139,123 C136.2386,123 134,120.7614 134,118 C134,115.2386 136.2386,113 139,113 C141.7614,113 144,115.2386 144,118 Z" />
            <Label className="chartLabel" position="absolute" left="149px" top="113px" width="14.125px" textAlign="left" fontSize="10px">H</Label>
            <Path className="chartFill56" position="absolute" left="0px" top="0px" width="163.125px" height="141px" viewBox="0 0 163.125 141" stroke="none" d="M144,131 C144,133.7614 141.7614,136 139,136 C136.2386,136 134,133.7614 134,131 C134,128.2386 136.2386,126 139,126 C141.7614,126 144,128.2386 144,131 Z" />
            <Label className="chartLabel" position="absolute" left="149px" top="126px" width="14.125px" textAlign="left" fontSize="10px">I</Label>
            <Label className="chartTitle" position="absolute" left="133px" top="5px" width="13.15px" textAlign="left" fontSize="11px" fontWeight="bold">a</Label>
          </View>
        </View>
          <Label className="caption">Donitsi · 52 komentoa</Label>
        </View>
      </View>
      <View className="row chartRow">
        <View className="chartCell">
        <View className="chartBox">
          <View className="chart" position="relative" width="276.006px" height="146px">
            <Path className="chartFrame" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" fill="none" strokeWidth="1" opacity="0.4" d="M78.3813,10.5 L228.3813,10.5 L228.3813,88.5 L78.3813,88.5 Z" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" fill="none" strokeWidth="1" opacity="0.25" d="M78.3813,88.5 L228.3813,88.5 M78.3813,49.5 L228.3813,49.5 M78.3813,10.5 L228.3813,10.5" />
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" fill="none" strokeWidth="1" d="M115.3813,88.5 L115.3813,93.5 M190.3813,88.5 L190.3813,93.5" />
            <Label className="chartLabel" position="absolute" left="109.131px" top="89.5px" width="12.5px" textAlign="center" fontSize="10px" rotate="270">x</Label>
            <Label className="chartLabel" position="absolute" left="184.131px" top="89.5px" width="12.5px" textAlign="center" fontSize="10px" rotate="270">y</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" fill="none" strokeWidth="1" d="M78.3813,88.5 L228.3813,88.5" />
            <Label className="chartTitle" position="absolute" left="146.806px" top="107.5px" width="13.15px" textAlign="center" fontSize="11px" fontWeight="bold">g</Label>
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" fill="none" strokeWidth="1" d="M78.3813,88.5 L73.3813,88.5 M78.3813,49.5 L73.3813,49.5 M78.3813,10.5 L73.3813,10.5" />
            <Label className="chartLabel" position="absolute" left="55.006px" top="83.5px" width="16.375px" textAlign="right" fontSize="10px">0%</Label>
            <Label className="chartLabel" position="absolute" left="48.381px" top="44.5px" width="23px" textAlign="right" fontSize="10px">50%</Label>
            <Label className="chartLabel" position="absolute" left="41.756px" top="5.5px" width="29.625px" textAlign="right" fontSize="10px">100%</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" fill="none" strokeWidth="1" d="M78.3813,88.5 L78.3813,10.5" />
            <Label className="chartTitle" position="absolute" left="-0px" top="42.9px" width="57.563px" textAlign="center" fontSize="11px" fontWeight="bold" rotate="-90">Sum of b</Label>
            <Path className="chartFill47" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M81.6313,10 L149.1313,10 L149.1313,19.7937 L81.6313,19.7937 Z" />
            <Path className="chartFill49" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M156.6313,10 L224.1313,10 L224.1313,25 L156.6313,25 Z" />
            <Path className="chartFill50" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M81.6313,19.7937 L149.1313,19.7937 L149.1313,34.8341 L81.6313,34.8341 Z" />
            <Path className="chartFill51" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M156.6313,25 L224.1313,25 L224.1313,49.8182 L156.6313,49.8182 Z" />
            <Path className="chartFill52" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M81.6313,34.8341 L149.1313,34.8341 L149.1313,63.1659 L81.6313,63.1659 Z" />
            <Path className="chartFill53" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M156.6313,49.8182 L224.1313,49.8182 L224.1313,64.2727 L156.6313,64.2727 Z" />
            <Path className="chartFill54" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M81.6313,63.1659 L149.1313,63.1659 L149.1313,69.8117 L81.6313,69.8117 Z" />
            <Path className="chartFill55" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M156.6313,64.2727 L224.1313,64.2727 L224.1313,88 L156.6313,88 Z" />
            <Path className="chartFill56" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M81.6313,69.8117 L149.1313,69.8117 L149.1313,88 L81.6313,88 Z" />
            <Path className="chartFill47" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M246.8813,27 L256.8813,27 L256.8813,37 L246.8813,37 Z" />
            <Label className="chartLabel" position="absolute" left="261.881px" top="27px" width="14.125px" textAlign="left" fontSize="10px">A</Label>
            <Path className="chartFill49" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M246.8813,40 L256.8813,40 L256.8813,50 L246.8813,50 Z" />
            <Label className="chartLabel" position="absolute" left="261.881px" top="40px" width="14.125px" textAlign="left" fontSize="10px">B</Label>
            <Path className="chartFill50" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M246.8813,53 L256.8813,53 L256.8813,63 L246.8813,63 Z" />
            <Label className="chartLabel" position="absolute" left="261.881px" top="53px" width="14.125px" textAlign="left" fontSize="10px">C</Label>
            <Path className="chartFill51" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M246.8813,66 L256.8813,66 L256.8813,76 L246.8813,76 Z" />
            <Label className="chartLabel" position="absolute" left="261.881px" top="66px" width="14.125px" textAlign="left" fontSize="10px">D</Label>
            <Path className="chartFill52" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M246.8813,79 L256.8813,79 L256.8813,89 L246.8813,89 Z" />
            <Label className="chartLabel" position="absolute" left="261.881px" top="79px" width="14.125px" textAlign="left" fontSize="10px">E</Label>
            <Path className="chartFill53" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M246.8813,92 L256.8813,92 L256.8813,102 L246.8813,102 Z" />
            <Label className="chartLabel" position="absolute" left="261.881px" top="92px" width="14.125px" textAlign="left" fontSize="10px">F</Label>
            <Path className="chartFill54" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M246.8813,105 L256.8813,105 L256.8813,115 L246.8813,115 Z" />
            <Label className="chartLabel" position="absolute" left="261.881px" top="105px" width="14.125px" textAlign="left" fontSize="10px">G</Label>
            <Path className="chartFill55" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M246.8813,118 L256.8813,118 L256.8813,128 L246.8813,128 Z" />
            <Label className="chartLabel" position="absolute" left="261.881px" top="118px" width="14.125px" textAlign="left" fontSize="10px">H</Label>
            <Path className="chartFill56" position="absolute" left="0px" top="0px" width="276.006px" height="146px" viewBox="0 0 276.006 146" stroke="none" d="M246.8813,131 L256.8813,131 L256.8813,141 L246.8813,141 Z" />
            <Label className="chartLabel" position="absolute" left="261.881px" top="131px" width="14.125px" textAlign="left" fontSize="10px">I</Label>
            <Label className="chartTitle" position="absolute" left="245.881px" top="10px" width="13.15px" textAlign="left" fontSize="11px" fontWeight="bold">a</Label>
          </View>
        </View>
          <Label className="caption">Normalisoitu pino · 76 komentoa</Label>
        </View>
        <View className="chartCell">
        <View className="chartBox">
          <View className="chart" position="relative" width="207px" height="123px">
            <Path className="chartFrame" position="absolute" left="0px" top="0px" width="207px" height="123px" viewBox="0 0 207 123" fill="none" strokeWidth="1" opacity="0.4" d="M51.5,10.5 L201.5,10.5 L201.5,88.5 L51.5,88.5 Z" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="207px" height="123px" viewBox="0 0 207 123" fill="none" strokeWidth="1" opacity="0.25" d="M51.5,88.5 L201.5,88.5 M51.5,49.5 L201.5,49.5 M51.5,10.5 L201.5,10.5" />
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="207px" height="123px" viewBox="0 0 207 123" fill="none" strokeWidth="1" d="M59.5,88.5 L59.5,93.5 M75.5,88.5 L75.5,93.5 M92.5,88.5 L92.5,93.5 M109.5,88.5 L109.5,93.5 M126.5,88.5 L126.5,93.5 M142.5,88.5 L142.5,93.5 M159.5,88.5 L159.5,93.5 M176.5,88.5 L176.5,93.5 M192.5,88.5 L192.5,93.5" />
            <Label className="chartLabel" position="absolute" left="52.271px" top="89.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">A</Label>
            <Label className="chartLabel" position="absolute" left="68.938px" top="89.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">B</Label>
            <Label className="chartLabel" position="absolute" left="85.604px" top="89.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">C</Label>
            <Label className="chartLabel" position="absolute" left="102.271px" top="89.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">D</Label>
            <Label className="chartLabel" position="absolute" left="118.938px" top="89.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">E</Label>
            <Label className="chartLabel" position="absolute" left="135.604px" top="89.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">F</Label>
            <Label className="chartLabel" position="absolute" left="152.271px" top="89.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">G</Label>
            <Label className="chartLabel" position="absolute" left="168.938px" top="89.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">H</Label>
            <Label className="chartLabel" position="absolute" left="185.604px" top="89.5px" width="14.125px" textAlign="center" fontSize="10px" rotate="270">I</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="207px" height="123px" viewBox="0 0 207 123" fill="none" strokeWidth="1" d="M51.5,88.5 L201.5,88.5" />
            <Label className="chartTitle" position="absolute" left="119.925px" top="107.5px" width="13.15px" textAlign="center" fontSize="11px" fontWeight="bold">a</Label>
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="207px" height="123px" viewBox="0 0 207 123" fill="none" strokeWidth="1" d="M51.5,88.5 L46.5,88.5 M51.5,49.5 L46.5,49.5 M51.5,10.5 L46.5,10.5" />
            <Label className="chartLabel" position="absolute" left="31.875px" top="83.5px" width="12.625px" textAlign="right" fontSize="10px">0</Label>
            <Label className="chartLabel" position="absolute" left="25.25px" top="44.5px" width="19.25px" textAlign="right" fontSize="10px">50</Label>
            <Label className="chartLabel" position="absolute" left="18.625px" top="5.5px" width="25.875px" textAlign="right" fontSize="10px">100</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="207px" height="123px" viewBox="0 0 207 123" fill="none" strokeWidth="1" d="M51.5,88.5 L51.5,10.5" />
            <Label className="chartTitle" position="absolute" left="3.325px" top="42.9px" width="13.15px" textAlign="center" fontSize="11px" fontWeight="bold" rotate="-90">b</Label>
            <Path className="chartFill47" position="absolute" left="0px" top="0px" width="207px" height="123px" viewBox="0 0 207 123" stroke="none" d="M51.8333,66.16 L66.8333,66.16 L66.8333,88 L51.8333,88 Z M68.5,45.1 L83.5,45.1 L83.5,88 L68.5,88 Z M85.1667,54.46 L100.1667,54.46 L100.1667,88 L85.1667,88 Z M101.8333,17.02 L116.8333,17.02 L116.8333,88 L101.8333,88 Z M118.5,24.82 L133.5,24.82 L133.5,88 L118.5,88 Z M135.1667,46.66 L150.1667,46.66 L150.1667,88 L135.1667,88 Z M151.8333,73.18 L166.8333,73.18 L166.8333,88 L151.8333,88 Z M168.5,20.14 L183.5,20.14 L183.5,88 L168.5,88 Z M185.1667,47.44 L200.1667,47.44 L200.1667,88 L185.1667,88 Z" />
            <Label className="chartText57" position="absolute" left="49.046px" top="60.66px" width="20.575px" textAlign="center" fontSize="11px">28</Label>
            <Label className="chartText57" position="absolute" left="65.713px" top="39.6px" width="20.575px" textAlign="center" fontSize="11px">55</Label>
            <Label className="chartText57" position="absolute" left="82.379px" top="48.96px" width="20.575px" textAlign="center" fontSize="11px">43</Label>
            <Label className="chartText57" position="absolute" left="99.046px" top="11.52px" width="20.575px" textAlign="center" fontSize="11px">91</Label>
            <Label className="chartText57" position="absolute" left="115.713px" top="19.32px" width="20.575px" textAlign="center" fontSize="11px">81</Label>
            <Label className="chartText57" position="absolute" left="132.379px" top="41.16px" width="20.575px" textAlign="center" fontSize="11px">53</Label>
            <Label className="chartText57" position="absolute" left="149.046px" top="67.68px" width="20.575px" textAlign="center" fontSize="11px">19</Label>
            <Label className="chartText57" position="absolute" left="165.713px" top="14.64px" width="20.575px" textAlign="center" fontSize="11px">87</Label>
            <Label className="chartText57" position="absolute" left="182.379px" top="41.94px" width="20.575px" textAlign="center" fontSize="11px">52</Label>
          </View>
        </View>
          <Label className="caption">Arvot pylväiden päällä · 58 komentoa</Label>
        </View>
      </View>
    </View>
  );
}

export default render;
