// GENERATED by gallery/vela/tools/vela_evg.rgr — do not edit by hand.
//
// Each chart below is an unmodified Vega specification, compiled from a
// Vega-Lite example, run through the Vela runtime and drawn with the EVG
// vector layer: every gridline, bar, wedge and label is path data and text
// this repository computed, in all three targets.
//
// Regenerate with:  npm run vela:showcase

import { View, Label, Path } from "./evg_types";

function render() {
  return (
    <View className="page">
      <Label className="title">Piirto</Label>
      <View className="rule" />
      <View className="row chartRow">
        <View className="chartCell">
        <View className="chartBox">
          <View className="chart" position="relative" width="379.833px" height="163px">
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="379.833px" height="163px" viewBox="0 0 379.833 163" fill="none" strokeWidth="1" d="M45.5,75.5 L45.5,80.5 M74.5,75.5 L74.5,80.5 M102.5,75.5 L102.5,80.5 M130.5,75.5 L130.5,80.5 M159.5,75.5 L159.5,80.5 M187.5,75.5 L187.5,80.5 M215.5,75.5 L215.5,80.5 M244.5,75.5 L244.5,80.5 M272.5,75.5 L272.5,80.5 M300.5,75.5 L300.5,80.5 M329.5,75.5 L329.5,80.5 M357.5,75.5 L357.5,80.5" />
            <Label className="chartLabel" position="absolute" left="23.167px" top="76.5px" width="45px" textAlign="center" fontSize="10px" rotate="-40">circle</Label>
            <Label className="chartLabel" position="absolute" left="51.5px" top="76.5px" width="45px" textAlign="center" fontSize="10px" rotate="-40">square</Label>
            <Label className="chartLabel" position="absolute" left="83.083px" top="76.5px" width="38.5px" textAlign="center" fontSize="10px" rotate="-40">cross</Label>
            <Label className="chartLabel" position="absolute" left="104.917px" top="76.5px" width="51.5px" textAlign="center" fontSize="10px" rotate="-40">diamond</Label>
            <Label className="chartLabel" position="absolute" left="121.625px" top="76.5px" width="74.75px" textAlign="center" fontSize="10px" rotate="-40">triangle-up</Label>
            <Label className="chartLabel" position="absolute" left="143.458px" top="76.5px" width="87.75px" textAlign="center" fontSize="10px" rotate="-40">triangle-down</Label>
            <Label className="chartLabel" position="absolute" left="168.542px" top="76.5px" width="94.25px" textAlign="center" fontSize="10px" rotate="-40">triangle-right</Label>
            <Label className="chartLabel" position="absolute" left="200.125px" top="76.5px" width="87.75px" textAlign="center" fontSize="10px" rotate="-40">triangle-left</Label>
            <Label className="chartLabel" position="absolute" left="243.333px" top="76.5px" width="58px" textAlign="center" fontSize="10px" rotate="-40">triangle</Label>
            <Label className="chartLabel" position="absolute" left="281.417px" top="76.5px" width="38.5px" textAlign="center" fontSize="10px" rotate="-40">wedge</Label>
            <Label className="chartLabel" position="absolute" left="309.75px" top="76.5px" width="38.5px" textAlign="center" fontSize="10px" rotate="-40">arrow</Label>
            <Label className="chartLabel" position="absolute" left="334.833px" top="76.5px" width="45px" textAlign="center" fontSize="10px" rotate="-40">stroke</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="379.833px" height="163px" viewBox="0 0 379.833 163" fill="none" strokeWidth="1" d="M31.5,75.5 L371.5,75.5" />
            <Path className="chartFill0 chartStroke1" position="absolute" left="0px" top="0px" width="379.833px" height="163px" viewBox="0 0 379.833 163" stroke="none" opacity="0.55" d="M53.2289,40 C53.2289,44.4527 49.6193,48.0623 45.1667,48.0623 C40.714,48.0623 37.1044,44.4527 37.1044,40 C37.1044,35.5473 40.714,31.9377 45.1667,31.9377 C49.6193,31.9377 53.2289,35.5473 53.2289,40 Z M65.4377,31.9377 L81.5623,31.9377 L81.5623,48.0623 L65.4377,48.0623 Z M93.7711,36.7751 L93.7711,43.2249 L98.6084,43.2249 L98.6084,48.0623 L105.0582,48.0623 L105.0582,43.2249 L109.8956,43.2249 L109.8956,36.7751 L105.0582,36.7751 L105.0582,31.9377 L98.6084,31.9377 L98.6084,36.7751 Z M122.1044,40 L130.1667,31.9377 L138.2289,40 L130.1667,48.0623 Z M158.5,33.0179 L150.4377,46.9821 L166.5623,46.9821 Z M186.8333,46.9821 L178.7711,33.0179 L194.8956,33.0179 Z M222.1488,40 L208.1845,31.9377 L208.1845,48.0623 Z M236.5179,40 L250.4821,31.9377 L250.4821,48.0623 Z M271.8333,30.6905 L263.7711,44.6547 L279.8956,44.6547 Z M300.1667,30.6905 L298.1511,44.6547 L302.1822,44.6547 Z M327.3482,48.0623 L329.6518,48.0623 L329.6518,38.9922 L331.7249,38.9922 L328.5,31.9377 L325.2751,38.9922 L327.3482,38.9922 Z M348.7711,40 L364.8956,40" />
            <Path className="chartFill0 chartStroke1" position="absolute" left="0px" top="0px" width="379.833px" height="163px" viewBox="0 0 379.833 163" fill="none" strokeWidth="1.5" opacity="0.9" d="M53.2289,40 C53.2289,44.4527 49.6193,48.0623 45.1667,48.0623 C40.714,48.0623 37.1044,44.4527 37.1044,40 C37.1044,35.5473 40.714,31.9377 45.1667,31.9377 C49.6193,31.9377 53.2289,35.5473 53.2289,40 Z M65.4377,31.9377 L81.5623,31.9377 L81.5623,48.0623 L65.4377,48.0623 Z M93.7711,36.7751 L93.7711,43.2249 L98.6084,43.2249 L98.6084,48.0623 L105.0582,48.0623 L105.0582,43.2249 L109.8956,43.2249 L109.8956,36.7751 L105.0582,36.7751 L105.0582,31.9377 L98.6084,31.9377 L98.6084,36.7751 Z M122.1044,40 L130.1667,31.9377 L138.2289,40 L130.1667,48.0623 Z M158.5,33.0179 L150.4377,46.9821 L166.5623,46.9821 Z M186.8333,46.9821 L178.7711,33.0179 L194.8956,33.0179 Z M222.1488,40 L208.1845,31.9377 L208.1845,48.0623 Z M236.5179,40 L250.4821,31.9377 L250.4821,48.0623 Z M271.8333,30.6905 L263.7711,44.6547 L279.8956,44.6547 Z M300.1667,30.6905 L298.1511,44.6547 L302.1822,44.6547 Z M327.3482,48.0623 L329.6518,48.0623 L329.6518,38.9922 L331.7249,38.9922 L328.5,31.9377 L325.2751,38.9922 L327.3482,38.9922 Z M348.7711,40 L364.8956,40" />
          </View>
        </View>
          <Label className="caption">Kaikki merkkimuodot · 41 komentoa</Label>
        </View>
        <View className="chartCell">
        <View className="chartBox">
          <View className="chart" position="relative" width="426px" height="182px">
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1" d="M36.5,160.5 L36.5,165.5 M73.5,160.5 L73.5,165.5 M110.5,160.5 L110.5,165.5 M147.5,160.5 L147.5,165.5 M185.5,160.5 L185.5,165.5 M222.5,160.5 L222.5,165.5 M259.5,160.5 L259.5,165.5 M296.5,160.5 L296.5,165.5" />
            <Label className="chartLabel" position="absolute" left="30.188px" top="167.5px" width="12.625px" textAlign="center" fontSize="10px">0</Label>
            <Label className="chartLabel" position="absolute" left="67.33px" top="167.5px" width="12.625px" textAlign="center" fontSize="10px">1</Label>
            <Label className="chartLabel" position="absolute" left="104.473px" top="167.5px" width="12.625px" textAlign="center" fontSize="10px">2</Label>
            <Label className="chartLabel" position="absolute" left="141.616px" top="167.5px" width="12.625px" textAlign="center" fontSize="10px">3</Label>
            <Label className="chartLabel" position="absolute" left="178.759px" top="167.5px" width="12.625px" textAlign="center" fontSize="10px">4</Label>
            <Label className="chartLabel" position="absolute" left="215.902px" top="167.5px" width="12.625px" textAlign="center" fontSize="10px">5</Label>
            <Label className="chartLabel" position="absolute" left="253.045px" top="167.5px" width="12.625px" textAlign="center" fontSize="10px">6</Label>
            <Label className="chartLabel" position="absolute" left="290.188px" top="167.5px" width="12.625px" textAlign="center" fontSize="10px">7</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1" d="M36.5,160.5 L296.5,160.5" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1" d="M36.5,160.5 L296.5,160.5 M36.5,145.5 L296.5,145.5 M36.5,130.5 L296.5,130.5 M36.5,115.5 L296.5,115.5 M36.5,100.5 L296.5,100.5 M36.5,85.5 L296.5,85.5 M36.5,70.5 L296.5,70.5 M36.5,55.5 L296.5,55.5 M36.5,40.5 L296.5,40.5 M36.5,25.5 L296.5,25.5 M36.5,10.5 L296.5,10.5" />
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1" d="M36.5,160.5 L31.5,160.5 M36.5,145.5 L31.5,145.5 M36.5,130.5 L31.5,130.5 M36.5,115.5 L31.5,115.5 M36.5,100.5 L31.5,100.5 M36.5,85.5 L31.5,85.5 M36.5,70.5 L31.5,70.5 M36.5,55.5 L31.5,55.5 M36.5,40.5 L31.5,40.5 M36.5,25.5 L31.5,25.5 M36.5,10.5 L31.5,10.5" />
            <Label className="chartLabel" position="absolute" left="16.875px" top="155.5px" width="12.625px" textAlign="right" fontSize="10px">0</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="140.5px" width="19.25px" textAlign="right" fontSize="10px">10</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="125.5px" width="19.25px" textAlign="right" fontSize="10px">20</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="110.5px" width="19.25px" textAlign="right" fontSize="10px">30</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="95.5px" width="19.25px" textAlign="right" fontSize="10px">40</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="80.5px" width="19.25px" textAlign="right" fontSize="10px">50</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="65.5px" width="19.25px" textAlign="right" fontSize="10px">60</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="50.5px" width="19.25px" textAlign="right" fontSize="10px">70</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="35.5px" width="19.25px" textAlign="right" fontSize="10px">80</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="20.5px" width="19.25px" textAlign="right" fontSize="10px">90</Label>
            <Label className="chartLabel" position="absolute" left="3.625px" top="5.5px" width="25.875px" textAlign="right" fontSize="10px">100</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1" d="M36.5,160.5 L36.5,10.5" />
            <Path className="chartStroke0" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" opacity="0.85" d="M36,118 L73.1429,77.5 L110.2857,95.5 L147.4286,23.5 L184.5714,38.5 L221.7143,80.5 L258.8571,131.5 L296,29.5" />
            <Path className="chartStroke2" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" opacity="0.85" d="M36,118 L42.1905,111.25 C48.381,104.5 60.7619,91 73.1429,87.25 C85.5238,83.5 97.9048,89.5 110.2857,80.5 C122.6667,71.5 135.0476,47.5 147.4286,38 C159.8095,28.5 172.1905,33.5 184.5714,43 C196.9524,52.5 209.3333,66.5 221.7143,82 C234.0952,97.5 246.4762,114.5 258.8571,106 C271.2381,97.5 283.619,63.5 289.8095,46.5 L296,29.5" />
            <Path className="chartStroke3" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" opacity="0.85" d="M36,118 C36,118 60.7619,81.25 73.1429,77.5 C85.5238,73.75 97.9048,104.5 110.2857,95.5 C122.6667,86.5 135.0476,33 147.4286,23.5 C159.8095,14 172.1905,29 184.5714,38.5 C196.9524,48 209.3333,65 221.7143,80.5 C234.0952,96 246.4762,140 258.8571,131.5 C271.2381,123 296,29.5 296,29.5" />
            <Path className="chartStroke4" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" opacity="0.85" d="M36,118 C36,118 59.7414,80.0589 73.1429,77.5 C84.7573,75.2823 99.3807,99.1336 110.2857,95.5 C125.5638,90.4093 131.9789,29.2336 147.4286,23.5 C158.2922,19.4684 173.0681,30.3698 184.5714,38.5 C198.1808,48.1187 209.6776,65.517 221.7143,80.5 C234.4827,96.3939 247.7489,133.0668 258.8571,131.5 C273.4278,129.4449 296,29.5 296,29.5" />
            <Path className="chartStroke5" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" opacity="0.85" d="M36,118 C48.381,97.75 60.7619,77.5 73.1429,77.5 C85.5238,77.5 97.9048,95.5 110.2857,95.5 C122.6667,95.5 135.0476,23.5 147.4286,23.5 C159.8095,23.5 172.1905,29 184.5714,38.5 C196.9524,48 209.3333,65 221.7143,80.5 C234.0952,96 246.4762,131.5 258.8571,131.5 C271.2381,131.5 283.619,80.5 296,29.5" />
            <Path className="chartStroke6" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" opacity="0.85" d="M36,118 C48.381,96.5879 60.7619,75.1759 73.1429,77.5 C85.5238,79.8241 97.9048,105.8844 110.2857,95.5 C122.6667,85.1156 135.0476,38.2865 147.4286,23.5 C159.8095,8.7135 172.1905,25.9696 184.5714,38.5 C196.9524,51.0304 209.3333,58.8351 221.7143,80.5 C234.0952,102.1649 246.4762,137.69 258.8571,131.5 C271.2381,125.31 283.619,77.405 296,29.5" />
            <Path className="chartStroke7" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" opacity="0.85" d="M36,118 L54.5714,118 L54.5714,77.5 L73.1429,77.5 L91.7143,77.5 L91.7143,95.5 L110.2857,95.5 L128.8571,95.5 L128.8571,23.5 L147.4286,23.5 L166,23.5 L166,38.5 L184.5714,38.5 L203.1429,38.5 L203.1429,80.5 L221.7143,80.5 L240.2857,80.5 L240.2857,131.5 L258.8571,131.5 L277.4286,131.5 L277.4286,29.5 L296,29.5" />
            <Path className="chartStroke8" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" opacity="0.85" d="M36,118 L36,77.5 L73.1429,77.5 L73.1429,95.5 L110.2857,95.5 L110.2857,23.5 L147.4286,23.5 L147.4286,38.5 L184.5714,38.5 L184.5714,80.5 L221.7143,80.5 L221.7143,131.5 L258.8571,131.5 L258.8571,29.5 L296,29.5" />
            <Path className="chartStroke9" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" opacity="0.85" d="M36,118 L73.1429,118 L73.1429,77.5 L110.2857,77.5 L110.2857,95.5 L147.4286,95.5 L147.4286,23.5 L184.5714,23.5 L184.5714,38.5 L221.7143,38.5 L221.7143,80.5 L258.8571,80.5 L258.8571,131.5 L296,131.5 L296,29.5" />
            <Path className="chartStroke0" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" d="M318,32 L328,32" />
            <Label className="chartLabel" position="absolute" left="333px" top="27px" width="45px" textAlign="left" fontSize="10px">linear</Label>
            <Path className="chartStroke2" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" d="M318,45 L328,45" />
            <Label className="chartLabel" position="absolute" left="333px" top="40px" width="38.5px" textAlign="left" fontSize="10px">basis</Label>
            <Path className="chartStroke3" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" d="M318,58 L328,58" />
            <Label className="chartLabel" position="absolute" left="333px" top="53px" width="58px" textAlign="left" fontSize="10px">cardinal</Label>
            <Path className="chartStroke4" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" d="M318,71 L328,71" />
            <Label className="chartLabel" position="absolute" left="333px" top="66px" width="74.75px" textAlign="left" fontSize="10px">catmull-rom</Label>
            <Path className="chartStroke5" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" d="M318,84 L328,84" />
            <Label className="chartLabel" position="absolute" left="333px" top="79px" width="58px" textAlign="left" fontSize="10px">monotone</Label>
            <Path className="chartStroke6" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" d="M318,97 L328,97" />
            <Label className="chartLabel" position="absolute" left="333px" top="92px" width="51.5px" textAlign="left" fontSize="10px">natural</Label>
            <Path className="chartStroke7" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" d="M318,110 L328,110" />
            <Label className="chartLabel" position="absolute" left="333px" top="105px" width="32px" textAlign="left" fontSize="10px">step</Label>
            <Path className="chartStroke8" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" d="M318,123 L328,123" />
            <Label className="chartLabel" position="absolute" left="333px" top="118px" width="74.75px" textAlign="left" fontSize="10px">step-before</Label>
            <Path className="chartStroke9" position="absolute" left="0px" top="0px" width="426px" height="182px" viewBox="0 0 426 182" fill="none" strokeWidth="1.5" d="M318,136 L328,136" />
            <Label className="chartLabel" position="absolute" left="333px" top="131px" width="68.25px" textAlign="left" fontSize="10px">step-after</Label>
            <Label className="chartTitle" position="absolute" left="317px" top="10px" width="84.65px" textAlign="left" fontSize="11px" fontWeight="bold">interpolate</Label>
          </View>
        </View>
          <Label className="caption">Interpolaatiot · 125 komentoa</Label>
        </View>
      </View>
      <View className="row chartRow">
        <View className="chartCell">
        <View className="chartBox">
          <View className="chart" position="relative" width="301px" height="172px">
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="301px" height="172px" viewBox="0 0 301 172" fill="none" strokeWidth="1" d="M73.5,150.5 L73.5,155.5 M135.5,150.5 L135.5,155.5 M196.5,150.5 L196.5,155.5 M258.5,150.5 L258.5,155.5" />
            <Label className="chartLabel" position="absolute" left="66.08px" top="157.5px" width="14.125px" textAlign="center" fontSize="10px">A</Label>
            <Label className="chartLabel" position="absolute" left="127.985px" top="157.5px" width="14.125px" textAlign="center" fontSize="10px">B</Label>
            <Label className="chartLabel" position="absolute" left="189.89px" top="157.5px" width="14.125px" textAlign="center" fontSize="10px">C</Label>
            <Label className="chartLabel" position="absolute" left="251.795px" top="157.5px" width="14.125px" textAlign="center" fontSize="10px">D</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="301px" height="172px" viewBox="0 0 301 172" fill="none" strokeWidth="1" d="M36.5,150.5 L296.5,150.5" />
            <Path className="chartGrid" position="absolute" left="0px" top="0px" width="301px" height="172px" viewBox="0 0 301 172" fill="none" strokeWidth="1" strokeDasharray="4,3" d="M36.5,150.5 L296.5,150.5 M36.5,136.5 L296.5,136.5 M36.5,122.5 L296.5,122.5 M36.5,108.5 L296.5,108.5 M36.5,94.5 L296.5,94.5 M36.5,80.5 L296.5,80.5 M36.5,66.5 L296.5,66.5 M36.5,52.5 L296.5,52.5 M36.5,38.5 L296.5,38.5 M36.5,24.5 L296.5,24.5 M36.5,10.5 L296.5,10.5" />
            <Path className="chartTick" position="absolute" left="0px" top="0px" width="301px" height="172px" viewBox="0 0 301 172" fill="none" strokeWidth="1" d="M36.5,150.5 L31.5,150.5 M36.5,136.5 L31.5,136.5 M36.5,122.5 L31.5,122.5 M36.5,108.5 L31.5,108.5 M36.5,94.5 L31.5,94.5 M36.5,80.5 L31.5,80.5 M36.5,66.5 L31.5,66.5 M36.5,52.5 L31.5,52.5 M36.5,38.5 L31.5,38.5 M36.5,24.5 L31.5,24.5 M36.5,10.5 L31.5,10.5" />
            <Label className="chartLabel" position="absolute" left="16.875px" top="145.5px" width="12.625px" textAlign="right" fontSize="10px">0</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="131.5px" width="19.25px" textAlign="right" fontSize="10px">10</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="117.5px" width="19.25px" textAlign="right" fontSize="10px">20</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="103.5px" width="19.25px" textAlign="right" fontSize="10px">30</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="89.5px" width="19.25px" textAlign="right" fontSize="10px">40</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="75.5px" width="19.25px" textAlign="right" fontSize="10px">50</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="61.5px" width="19.25px" textAlign="right" fontSize="10px">60</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="47.5px" width="19.25px" textAlign="right" fontSize="10px">70</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="33.5px" width="19.25px" textAlign="right" fontSize="10px">80</Label>
            <Label className="chartLabel" position="absolute" left="10.25px" top="19.5px" width="19.25px" textAlign="right" fontSize="10px">90</Label>
            <Label className="chartLabel" position="absolute" left="3.625px" top="5.5px" width="25.875px" textAlign="right" fontSize="10px">100</Label>
            <Path className="chartDomain" position="absolute" left="0px" top="0px" width="301px" height="172px" viewBox="0 0 301 172" fill="none" strokeWidth="1" d="M36.5,150.5 L36.5,10.5" />
            <Path className="chartFill5 chartStroke10" position="absolute" left="0px" top="0px" width="301px" height="172px" viewBox="0 0 301 172" stroke="none" opacity="0.45" d="M48.381,63.2 L97.9048,63.2 L97.9048,150 L48.381,150 Z" />
            <Path className="chartFill5 chartStroke10" position="absolute" left="0px" top="0px" width="301px" height="172px" viewBox="0 0 301 172" fill="none" strokeWidth="2" opacity="0.9" d="M48.381,63.2 L97.9048,63.2 L97.9048,150 L48.381,150 Z" />
            <Path className="chartFill5 chartStroke10" position="absolute" left="0px" top="0px" width="301px" height="172px" viewBox="0 0 301 172" stroke="none" opacity="0.45" d="M114.2857,26.8 L155.8095,26.8 C158.0172,26.8 159.8095,28.5923 159.8095,30.8 L159.8095,146 C159.8095,148.2077 158.0172,150 155.8095,150 L114.2857,150 C112.0781,150 110.2857,148.2077 110.2857,146 L110.2857,30.8 C110.2857,28.5923 112.0781,26.8 114.2857,26.8 Z" />
            <Path className="chartFill5 chartStroke10" position="absolute" left="0px" top="0px" width="301px" height="172px" viewBox="0 0 301 172" fill="none" strokeWidth="2" opacity="0.9" d="M114.2857,26.8 L155.8095,26.8 C158.0172,26.8 159.8095,28.5923 159.8095,30.8 L159.8095,146 C159.8095,148.2077 158.0172,150 155.8095,150 L114.2857,150 C112.0781,150 110.2857,148.2077 110.2857,146 L110.2857,30.8 C110.2857,28.5923 112.0781,26.8 114.2857,26.8 Z" />
            <Path className="chartFill5 chartStroke10" position="absolute" left="0px" top="0px" width="301px" height="172px" viewBox="0 0 301 172" stroke="none" opacity="0.45" d="M180.1905,92.6 L213.7143,92.6 C218.1296,92.6 221.7143,96.1847 221.7143,100.6 L221.7143,142 C221.7143,146.4153 218.1296,150 213.7143,150 L180.1905,150 C175.7752,150 172.1905,146.4153 172.1905,142 L172.1905,100.6 C172.1905,96.1847 175.7752,92.6 180.1905,92.6 Z" />
            <Path className="chartFill5 chartStroke10" position="absolute" left="0px" top="0px" width="301px" height="172px" viewBox="0 0 301 172" fill="none" strokeWidth="2" opacity="0.9" d="M180.1905,92.6 L213.7143,92.6 C218.1296,92.6 221.7143,96.1847 221.7143,100.6 L221.7143,142 C221.7143,146.4153 218.1296,150 213.7143,150 L180.1905,150 C175.7752,150 172.1905,146.4153 172.1905,142 L172.1905,100.6 C172.1905,96.1847 175.7752,92.6 180.1905,92.6 Z" />
            <Path className="chartFill5 chartStroke10" position="absolute" left="0px" top="0px" width="301px" height="172px" viewBox="0 0 301 172" stroke="none" opacity="0.45" d="M246.0952,46.4 L271.619,46.4 C278.242,46.4 283.619,51.777 283.619,58.4 L283.619,138 C283.619,144.623 278.242,150 271.619,150 L246.0952,150 C239.4723,150 234.0952,144.623 234.0952,138 L234.0952,58.4 C234.0952,51.777 239.4723,46.4 246.0952,46.4 Z" />
            <Path className="chartFill5 chartStroke10" position="absolute" left="0px" top="0px" width="301px" height="172px" viewBox="0 0 301 172" fill="none" strokeWidth="2" opacity="0.9" d="M246.0952,46.4 L271.619,46.4 C278.242,46.4 283.619,51.777 283.619,58.4 L283.619,138 C283.619,144.623 278.242,150 271.619,150 L246.0952,150 C239.4723,150 234.0952,144.623 234.0952,138 L234.0952,58.4 C234.0952,51.777 239.4723,46.4 246.0952,46.4 Z" />
            <Path className="chartStroke11" position="absolute" left="0px" top="0px" width="301px" height="172px" viewBox="0 0 301 172" fill="none" strokeWidth="3" strokeDasharray="6,4" d="M55.8095,63.2 L90.4762,63.2 M117.7143,26.8 L152.381,26.8 M179.619,92.6 L214.2857,92.6 M241.5238,46.4 L276.1905,46.4" />
          </View>
        </View>
          <Label className="caption">Katkoviiva, pyöristys, läpinäkyvyys · 57 komentoa</Label>
        </View>
        <View className="chartCell">
        <View className="chartBox">
          <View className="chart" position="relative" width="294.7px" height="206px">
            <Path className="chartFill11" position="absolute" left="0px" top="0px" width="294.7px" height="206px" viewBox="0 0 294.7 206" stroke="none" d="M18.225,25 C18.225,26.1046 17.3296,27 16.225,27 C15.1204,27 14.225,26.1046 14.225,25 C14.225,23.8954 15.1204,23 16.225,23 C17.3296,23 18.225,23.8954 18.225,25 Z M138.225,25 C138.225,26.1046 137.3296,27 136.225,27 C135.1204,27 134.225,26.1046 134.225,25 C134.225,23.8954 135.1204,23 136.225,23 C137.3296,23 138.225,23.8954 138.225,25 Z M258.225,25 C258.225,26.1046 257.3296,27 256.225,27 C255.1204,27 254.225,26.1046 254.225,25 C254.225,23.8954 255.1204,23 256.225,23 C257.3296,23 258.225,23.8954 258.225,25 Z M18.225,65 C18.225,66.1046 17.3296,67 16.225,67 C15.1204,67 14.225,66.1046 14.225,65 C14.225,63.8954 15.1204,63 16.225,63 C17.3296,63 18.225,63.8954 18.225,65 Z M138.225,65 C138.225,66.1046 137.3296,67 136.225,67 C135.1204,67 134.225,66.1046 134.225,65 C134.225,63.8954 135.1204,63 136.225,63 C137.3296,63 138.225,63.8954 138.225,65 Z M258.225,65 C258.225,66.1046 257.3296,67 256.225,67 C255.1204,67 254.225,66.1046 254.225,65 C254.225,63.8954 255.1204,63 256.225,63 C257.3296,63 258.225,63.8954 258.225,65 Z M38.225,125 C38.225,126.1046 37.3296,127 36.225,127 C35.1204,127 34.225,126.1046 34.225,125 C34.225,123.8954 35.1204,123 36.225,123 C37.3296,123 38.225,123.8954 38.225,125 Z M138.225,125 C138.225,126.1046 137.3296,127 136.225,127 C135.1204,127 134.225,126.1046 134.225,125 C134.225,123.8954 135.1204,123 136.225,123 C137.3296,123 138.225,123.8954 138.225,125 Z M248.225,125 C248.225,126.1046 247.3296,127 246.225,127 C245.1204,127 244.225,126.1046 244.225,125 C244.225,123.8954 245.1204,123 246.225,123 C247.3296,123 248.225,123.8954 248.225,125 Z" />
            <Label className="chartText1" position="absolute" left="16.225px" top="15.4px" width="84px" textAlign="left" fontSize="12px">alphabetic</Label>
            <Label className="chartText1" position="absolute" left="121.525px" top="25px" width="29.4px" textAlign="center" fontSize="12px">top</Label>
            <Label className="chartText1" position="absolute" left="203.425px" top="19px" width="52.8px" textAlign="right" fontSize="12px">middle</Label>
            <Label className="chartText1" position="absolute" left="16.225px" top="53px" width="52.8px" textAlign="left" fontSize="12px">bottom</Label>
            <Label className="chartText1" position="absolute" left="109.825px" top="59px" width="52.8px" textAlign="center" fontSize="12px">nudged</Label>
            <Label className="chartText1" position="absolute" left="217.75px" top="57.8px" width="76.95px" textAlign="center" fontSize="12px" rotate="-90">turned -90</Label>
            <Label className="chartText1" position="absolute" left="0px" top="117.8px" width="72.45px" textAlign="center" fontSize="12px" rotate="90">turned 90</Label>
            <Label className="chartText1" position="absolute" left="104.95px" top="117.8px" width="76.95px" textAlign="center" fontSize="12px" rotate="-45">turned -45</Label>
            <Label className="chartText1" position="absolute" left="198.825px" top="117.8px" width="80.4px" textAlign="center" fontSize="12px" rotate="270">turned 270</Label>
          </View>
        </View>
          <Label className="caption">Tekstin ankkurointi · 20 komentoa</Label>
        </View>
      </View>
    </View>
  );
}

export default render;
