/**
 * main.js — what the front page does once it is on screen.
 *
 * Four things, and they are all optional: the page reads and works with none
 * of them having run. The backdrop is in assets/hero/hero.js, because it is
 * the one part that is a program rather than a decoration.
 */
import { startHero } from "./assets/hero/hero.js";

/* --------------------------------------------------------- inline SVG --- */
/* Anything with data-inline-svg gets the file's markup put in it, so the path
   can take currentColor and be animated. A failed fetch leaves an empty span,
   which is what the decoration was worth anyway. */
for (const host of document.querySelectorAll("[data-inline-svg]")) {
  fetch(host.dataset.inlineSvg)
    .then((r) => (r.ok ? r.text() : Promise.reject(new Error(String(r.status)))))
    .then((svg) => { host.innerHTML = svg; })
    .catch(() => { /* the page is fine without it */ });
}

/* ----------------------------------------------------------- the nav ---- */
const nav = document.getElementById("nav");
if (nav) {
  const onScroll = () => nav.classList.toggle("is-stuck", window.scrollY > 8);
  addEventListener("scroll", onScroll, { passive: true });
  onScroll();
}

/* ------------------------------------------------------------ reveal ---- */
const reduced = matchMedia("(prefers-reduced-motion: reduce)").matches;
const targets = document.querySelectorAll(".reveal");
if (reduced || !("IntersectionObserver" in window)) {
  for (const el of targets) el.classList.add("is-in");
} else {
  const io = new IntersectionObserver((entries, obs) => {
    for (const e of entries) {
      if (!e.isIntersecting) continue;
      e.target.classList.add("is-in");
      obs.unobserve(e.target);
    }
  }, { rootMargin: "0px 0px -8% 0px", threshold: 0.05 });
  for (const el of targets) io.observe(el);
}

/* ------------------------------------------------------- the code tabs -- */
/*
 * assets/targets.js is generated by landing/tools/examples.mjs: it holds the
 * Ranger source and, for each target, exactly what the compiler wrote for it.
 * Nothing here interprets the code — the highlighter below is a few regular
 * expressions over already-escaped text, deliberately shallow, because a
 * wrong colour on a keyword is cheaper than a parser on the front page.
 */
const DATA = window.RANGER_TARGETS;

const esc = (s) => s.replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]));

const KEYWORDS = {
  ranger: /\b(class|extension|fn|sfn|def|return|if|while|for|push|new|this|true|false|null|break|continue|switch|case|Constructor|Extends|idiv|unwrap|wrap)\b/g,
  swift: /\b(func|class|final|var|let|return|if|else|for|in|while|import|struct|enum|public|private|override|self|true|false|nil|inout|Void)\b/g,
  kotlin: /\b(fun|class|val|var|return|if|else|for|in|while|import|object|override|this|true|false|null|Unit|open)\b/g,
  js: /\b(function|class|const|let|var|return|if|else|for|of|in|while|new|this|true|false|null|undefined|export|import|extends|typeof)\b/g,
  ts: /\b(function|class|const|let|var|return|if|else|for|of|in|while|new|this|true|false|null|undefined|export|import|extends|typeof|public|private|readonly|interface|number|string|boolean|void|any)\b/g,
  csharp: /\b(using|namespace|public|private|class|void|return|if|else|for|foreach|in|while|new|this|true|false|null|static|override|int|string|bool|double|var)\b/g,
  cpp: /\b(class|public|private|struct|return|if|else|for|while|new|this|true|false|nullptr|const|auto|void|int|double|bool|template|typename|static|std|include)\b/g,
  php: /\b(class|function|public|private|return|if|else|for|foreach|as|while|new|this|true|false|null|static|echo|array)\b/g,
  rust: /\b(fn|pub|struct|impl|let|mut|return|if|else|for|in|while|match|self|true|false|None|Some|use|crate|i64|f64|bool|String|Vec|Rc|RefCell)\b/g,
};

function highlight(code, lang) {
  let out = esc(code);
  // Comments and strings first, then wrap them so a later pass cannot reach
  // inside: a keyword inside a comment must stay a comment.
  const stash = [];
  const keep = (html) => `\u0000${stash.push(html) - 1}\u0000`;
  out = out
    .replace(/(^|\n)(\s*)(;[^\n]*)/g, (m, nl, sp, c) => nl + sp + keep(`<span class="c">${c}</span>`))
    .replace(/\/\/[^\n]*/g, (m) => keep(`<span class="c">${m}</span>`))
    .replace(/\/\*[\s\S]*?\*\//g, (m) => keep(`<span class="c">${m}</span>`))
    .replace(/#[^\n]*/g, (m) => (lang === "php" ? m : keep(`<span class="c">${m}</span>`)))
    .replace(/"(?:[^"\\\n]|\\.)*"/g, (m) => keep(`<span class="s">${m}</span>`));

  const kw = KEYWORDS[lang];
  if (kw) out = out.replace(kw, '<span class="k">$&</span>');
  out = out.replace(/\b\d+(?:\.\d+)?\b/g, '<span class="n">$&</span>');
  // A capitalised word is a type in every one of these languages often enough
  // to be worth the colour.
  out = out.replace(/\b([A-Z][A-Za-z0-9_]{1,})\b/g, '<span class="t">$1</span>');

  return out.replace(/\u0000(\d+)\u0000/g, (m, i) => stash[+i]);
}

const srcEl = document.getElementById("srcCode");
const outEl = document.getElementById("outCode");
const cmdEl = document.getElementById("outCmd");
const noteEl = document.getElementById("outNote");
const tabsEl = document.getElementById("tabs");

if (DATA && srcEl && outEl && tabsEl) {
  srcEl.innerHTML = highlight(DATA.source, "ranger");

  const ids = Object.keys(DATA.targets);
  const show = (id) => {
    const t = DATA.targets[id];
    outEl.innerHTML = highlight(t.code, t.hl);
    cmdEl.textContent = t.cmd;
    noteEl.textContent = t.skipped
      ? `after ${t.skipped} lines of the small runtime every ${t.label} output carries`
      : "";
    for (const b of tabsEl.children) b.setAttribute("aria-selected", String(b.dataset.id === id));
  };

  for (const id of ids) {
    const b = document.createElement("button");
    b.className = "tab";
    b.type = "button";
    b.role = "tab";
    b.dataset.id = id;
    b.textContent = DATA.targets[id].label;
    b.addEventListener("click", () => show(id));
    tabsEl.append(b);
  }
  show(ids[0]);
} else if (srcEl) {
  // The generated file is missing — say so where it would have been rather
  // than leaving "loading…" on the page for ever.
  srcEl.textContent = "The compiled examples are generated by landing/tools/examples.mjs.";
  if (outEl) outEl.textContent = "Run: node landing/tools/examples.mjs";
}

/* ---------------------------------------------------------- the hero ---- */
startHero(document.getElementById("heroBg"), { host: document.getElementById("hero") });
