#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The exported application, assembled: the runtime compiled without the
// editor, wrapped as an ES module, EVG's browser helpers beside it, and the
// document it opens on.
//
//   npm run rave:export                      # beside the sources
//   node gallery/rave/export/build.mjs --out DIR   # for the site
//   node gallery/rave/export/build.mjs --app FILE  # ship this document
//
// `app.rave.json` is what the editor's Save writes. With none given the
// starter document is written, which is what /rave/app/ opens on.

import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MODULE = path.join(HERE, "..");                // gallery/rave
const GALLERY = path.join(MODULE, "..");             // gallery

const argv = process.argv.slice(2);
const flag = (name) => {
  const i = argv.indexOf(name);
  return i >= 0 ? path.resolve(argv[i + 1]) : null;
};
const OUT = flag("--out");
const APP = flag("--app");

const COMPILED = path.join(MODULE, "bin", "RaveExport.cjs");
if (!fs.existsSync(COMPILED)) {
  console.error("the runtime is not built — run `npm run rave:export:build` first");
  process.exit(3);
}

// --- the runtime, as an ES module ------------------------------------------------
const cjs = fs.readFileSync(COMPILED, "utf8");
const names = [...cjs.matchAll(/^module\.exports\.(\w+)\s*=/gm)].map((m) => m[1]);
if (!names.includes("RaveExport")) {
  console.error("the compiled module does not export RaveExport");
  process.exit(4);
}
const wrapped = `// Generated by gallery/rave/export/build.mjs — do not edit.
// SPDX-License-Identifier: AGPL-3.0-or-later
const module = { exports: {} };
{
${cjs}
}
const RaveModule = module.exports;
export default RaveModule;
export const { ${names.join(", ")} } = RaveModule;
`;
fs.writeFileSync(path.join(HERE, "generated-host.js"), wrapped);

// --- the document ----------------------------------------------------------------
const require = createRequire(import.meta.url);
const { RaveExport } = require(COMPILED);
let doc = "";
if (APP) {
  doc = fs.readFileSync(APP, "utf8");
  if (!RaveExport.isDocument(doc)) {
    console.error(`${APP} is not a Rave document`);
    process.exit(4);
  }
} else {
  doc = RaveExport.starter();
}
fs.writeFileSync(path.join(HERE, "app.rave.json"), doc);

// --- EVG's browser helpers ---------------------------------------------------------
const ENTRY_IMPORTS = ["evg/gl/evg-webgl.js", "evg/gl/evg-a11y.js", "evg/gl/evg-measure.js"];

function relativeImports(text) {
  const out = [];
  for (const m of text.matchAll(/(?:^|\s)(?:import|export)[^;]*?from\s*["'](\.[^"']+)["']/g)) out.push(m[1]);
  for (const m of text.matchAll(/import\s*\(\s*["'](\.[^"']+)["']\s*\)/g)) out.push(m[1]);
  return out;
}

function helperClosure() {
  const seen = new Set();
  const queue = [...ENTRY_IMPORTS];
  while (queue.length) {
    const rel = queue.shift();
    if (seen.has(rel)) continue;
    const from = path.join(GALLERY, rel);
    if (!fs.existsSync(from)) {
      console.error(`the page imports ${rel}, which is not in gallery/`);
      process.exit(4);
    }
    seen.add(rel);
    for (const next of relativeImports(fs.readFileSync(from, "utf8"))) {
      queue.push(path.posix.normalize(path.posix.join(path.posix.dirname(rel), next)));
    }
  }
  return [...seen];
}

const HELPERS = helperClosure();
function copyHelpers(root) {
  for (const rel of HELPERS) {
    const to = path.join(root, rel);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(path.join(GALLERY, rel), to);
  }
}
copyHelpers(HERE);

function assertResolvable(root) {
  for (const name of ["main.js", "generated-host.js"]) {
    const file = path.join(root, name);
    for (const rel of relativeImports(fs.readFileSync(file, "utf8"))) {
      if (!fs.existsSync(path.join(path.dirname(file), rel))) {
        console.error(`${name} imports ${rel}, which is not beside it in ${path.relative(process.cwd(), root)}`);
        process.exit(4);
      }
    }
  }
}
assertResolvable(HERE);

if (OUT) {
  fs.mkdirSync(OUT, { recursive: true });
  for (const name of ["index.html", "main.js", "generated-host.js", "app.rave.json"]) {
    fs.copyFileSync(path.join(HERE, name), path.join(OUT, name));
  }
  copyHelpers(OUT);
  assertResolvable(OUT);
  process.stdout.write(`  ${path.relative(process.cwd(), OUT)}  index.html + app.rave.json + ${HELPERS.length + 2} modules\n`);
} else {
  const kb = (wrapped.length / 1024).toFixed(0);
  process.stdout.write(`  gallery/rave/export  generated-host.js ${kb} kB, app.rave.json and EVG helpers written\n`);
}
