#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The simulator, for a browser.
//
//   node gallery/firesim/web/build.mjs
//
// No bundler. The compiled module is one self-contained CommonJS file with no
// `require` in it at all — the Ranger sources import each other and the
// compiler flattens them — so turning it into an ES module for a page is a
// wrapper and a re-export, and the page has no build step to go stale.
//
// This is what makes "run the whole thing in the browser" true rather than a
// plan: the store, the query engine, the rules parser, the accounts and the
// model are the same code the Node checks run, executing in the tab, with no
// emulator, no Java, no Docker and no network.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MODULE = path.join(HERE, "..");
const SOURCE = path.join(MODULE, "bin", "FsSimBridge.cjs");
const OUT = path.join(HERE, "firesim.browser.js");

if (!fs.existsSync(SOURCE)) {
  console.error("the module is not built — run `npm run firesim:build` first");
  process.exit(3);
}

const cjs = fs.readFileSync(SOURCE, "utf8");
if (/\brequire\s*\(/.test(cjs)) {
  console.error("the compiled module now has a require() in it; this wrapper assumes it has none");
  process.exit(4);
}

const names = [...cjs.matchAll(/^module\.exports\.(\w+)\s*=/gm)].map((m) => m[1]);
if (names.length === 0) {
  console.error("no exports found in the compiled module");
  process.exit(4);
}

const wrapped = `// Generated by gallery/firesim/web/build.mjs — do not edit.
// SPDX-License-Identifier: AGPL-3.0-or-later
const module = { exports: {} };
{
${cjs}
}
const Firesim = module.exports;
export default Firesim;
export const { ${names.join(", ")} } = Firesim;
`;

fs.writeFileSync(OUT, wrapped);
process.stdout.write(`  ${path.relative(process.cwd(), OUT)}  ${(wrapped.length / 1024).toFixed(0)} kB, ${names.length} exports\n`);
