#!/usr/bin/env bash
# Sync game-engine runtime tree into a deploy directory.
#
# Preserves gallery/game_engine/... layout so game_sdl default paths
# (games/, menu/, scripting/) resolve when the bundle root is the CWD.
#
# Usage:
#   ./gallery/game_engine/scripts/sync-game-engine-runtime.sh dist/raspberry-pi5

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
DEST="${1:?usage: sync-game-engine-runtime.sh <dest-dir>}"

GE="$ROOT/gallery/game_engine"

echo "==> Sync game-engine runtime -> $DEST"

copy_tree() {
  local src="$1" rel="$2"
  local dst="$DEST/$rel"
  rm -rf "$dst"
  mkdir -p "$(dirname "$dst")"
  cp -a "$src" "$dst"
}

# TSX launcher: games, menu, scripting (imports + shared assets).
copy_tree "$GE/games" "gallery/game_engine/games"
copy_tree "$GE/menu" "gallery/game_engine/menu"
copy_tree "$GE/scripting" "gallery/game_engine/scripting"

# Drop generated frame dumps (regenerated by runner demos).
find "$DEST/gallery/game_engine/scripting" -name '*.rgba' -delete 2>/dev/null || true

# Top-level engine modules (gfx_sdl, pong_sdl, framebuffer, …).
mkdir -p "$DEST/gallery/game_engine"
for f in "$GE"/*.rgr; do
  cp "$f" "$DEST/gallery/game_engine/"
done

# On-device Ranger compiles (RANGER_LIB=compiler/Lang.rgr:lib/stdops.rgr).
copy_tree "$ROOT/lib" "lib"
mkdir -p "$DEST/compiler" "$DEST/bin"
cp "$ROOT/compiler/Lang.rgr" "$DEST/compiler/Lang.rgr"
cp "$ROOT/bin/output.js" "$DEST/bin/output.js"
cp "$ROOT/lib/stdops.rgr" "$DEST/bin/stdops.rgr"
cp "$ROOT/bin/Lang.rgr" "$DEST/bin/Lang.rgr"

# C runtime + SDL/WASM helper sources for on-device rebuilds on the Pi.
mkdir -p "$DEST/runtime" "$DEST/gallery/invaders"
cp "$ROOT/runtime/ranger_rt.c" "$DEST/runtime/ranger_rt.c"
cp "$ROOT/runtime/ranger_mem.c" "$DEST/runtime/ranger_mem.c"
cp "$ROOT/runtime/rg_wasm_bridge.c" "$DEST/runtime/rg_wasm_bridge.c"
cp "$ROOT/runtime/rg_wasm_bridge.h" "$DEST/runtime/rg_wasm_bridge.h"
copy_tree "$ROOT/runtime/wasm3" "runtime/wasm3"
cp "$ROOT/gallery/invaders/variant.hpp" "$DEST/gallery/invaders/variant.hpp"

# Build helpers (run from bundle root on the Pi).
mkdir -p "$DEST/gallery/game_engine/scripts"
for script in build-native.sh build-sdl.sh build-game-sdl.sh sync-game-engine-runtime.sh sync-pi-games.sh deploy-pi.sh; do
  cp "$GE/scripts/$script" "$DEST/gallery/game_engine/scripts/$script"
done

echo "   gallery/game_engine/{games,menu,scripting,*.rgr,scripts}"
echo "   lib/, compiler/Lang.rgr, bin/{output.js,stdops.rgr,Lang.rgr}"
echo "   runtime/{ranger_rt.c,ranger_mem.c,rg_wasm_bridge.*,wasm3/}, gallery/invaders/variant.hpp"
