#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// WRITE THE HEAD THAT STARTS EVERYTHING.
//
//   node gallery/evg/web/tools/inline-assets.mjs \
//     --html DIR/index.html \
//     --start fonts/A.ttf,fonts/B.ttf,presets.txt,deck.pptx \
//     --preload standalone.mjs,gl/evg-webgl.js \
//     --stamp <build id>
//
// Every gallery page fetched its assets the same way and in the same wrong
// order: after its engine had loaded and its module had run, one await at a
// time. The requests need no code, so they can go out while the code is still
// coming — and then a visitor waits for the LONGEST of the downloads rather
// than for their sum.
//
// This writes that head, from a list, so the pattern is one build line per
// page rather than a paragraph of hand-written script in each. The module side
// is `assets-client.mjs`, which picks the responses up by name.
//
// The list is the build's, taken from wherever the page's own font table
// lives, so it cannot drift from what the module asks for — an asset in one
// and not the other is either fetched twice or waited for and never started,
// and neither shows up as an error.

import fs from "node:fs";

const argv = process.argv.slice(2);
const flag = (name, fallback) => {
  const at = argv.indexOf(name);
  return at >= 0 ? argv[at + 1] : fallback;
};
const list = (name) => (flag(name, "") ? flag(name, "").split(",").filter(Boolean) : []);

const html = flag("--html");
const start = list("--start");
const preload = list("--preload");
const stamp = flag("--stamp", "");
const openParam = flag("--open-param");

if (!html || !fs.existsSync(html)) {
  console.error("usage: inline-assets.mjs --html <file> --start a,b --preload c,d [--stamp id] [--open-param open]");
  process.exit(2);
}

const MARK = "<!-- evg:assets -->";
let src = fs.readFileSync(html, "utf8");
if (src.includes(MARK)) {
  console.error(`${html} already carries an evg:assets head`);
  process.exit(1);
}

const q = stamp ? `?v=${stamp}` : "";
const lines = [];
lines.push(`    ${MARK}`);
lines.push("    <!-- Generated by gallery/evg/web/tools/inline-assets.mjs.");
lines.push("       * Every asset this page needs, started before the body is parsed:");
lines.push("       * these requests need no code, so they must not wait for any. The");
lines.push("       * module picks the responses up by name (assets-client.mjs). -->");
lines.push("    <script>");
lines.push("      (function () {");
lines.push(`        var files = ${JSON.stringify(start)};`);
if (openParam) {
  lines.push("        // `?" + openParam + "=` names a file to open instead of the default, and is");
  lines.push("        // restricted to a plain name so a query string cannot make the page");
  lines.push("        // fetch somewhere else — the same rule the module applies.");
  lines.push(`        var wanted = new URLSearchParams(location.search).get(${JSON.stringify(openParam)});`);
  lines.push("        if (wanted && /^[\\w.-]+$/.test(wanted)) files.push(wanted);");
}
lines.push("        window.__evgAssets = {};");
lines.push("        files.forEach(function (f) {");
lines.push("          window.__evgAssets[f] = fetch('./' + f).catch(function (e) { return e; });");
lines.push("        });");
lines.push("      })();");
lines.push("    </script>");
for (const mod of preload) {
  lines.push(`    <link rel="modulepreload" href="./${mod}${q}" />`);
}

// After the charset, which must stay first, and before anything that could
// start a download of its own.
const anchor = /<meta charset="utf-8"\s*\/?>/i;
if (!anchor.test(src)) {
  console.error(`${html} has no <meta charset="utf-8"> to write after`);
  process.exit(1);
}
src = src.replace(anchor, (m) => `${m}\n${lines.join("\n")}`);
fs.writeFileSync(html, src);
console.log(`  head starts ${start.length} assets${openParam ? " (+?" + openParam + ")" : ""}, preloads ${preload.length}`);
