#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Writes src/unidata.rs: ComponentEngine's generated Unicode and locale
// tables (gallery/game_engine/v2/interp/migrate/src/Unicode*.rgr and
// Locale*.rgr) as data CEr reads.
//
//   node gallery/game_engine/v2/cer/tools/gen-unidata.cjs
//
// Every table becomes one string constant of decimal integers separated by
// commas, parsed on first use (unicode.rs `ints`). A table of strings is
// written as integers too -- each string as its length in code points and
// then the code points -- so the Rust source stays ASCII and every rgrc
// target reads it the same way. A string constant rather than a `vec![…]`
// literal: tens of thousands of elements are one token each for rgrc and
// the C++ / Go compilers, and a table nobody asks for costs nothing.
//
// The property ranges of \p{…} are one constant per property, so compiling
// /\p{L}/u parses the ranges of L and nothing else.

'use strict';
const fs = require('fs');
const path = require('path');

const here = __dirname;
const src = path.join(here, '..', '..', 'interp', 'migrate', 'src');
const out = path.join(here, '..', 'src', 'unidata.rs');

function tables(file) {
  const text = fs.readFileSync(path.join(src, file), 'utf8');
  const re = /static sfn (\w+):(\[\w+\]|\w+) \(\) \{\s*return ([\s\S]*?)\n    \}/g;
  const res = {};
  let m;
  while ((m = re.exec(text))) {
    const name = m[1];
    const type = m[2];
    let body = m[3].trim();
    if (type === 'int') {
      res[name] = parseInt(body, 10);
      continue;
    }
    body = body.replace(/^\(\[\]/, '').replace(/\)$/, '');
    const toks = body.match(/"(?:[^"\\]|\\.)*"|-?\d+/g) || [];
    if (type === '[string]') {
      res[name] = toks.map((t) => JSON.parse(t));
    } else if (type === '[int]') {
      res[name] = toks.map((t) => parseInt(t, 10));
    } else {
      throw new Error(file + ': ' + name + ': type ' + type);
    }
  }
  return res;
}

function ints(a) {
  for (const x of a) {
    if (!Number.isInteger(x) || x < 0 || x > 2147483647) throw new Error('not an int: ' + x);
  }
  return a.join(',');
}

function strs(a) {
  const o = [];
  for (const s of a) {
    const cps = Array.from(s).map((c) => c.codePointAt(0));
    o.push(cps.length);
    for (const c of cps) o.push(c);
  }
  return o.join(',');
}

const lines = [];
lines.push('// SPDX-License-Identifier: AGPL-3.0-or-later');
lines.push('//! GENERATED by tools/gen-unidata.cjs from ComponentEngine\'s tables');
lines.push('//! (gallery/game_engine/v2/interp/migrate/src/Unicode*.rgr, Locale*.rgr);');
lines.push('//! do not edit. What each table holds is written at the head of its');
lines.push('//! .rgr file. Integers separated by commas; a table of strings is each');
lines.push('//! string\'s length in code points followed by the code points.');
lines.push('');
lines.push('use ranger::prelude::*;');
lines.push('');

function konst(name, value, what) {
  lines.push('/// ' + what);
  lines.push('pub const ' + name + ': &str = "' + value + '";');
  lines.push('');
}

const norm = tables('UnicodeNorm.rgr');
konst('NORM_DECOMP', ints(norm.decomp), 'UnicodeNorm.decomp: (code point, count, points…)');
konst('NORM_CCC', ints(norm.cccRuns), 'UnicodeNorm.cccRuns: (start, end, class) triples');
konst('NORM_COMPOSE', ints(norm.compose), 'UnicodeNorm.compose: (starter, combining, composite) triples, sorted');

const coll = tables('UnicodeCollate.rgr');
konst('COLL_PUNCT', ints(coll.punctRuns), 'UnicodeCollate.punctRuns: (start, end, first rank) triples');
konst('COLL_EXPAND', ints(coll.expansions), 'UnicodeCollate.expansions: (code point, count, points…)');
konst('COLL_MARKS', ints(coll.markRanks), 'UnicodeCollate.markRanks: (mark, secondary rank) pairs, sorted');
konst('COLL_BASES', ints(coll.baseLetters), 'UnicodeCollate.baseLetters: (code point, secondary, count, points…)');

// The tailorings, less the entries this host's collator does not confirm.
// ComponentEngine's table files, for instance, "ss" and "ß" as letters after
// s in Swedish and æ as a letter after a in Polish, where ICU keeps the
// root order (ss before st, æ with ae). An element tailored after its
// anchor letter must sort after the anchor followed by anything, so each
// entry is kept only when the anchor followed by ezh (U+0292, a letter after z
// that starts no contraction) sorts before it in its locale.
function filterTailorings(t) {
  const locOut = [];
  const entOut = [];
  let dropped = 0;
  for (let i = 0; i < t.locales.length; ) {
    const n = t.locales[i];
    const tag = String.fromCodePoint(...t.locales.slice(i + 1, i + 1 + n));
    const off = t.locales[i + 1 + n];
    const cnt = t.locales[i + 2 + n];
    const coll = new Intl.Collator(tag);
    const start = entOut.length;
    let kept = 0;
    let p = off;
    for (let k = 0; k < cnt; k++) {
      const anchor = t.entries[p];
      const len = t.entries[p + 2];
      const elem = t.entries.slice(p + 3, p + 3 + len);
      const text = String.fromCodePoint(...elem).normalize('NFC');
      if (coll.compare(String.fromCodePoint(anchor) + '\u0292\u0292\u0292', text) < 0) {
        for (let q = 0; q < 3 + len; q++) entOut.push(t.entries[p + q]);
        kept++;
      } else {
        dropped++;
      }
      p += 3 + len;
    }
    locOut.push(n, ...t.locales.slice(i + 1, i + 1 + n), start, kept);
    i += 3 + n;
  }
  console.log('tailorings: dropped ' + dropped + ' entries the host collator does not confirm');
  return { locales: locOut, entries: entOut };
}
const tailor = filterTailorings(tables('UnicodeTailor.rgr'));
konst('TAILOR_LOCALES', ints(tailor.locales), 'UnicodeTailor.locales: (tag length, tag points…, entry offset, entry count)');
konst('TAILOR_ENTRIES', ints(tailor.entries), 'UnicodeTailor.entries: (anchor, offset, element length, element points…), less the entries the generating host\'s collator does not confirm (see tools/gen-unidata.cjs)');

const loc = tables('LocaleData.rgr');
konst('LOC_TAGS', strs(loc.tags), 'LocaleData.tags (strings)');
konst('LOC_NUMSTR', strs(loc.numStrings), 'LocaleData.numStrings (strings), 22 per locale');
konst('LOC_NUMINT', ints(loc.numInts), 'LocaleData.numInts, 5 per locale');
konst('LOC_NAMES', strs(loc.names), 'LocaleData.names (strings), 38 per locale');
konst('LOC_PATINT', ints(loc.patternInts), 'LocaleData.patternInts');
konst('LOC_PATSTR', strs(loc.patternStrings), 'LocaleData.patternStrings (strings)');
konst('LOC_CURSTR', strs(loc.currencyStrings), 'LocaleData.currencyStrings (strings): (code, symbol) per currency per locale');
konst('LOC_CURINT', ints(loc.currencyInts), 'LocaleData.currencyInts: 1 when the symbol is letters');
lines.push('/// LocaleData.currencyCount: currencies per locale');
lines.push('pub const LOC_CURCOUNT: int = ' + loc.currencyCount + ';');
lines.push('');

const pl = tables('LocalePlural.rgr');
konst('PLURAL_TAGS', strs(pl.tags), 'LocalePlural.tags (strings)');
konst('PLURAL_KEYS', strs(pl.keyList), 'LocalePlural.keyList (strings)');
konst('PLURAL_ENTRIES', ints(pl.entries), 'LocalePlural.entries: (offset, count, fallback) per locale per type');
konst('PLURAL_PAIRS', ints(pl.pairs), 'LocalePlural.pairs: (key id, category id)');
konst('LIST_SEPS', strs(pl.listSeparators), 'LocalePlural.listSeparators (strings): (pair, middle, end) x2 per locale');

const props = tables('UnicodeProps.rgr');
konst('PROP_NAMES', strs(props.names), 'UnicodeProps.names (strings), lowercased canonical property names');
const n = props.names.length;
for (let i = 0; i < n; i++) {
  const off = props.offsets[i];
  const cnt = props.counts[i];
  const r = props.ranges.slice(off * 2, (off + cnt) * 2);
  konst('PROP_' + i, ints(r), 'ranges of \\p{' + props.names[i] + '}: [lo, hi] pairs, sorted');
}
lines.push('/// The ranges of property `i` (an index into PROP_NAMES).');
lines.push('pub fn prop_ranges(i: int) -> String {');
for (let i = 0; i < n; i++) {
  lines.push('    if i == ' + i + ' {');
  lines.push('        return String::from(PROP_' + i + ');');
  lines.push('    }');
}
lines.push('    String::new()');
lines.push('}');
lines.push('');

fs.writeFileSync(out, lines.join('\n'));
console.log('wrote ' + path.relative(process.cwd(), out) + ' (' + fs.statSync(out).size + ' bytes)');
